README.md
Now that we have bootstrapped the repository and created initial tickets to keep track of ongoing work, let's reflect that in the roadmap.
=> Make the "Roadmap" section in the README more specific

docs/spec_draft.md
Addressing the comment at https://github.com/openxla/stablehlo/commit/27259786691d11c7bb4b12949765d539798c8491#r82206039
=> clarified the semantics of 0 dimension of a tensor

docs/spec_draft.md
fixes https://github.com/openxla/stablehlo/issues/55
=> Add specifications for maximum and minimum operators

docs/spec_draft.md
=> Add specifications for constant operator

docs/spec_draft.md
=> Fix examples to include operand and result names

docs/spec_draft.md
=> Add specifications for sine, cosine, and tanh operators

docs/spec_draft.md
=> Add specifications for sqrt and rsqrt operators

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h
wontfix https://github.com/openxla/stablehlo/issues/82
=> Remove the redundant fp equality comparison function.

docs/spec_draft.md
=> Add specification for log op

docs/spec_draft.md
=> Add specification for logistic operator

docs/spec_draft.md
fixes https://github.com/openxla/stablehlo/issues/77
=> Add spec of div/rem

docs/spec_draft.md
fixes https://github.com/openxla/stablehlo/issues/95
=> Clarification on floating-point exception env.

stablehlo/tests/interpret_constant.mlir
=> Add test for constant op

docs/implementation_progress.md
fixes https://github.com/openxla/stablehlo/issues/16
=> Tracking of completeness of the implementation

docs/spec_draft.md
=> Add specification for exp operator

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_sine.mlir
=> Add interpreter for sine op

docs/governance.md
Bootstraps StableHLO governance from the SIG OpenXLA charter: https://github.com/tensorflow/community/blob/master/rfcs/20220713-sig-open-xla.md.
In a follow-up pull request, I'll propose a process by which we'll be reviewing
StableHLO RFCs: https://github.com/openxla/stablehlo/labels/RFC.
=> Bootstrap StableHLO governance

docs/spec_draft.md
=> Fix a few typos in the spec

docs/status.md, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_cosine.mlir, stablehlo/tests/interpret_tanh.mlir
=> Add interpreters for cosine and tanh op

docs/interpreter.md, docs/spec_draft.md, docs/status.md, stablehlo/reference/Element.cpp, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/tests/interpret_reshape.mlir
fixes https://github.com/openxla/stablehlo/issues/169
~Diff based on https://github.com/openxla/stablehlo/pull/167~
upd: Checked that the spec matches with the verifier of the Op.
=> Specification and Interpreter for  reshape op

docs/spec_draft.md, docs/status.md, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/infer_subtract.mlir, stablehlo/tests/interpret_subtract.mlir
=> Add specification and interpreter for SubtractOp

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Interpreter.cpp
Changes built on top of #202.
Adapted from a patch by @tpopp (thank you).
Closes #146
=> Update to use prefixed accessors

stablehlo/reference/CMakeLists.txt, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Types.cpp, stablehlo/reference/Types.h
=> Move type utilities into a separate file

docs/spec_checklist.md
This will hopefully help with reviewing StableHLO spec pull requests.
=> Add a StableHLO specification checklist

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
=> Add spec for ConcatenateOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ReverseOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for PadOp

docs/spec_draft.md, docs/status.md
fixes https://github.com/openxla/stablehlo/issues/263
=> Update spec of AbsOp to match HLO semantics

stablehlo/dialect/Base.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp
=> Fix clang tidy name mismatches

docs/spec_draft.md
Our discussions in #280 provided some additional notational inspiration, and I think I've got something that's readable and correct.
=> Add formal notation for PadOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_multiply.mlir
Wording for add and subtract is updated: integer overflow/underflow -> overflow.
closes #199
=> Add specification and interpreter for MulOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
Adds the specification as  part of #122 
Fixes https://github.com/openxla/stablehlo/issues/277
=> Add spec for BroadcastInDimOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for SliceOp

docs/spec_draft.md
This supports ongoing work on sort (#259) and reduce (#300).
=> Introduce function types

docs/spec_draft.md
refactor to have consistent usages of "any supported element types"
=> Refactor spec to have consistent usage of "any supported element types"

docs/status.md
=> Update verification status for PadOp to `yes`

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for IfOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for CaseOp

.gitignore, docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for SortOp

stablehlo/tests/infer_stablehlo.mlir
Fix with better error messages and fully align with MHLO.
=> Quick fix reduce and reduce_window tests

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
fix https://github.com/openxla/stablehlo/issues/370
=> Merge verify and shape function of BatchNorm ops

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/infer_stablehlo.mlir
=> Update SetDimensionSize type inference to recognise constant sizes

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for WhileOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for CholeskyOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for PopulationCountOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for SelectOp

docs/spec_checklist.md
This is something that we've been following for some time now, and I figured it'd be good to document explicitly and have a chance to discuss.
=> Update spec checklist to account for prettyprinting conventions

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for BatchNormInferenceOp

docs/status.md
Updates the wording that explain in details what various labels means, consistent with how we've been using them in the last two months.
=> Update status.md to reflect conventional use

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ReduceOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ClzOp

docs/spec_draft.md, stablehlo/dialect/StablehloOps.td
Thank you, Sandeep, for discovering and documenting this in #351!
=> Fix discrepancy between names in Outputs and in the ODS

stablehlo/dialect/Register.cpp
=> Add SparseTensorDialect to  registration

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ComplexOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for RealOp and ImagOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for Expm1Op

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Verification is set to revisit due to #534
closes #358
=> Add spec for TriangularSolveOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for Atan2Op

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
closes #472 
Revisit verification for Log1pOp to disallow complex type operand #506
=> Add spec for Logp1Op

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for IsFiniteOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for RoundNearestEvenOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
closes #477
closes #479
closes #478
=> Add spec for ShiftLeftOp, ShiftRightArithmeticOp and ShiftRightLogicalOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for GetTupleElementOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for TupleOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ClampOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for CbrtOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for PowOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
closes #419 
Ticket for verification #571
=> Add spec for CompareOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for BitcastConvertOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for SignOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for BatchNormGrad

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ReplicaIdOp

docs/spec_draft.md
=> reorder AllGather and AllToAll Ops

docs/spec_draft.md
This is the feedback that I noticed in final stages of PR review but didn't want to introduce extra back and forth rounds of reviews for.
=> Minor fixes to recently merged specs

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir
fixes #504  
Address the followings:
1.  Adds verification checks for AllGather w.r.t. https://github.com/openxla/stablehlo/issues/498
2. Fixes https://github.com/openxla/stablehlo/issues/508
=> Add spec for AllReduceOp

stablehlo/dialect/ChloOps.td
fixes https://github.com/openxla/stablehlo/issues/709
=> Preparation change for MLIR to only produce prefixed accessor.

docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
=> Add type inference for AfterAllOp

docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
=> Add type inference for GetDimensionSizeOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ReducePrecisionOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for ConvertOp

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
Removes negative DotOp test since the verifier is removed.
closes #682
=> Remove DotOp verifier

stablehlo/tests/infer_stablehlo.mlir
=> Add tests, increase coverage, cover reifyReturnTypeShapes for ops.

docs/spec.md
As the first step towards implementing #484, this PR introduces an EBNF grammar for the StableHLO language, modelling it after the generic assembly format of the StableHLO dialect.
In addition to creating a foundation for future work as described in
#484, this PR immediately improves clarity of the Types and Constants
sections of the specification.
Next steps involve: 1) writing the Notation section along the lines of
#289, 2) formalizing execution of the StableHLO language in the
Execution section.
=> First step towards turning spec.md into a programming language spec

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
=> Add verification for DotOp precision config

docs/spec.md
fixes https://github.com/openxla/stablehlo/issues/857
=> Add missing constraint for selectAndScatter op

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
The PR fixes #799 (please refer this for more details)
Adding @smit-hinsu for review.
=> Handle Dynamic Bounds in Shape Function of DynamicUpdateSliceOp

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_conv.mlir
MLIR-HLO commit: tensorflow/mlir-hlo@35ee344.
=> Also allow one item in precision_config

stablehlo/dialect/TypeInference.cpp
Refactors TypeInference.cpp to use
`verifyCompatibleDims(dimSize1, dimSize2)` instead of the equivalent but more verbose:
```
isDynamicDimSize(dimSize1) || isDynamicDimSize(dimSize2) ||
dimSize1 == dimSize2
```
=> Simplify some dimension checks by using verifyCompatibleDims

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir
=> Verify exponent and mantissa in ReducePrecisionOp

docs/spec.md
Renames all instances of "grid" to "process grid"
closes #669
=> Rename grid to "process grid"

docs/spec.md
For more details please refer to the ticket below.
fixes https://github.com/openxla/stablehlo/issues/846
=> Added missing detail for remainder op

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloDialect.td, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td
=>  Reorganize VHLO .td files

docs/reference.md, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/VhloDialect.td
This is just an NFC change, and the folders should be cleaned up
afterwards.
=> Update dialects to use the folder adaptors

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/legalize_stablehlo_to_vhlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/print_stablehlo.mlir
=> Verify compare_type for compare_op.

stablehlo/dialect/StablehloOps.td
MLIR-HLO commit: tensorflow/mlir-hlo@539446d.
=> Mark ReducePrecisionOp as [Pure]

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
MLIR-HLO commit: tensorflow/mlir-hlo@f95a903.
=> Support ReduceWindowOp creation with a Region

stablehlo/dialect/StablehloOps.td
MLIR-HLO commit: tensorflow/mlir-hlo@6353126.
=> Document TorchIndexSelectOp

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/infer_stablehlo.mlir
MLIR-HLO commit: tensorflow/mlir-hlo@0c65568.
=> Fix reifyGatherShape to return tensors of index

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_reverse.mlir, stablehlo/tests/ops_stablehlo.mlir
=> Add interpreter for ReverseOp

docs/spec.md
`adjusted_start_indices` seems like a 1-d tensor from the type of `shape(operand)` in `clamp(0, start_indices, shape(operand) -slice_sizes)`.
=> Fix the notations for dynamic_update_slice and dynamic_slice

stablehlo/transforms/StablehloRefineShapes.cpp
Come up during internal integration.
=> Addressed a few clang-tidy suggestions

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
Move inferRngOp() and merge with verifyRngOp().
=> Move and merge inferRngOp

docs/reference_checklist.md
Please refer to https://github.com/openxla/stablehlo/pull/996#discussion_r1096336612
=> Update reference checklist w.r.t adding testing strategy

docs/spec.md
See #1156 (Decide on speccing numerical accuracy) and #1157 (Audit numerical corner cases) for more details.
=> Link recently added frontend contract tickets in the spec

stablehlo/dialect/StablehloOps.td
Migrate back from MHLO change: https://github.com/tensorflow/mlir-hlo/commit/69acab5abd3b6468703d31e83ff4f4871f887fa4
=> Remove the undefined AllReduceOp build()

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloEnums.td, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td
=> Remove default values for VHLO versions in Enums / Attrs / Types / Ops

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
MLIR-HLO commit: https://github.com/tensorflow/mlir-hlo/commit/15a5cd35cca34f39cd528eaa6beda0d828ea7331
=> Use std::optional instead of llvm::Optional

stablehlo/dialect/StablehloOps.td
MLIR-HLO commit: https://github.com/tensorflow/mlir-hlo/commit/d4f40974fe47f0ce7b5b03ac4ee1d6b1bc77d3ba.
Closes #611
=> Standardize summaries

stablehlo/dialect/Base.cpp
=> Fix crash in typechecker

docs/reference.md, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h
fixes https://github.com/openxla/stablehlo/issues/1275
Please refer to https://github.com/openxla/stablehlo/issues/1275 for the motivation behind the current change.
=> Fix for float diff error on Mac platform

docs/spec.md
Fix a bug in how pad is used in specification.
=> Update how pad is used in spec

stablehlo/tools/StablehloTranslateMain.cpp
This PR is to refactor the custom-call eval function which has been recently added to improve interpreter testing (#1290).
=> Refactor CustomCallOp evaluator

docs/spec.md
fixes https://github.com/openxla/stablehlo/issues/1338
Please refer to the https://github.com/openxla/stablehlo/issues/1338 for more details.
=> Spec update for ConvolutionOp: Clarify permute

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/tests/CheckOps.cpp
=> Unify APIs in Element.h

docs/spec.md
Following up on #1352, this pull request documents the unresolved conversations from that PR review.
=> Document open questions in the quantization spec

docs/vhlo.md
Add guidelines for implementing compatibility for new StableHLO features in VHLO. Will be useful to link to this doc in future reviews.
This does not impact anything about the compatibility process in `compatibility.md` or the Compatibility RFC, this is intended to aid developers.
=> Update `vhlo.md` with contribution guidelines.

stablehlo/testdata/asin_shape_complex64_20_20.mlir, stablehlo/testdata/atan_shape_complex64_20_20.mlir, stablehlo/testdata/bessel_i1e_shape_float32_20_20.mlir, stablehlo/testdata/shift_left_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_left_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir
A few interpreter tests which might have missed enabling.
=> enable a few interpreter tests

stablehlo/transforms/StablehloRefineShapes.cpp
This PR is based on #1452.
StableHLO ops don't actually support index element types, except in
rare situations (see uses of HLO_DimensionTensor in the TableGen file)
which don't apply to Eval patterns.
=> Drop support for index element types in Eval patterns

docs/compatibility.md
=> Add note on version bumping to compatibility.md

docs/reference_checklist.md
=> Clarify the checklist wording and provide examples

stablehlo/reference/Ops.cpp
The recent PR has merged with breakage in its tests, so this PR fixes it.
=> Fix CholeskyOp breakage

stablehlo/reference/Element.cpp
This is the same as #1293, but on newly added code.
=> Fix build error on macOS

stablehlo/dialect/TypeInference.cpp
While reviewing PRs that implement interpreters for ReduceOp and ReduceWindowOp, I noticed that the verifiers can be somewhat simplified. This PR does the necessary cleanup.
=> Simplify verification of ReduceOp and ReduceWindowOp

WORKSPACE.bazel, build_tools/llvm_version.txt
Need to clean up `llvm_disable_optional_support_deps` after:
https://reviews.llvm.org/D151006
=> Integrate LLVM at llvm/llvm-project@e837f4b7

stablehlo/reference/Ops.cpp
When reviewing the ScatterOp PR, I saw a few opportunities for making the code a bit more compressed.
=> Compress the code a little bit

rfcs/20230525-compatibility.md
Cloned from OpenXLA Discuss [[RFC] Reduce StableHLO v1.0 Compatibility Guarantees](https://groups.google.com/a/openxla.org/g/openxla-discuss/c/yYjTDAsoygQ)
=> [RFC] Reduce StableHLO v1.0 Compatibility Guarantees

rfcs/20230528-linalg.md
This PR archives an approved RFC from [openxla-discuss](https://groups.google.com/a/openxla.org/g/openxla-discuss/c/KsRp9euuuB0).
=> [RFC] Add StableHLO => Linalg lowering to openxla/stablehlo

stablehlo/tools/CMakeLists.txt, stablehlo/tools/StablehloLspServerMain.cpp
This allows VSCode plugin integration as documented here:
https://mlir.llvm.org/docs/Tools/MLIRLSP/#mlir-lsp-language-server--mlir-lsp-server
=> Add stablehlo-lsp-server

BUILD.bazel, stablehlo/tools/CMakeLists.txt, stablehlo/tools/StablehloLspServerMain.cpp
Add Bazel build, integrate building stablehlo-lsp-server into CI.
=> Further integrate stablehlo-lsp-server into our build

stablehlo/dialect/ChloOps.td, stablehlo/tests/ops_chlo.mlir
Port of https://github.com/tensorflow/mlir-hlo/commit/65666664af3d400bd3ddc4fd581e3345e259468f
=> Add HLO_CompatibleOperandsAndResultElementType to CHLO broadcast MinOp and MaxOp

docs/spec.md
=> Elaborate on the semantics of tokens

stablehlo/dialect/Base.cpp, stablehlo/tests/stablehlo_refine_shapes.mlir
MLIR-HLO commit: https://github.com/tensorflow/mlir-hlo/commit/35f099cb3b784bf2b5130c526f7538ab01f7bc22
=> Fix --stablehlo-refine-shapes for i1 => ... conversions

docs/spec.md
=> Typo in convolution constraint

stablehlo/dialect/Base.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp
Port of https://github.com/tensorflow/mlir-hlo/commit/5aa3df6e13ea76f3290414e011f60113d5d26e65 and https://github.com/tensorflow/mlir-hlo/commit/f7fa8f5b6e0f9a058913000ab9c8966ae730a343
=> Patch changes from previous integrate

docs/spec.md
This PR **partially** solves #1574 in the sense that it just proposes a specification for per-axis quantitation scheme.
In the current proposal  we defined the semantics as part of quantize/dequantize meta functions avoiding text descriptions to provide more clarity. 
Please let me know your feedback.
=> Add specification for per-axis quantization scheme

stablehlo/dialect/ChloOps.h, stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/VhloDialect.td, stablehlo/reference/InterpreterOps.td, stablehlo/tests/CheckOps.h, stablehlo/tests/CheckOps.td
Port of https://github.com/tensorflow/mlir-hlo/commit/e8a6a7c2b51f7f7e27d050afbc115e805b8a9fc6
=> [NFC] Explicitly set dialects to usePropertiesForAttributes=0

stablehlo/tests/ops_stablehlo_roundtrip.mlir
Port of https://github.com/tensorflow/mlir-hlo/commit/c20cbf28f7963aed769c280aa7ab5f39ec4ba2f1
=> Remove XLA attribute from test

rfcs/20230210-sparsity.md
A few edits to make the proposal more consistent with the updated MLIR doc
=> Minor edits to the sparsity RFC

stablehlo/tests/ops_stablehlo.mlir
Corresponding MHLO change:https://github.com/tensorflow/mlir-hlo/commit/368ad52820900f56b606bf0fbc2758f36dcffa08
=> Fixing order of tests introduced in #1782

BUILD.bazel, stablehlo/reference/CMakeLists.txt, stablehlo/reference/InterpreterOps.h, stablehlo/tests/BUILD.bazel, stablehlo/tests/CMakeLists.txt
=> Fix clang tidy, remove unused dependencies

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/print_reduce.mlir
Backport of https://github.com/tensorflow/mlir-hlo/commit/b482677b8f00a9bd1a59f315d2176d5ee9b17b0b.
=> Print optional attr-dict on stablehlo.reduce

BUILD.bazel, stablehlo/reference/Ops.cpp
* Add missing dependency to reference_interpreterconfiguration.
* Update `/*config=*/` comments to `/*fallback=*/` following the recent rename.
=> Fix issues found during the recent downstream integrate

stablehlo/transforms/Passes.h
Backport of https://github.com/tensorflow/mlir-hlo/commit/e2805725a7ec22b4393848bb1083ea663313c141.
=> Minor code style updates

stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp, stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.h, stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h, stablehlo/conversions/linalg/transforms/Rewriters.h, stablehlo/conversions/linalg/transforms/StablehloToArith.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgRandom.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp, stablehlo/conversions/linalg/transforms/TypeConversion.cpp, stablehlo/conversions/linalg/transforms/TypeConversion.h
Updating license per discussion in https://github.com/openxla/stablehlo/pull/1817#issuecomment-1813203843
cc @ashay
=> Update license to be consistent with StableHLO project

stablehlo/tests/stablehlo_legalize_to_vhlo.0_15_0.mlir
Discovered in https://github.com/openxla/stablehlo/pull/1856#discussion_r1406841979
=> Fix 0.15.0 compatibility test to use proper run commands

BUILD.bazel, stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/StablehloTypes.td, stablehlo/dialect/VhloDialect.td, stablehlo/dialect/VhloTypes.td, stablehlo/tests/ops_stablehlo.mlir
=> Use ODS for StableHLO types

docs/spec.md
=> Clarify semantics of `ReduceWindowOp` and `SelectAndScatterOp`

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_reduce.mlir
In the same vein as https://github.com/openxla/stablehlo/pull/1893.
https://github.com/openxla/stablehlo/issues/1578
=> Port {Map,Reduce}Op  to I64DenseArrayOrElements1DAttr

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp
In the same vein as #1893.
#1578
=> Port SelectAndScatterOp to I64DenseArrayOrElements1DAttr

stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/tests/verify_reduce_window.mlir
In the same vein as https://github.com/openxla/stablehlo/pull/1893.
https://github.com/openxla/stablehlo/issues/1578
=> Port ReduceWindowOp to I64DenseArrayOrElements1DAttr

stablehlo/transforms/VhloLegalizeToStablehlo.cpp
I'm not sure specifically why this is happening, but creating a SmallVector from an ArrayRef can cause an illegal instruction because the memory can be misaligned. I will investigate further offline, but for now let's fix the bug.
=> Fix memory alignment bug in dense array conversion

stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_10_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_11_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_12_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_13_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_14_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_15_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_16_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_17_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.0_9_0.mlir, stablehlo/tests/vhlo/stablehlo_legalize_to_vhlo.mlir
ref: https://github.com/openxla/stablehlo/issues/1843
Tested: local test run, presubmit run
=> Add CHECK to validate resulting VHLO include reduce_v1

docs/compatibility.md
ref: https://github.com/openxla/stablehlo/issues/1653
=> Minor update to compatibility doc wrt serialization

docs/spec.md
https://github.com/openxla/stablehlo/issues/1578
=> Port dense literals to array literals in spec

stablehlo/dialect/Register.cpp
Bug fix to register `mlir::quant::QuantizationDialect`.
=> Register `QuantizationDialect`

README.md
to build the project we need to run `cmake --build .` after `cmake ..`
=> Add cmake --build to Build instructions

MODULE.bazel, MODULE.bazel.lock, stablehlo/transforms/ChloDecompositionPatterns.td, stablehlo/transforms/ChloLegalizeToStablehlo.cpp, stablehlo/transforms/StablehloAggressiveSimplification.cpp
Also includes framing the version string in ways expected by some internal integration tooling.
=> fix copyright message for a few files

docs/reference_checklist.md
=> Update recommended path for examples

docs/spec.md
Please find the specification of quantized `collective_broadcast` op. The specification is proposed to be similar to other distribution ops like `collective_permute`.
Let me know your feedback. 
@loganchien 
@paulinesho
@doyeonkim0
=> Specification of quantized collective_broadcast op

stablehlo/transforms/ChloLegalizeToStablehlo.cpp, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloAggressiveSimplification.cpp
Extending work done in #1919 and #1966.
=> Use initialize and generate getDependentDialects for passes from IREE

build_tools/github_actions/lint_check_license.sh
Addressing prior review feedback: https://github.com/openxla/stablehlo/pull/2018/files/001999860b0f236614b0e64493a447c9b0c85490#r1495173847
=> Check copyright year and license type in license check

stablehlo/dialect/Base.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_quantized.mlir
and make Quantized test compatible. This was missed during resolving merged conflict 
for https://github.com/openxla/stablehlo/pull/2007
=> Make HLO_FpOrQuantizedIntTensor def RankedTensorOf

rfcs/20230609-extensibility.md
This PR does not contain an actual RFC - it's merely tracking a discussion on openxla-discuss: https://groups.google.com/a/openxla.org/g/openxla-discuss/c/Ao5K8fvXoEk. Once this RFC reaches an outcome, we'll update the status field in this markdown file and merge this PR to document that.
=> Extensibility RFC

docs/ide.md
These are the main components that I use.
=> Add IDE instructions for Vim

stablehlo/dialect/Base.td
=> Disallow unranked complex tensors

docs/spec.md
The PR provides clarification on the execution semantics of the StableHLO quantized operations.
@loganchien
@paulinesho
@doyeonkim0
@dominicsymes
@cbasile-g
Looking forward to your feedback.
=> Execution semantics of Stablehlo quantized operations

stablehlo/dialect/TypeInference.cpp
=> Remove `RankedTensorType` verification check for `TriangularSolveOp`

stablehlo/dialect/TypeInference.cpp
=> Remove `RankedTensorType` verification check for `CholeskyOp`

stablehlo/dialect/StablehloOps.td
This includes the regioned ops case, if and while.
=> Mark recursively speculatable ops as such

stablehlo/dialect/StablehloOps.cpp, stablehlo/transforms/StablehloRefineShapes.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
This was missed in https://github.com/openxla/stablehlo/pull/2180
=> Fix deprecated uses of template dyn_cast/isa

stablehlo/dialect/StablehloOps.td, stablehlo/tests/chlo/chlo_legalize_to_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
Hit some unexpected blockers when trying to export properties changes to openxla/xla. I'm going to temporarily revert this change (keeping all the properties related infra changes, just reverting this portion and CHECK tests).
=> Revert properties change temporarily

docs/spec.md
This is for (P3) of the dynamism RFC: https://github.com/openxla/stablehlo/blob/main/rfcs/20230704-dynamism-101.md#p3
The RFC says to update the "Notation" section of the spec, but I think it makes more sense to have a separate section for dynamism, which I plan to expand in future PRs. For now, I am adding some explanations about constraint verification and undefined behavior.
(P3) also requires auditing existing verifiers and shape functions to make sure that we allow dynamic dimension sizes everywhere. I am doing this as part of writing tests for (P2).
=> Explain how constraints interact with dynamism

rfcs/20230704-dynamism-101.md
On the whole, it seems like this change has low returns and high costs.
See https://groups.google.com/a/openxla.org/g/openxla-discuss/c/HJRvFBum65k/m/Xzld0wJaAAAJ for discussion.
=> Remove shape operand change from Dynamism RFC

docs/spec.md
This satisfies P4 of the Dynamism RFC: https://github.com/openxla/stablehlo/blob/main/rfcs/20230704-dynamism-101.md#p4
=> Document that dimension sizes can be dynamic

stablehlo/dialect/StablehloOps.td
This was missed in https://github.com/openxla/stablehlo/pull/2199
=> Replace Pure on Transpose with ConditionallySpeculatable and NoMemoryEffect

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Relevant constraints from the spec:
```
(C9) dim(lhs, lhs_batching_dimensions...) = dim(rhs, rhs_batching_dimensions...).
(C10) dim(lhs, lhs_contracting_dimensions...) = dim(rhs, rhs_contracting_dimensions...).
(C12) shape(result) = dim(lhs, lhs_batching_dimensions) + dim(lhs, lhs_result_dimensions) + dim(rhs, rhs_result_dimensions).
```
=> Implement ConditionallySpeculatable for DotGeneral

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
This op isn't specced yet but the speculation logic is relatively straightforward and follows from the tablegen/type inference/XLA documentation: https://openxla.org/xla/operation_semantics#setdimensionsize.
=> Implement ConditionallySpeculatable for SetDimensionSize

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
The spec says (C11): shape(operand) = shape(result).
=> Implement ConditionallySpeculatable for SelectAndScatter

stablehlo/reference/Ops.cpp
This is part of ongoing efforts to sync reference interpreter closer to the spec #1049
=> Rename variables to simplify refactoring

docs/_toc.yaml, docs/tutorials/savedmodel-embed.ipynb
[Preview](https://github.com/GleasonK/stablehlo/blob/d8894397b73d19ee93b9509024c02f705b631718/docs/tutorials/savedmodel-embed.ipynb)
Add a tutorial to demonstrate the new StableHLO to SavedModel APIs.
=> Add StableHLO to SavedModel Tutorial

stablehlo/dialect/StablehloOps.td
Missing the common declarations.
=> Fix extraDeclarations for AllGather

rfcs/20230623-compatibility.md
This PR does not contain an actual RFC - it's merely tracking a discussion on openxla-discuss: https://groups.google.com/a/openxla.org/g/openxla-discuss/c/rfd30zKR9uU. Once this RFC reaches an outcome, we'll update the status field in this markdown file and merge this PR to document that.
Posting PR on behalf of @zichuan-wei and @nutsiepully who drove this RFC on OpenXLA Discuss.
=> [RFC] Increase StableHLO Compatibility Guarantees

docs/spec.md
Updates spec for convolution to adhere to 80-char limit and formatting table properly.
=> Update table formatting and fix typos

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/tests/interpret/dynamic_gather.mlir, stablehlo/tests/ops_stablehlo.mlir
fixes https://github.com/openxla/stablehlo/issues/2290
=> Spec dynamic_gather

docs/spec.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
Thanks for taking the time to review the code!
FYI:
* I didn't quite understand this comment: https://github.com/openxla/stablehlo/pull/2306#discussion_r1597278405
* I didn't implement this suggestion (I think the existing code is correct): https://github.com/openxla/stablehlo/pull/2306#discussion_r1597281592
=> Address post-submit comments on #2306

stablehlo/dialect/VhloDialect.td
Thanks @mlevesquedion for the catch!
=> Add vhlo version log for v0.20.0

docs/spec.md, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/dialect/VhloOps.td, stablehlo/reference/Ops.cpp, stablehlo/tests/interpret/dynamic_conv.mlir, stablehlo/tests/verify_dynamic_conv.mlir, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloRefineShapes.cpp
Changes:
- `d_padding --> padding`
- `HLO_2DIntTensor:$d_padding --> HLO_Static2DIntTensor:$padding`
And cleanup for the two changes.
=> Make dynamic conv operand require static dim sizes, fix padding name

build_tools/github_actions/ci_build_cmake_code_coverage.sh, build_tools/github_actions/lint_check_license.sh, build_tools/github_actions/lint_clang_format.sh, build_tools/github_actions/lint_llvm_commit.sh, build_tools/github_actions/lint_whitespace_checks.sh
I implemented this in https://github.com/openxla/stablehlo/pull/2310 for a new script and I think it is good to apply this pattern to other scripts as well.
=> Exit after printing usage

stablehlo/api/PortableApi.h
PR was not ready to be submitted: https://github.com/openxla/stablehlo/pull/2366
=> Revert API bump

docs/spec.md, stablehlo/tests/interpret/all_to_all.mlir, stablehlo/tests/ops_stablehlo.mlir
This was pointed out by Yuyou on the StableHLO Discord: https://discord.com/channels/999073994483433573/999074539138990131/1246199149905449060
=> Tweak spec for special case when split_dim = concat_dim in all_to_all

rfcs/20240620-int2.md, rfcs/20240720-int2.md
To be shared to OpenXLA Discuss shortly.
=> [RFC] Add support for int2 in StableHLO

BUILD.bazel, stablehlo/integrations/c/CMakeLists.txt, stablehlo/integrations/c/StablehloPasses.cpp, stablehlo/integrations/c/StablehloPasses.h, stablehlo/integrations/python/CMakeLists.txt, stablehlo/integrations/python/StablehloModule.cpp, stablehlo/integrations/python/tests/stablehlo.py
Implements python bindings to register stablehlo specific passes.
=> Python binding for stablehlo.register_passes

docs/spec.md, stablehlo/dialect/Base.cpp, stablehlo/tests/ops_stablehlo_quantized.mlir
The verification labels used in code comments is out of place for some quantization relation constraints. Fixing those.
=> Fix quant verification labels

docs/spec.md, stablehlo/dialect/StablehloOps.td
as per https://github.com/openxla/stablehlo/blob/main/docs/reference_checklist.md#after-implementing-the-op.
=> Collectives Ops : Match example from the StableHLO op description comment with example from the spec

stablehlo/transforms/PassUtils.cpp, stablehlo/transforms/PassUtils.h, stablehlo/transforms/StablehloLegalizeQDQToQuantizedOp.cpp, stablehlo/transforms/StablehloLegalizeQuantizedOpToQDQ.cpp
=> Clean-up duplicate functions from pass dir

stablehlo/conversions/linalg/tests/pointwise.mlir, stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp
For elementwise operations, infer splat constant operands to avoid creating corresponding operands in the converted linalg op. Moreover, to facilitate this, the rewrite patterns `PointwiseToLinalgMapConverter` and `PointwiseToLinalgConverter` have been refactored to reuse common logic.
=> [legalize-linalg] Simple constant propagation for elementwise operands

stablehlo/tests/transforms/stablehlo_refine_shapes.mlir
cc @bartchr808 for pointing out this test gap
=> Add refinement test for if/case

docs/awesome.md
Happy to iterate on the specific phrasing, suggestions welcome.
I wonder if some reorganization would help too, since IREE could fit into either the "PJRT Plugins" or "Edge Compilation" sections.
=> Add IREE project link to awesome.md.

stablehlo/reference/Tensor.cpp, stablehlo/tests/interpret/printing.mlir, stablehlo/tools/StablehloTranslateMain.cpp
Found that the enzyme project was doing something like this, but didn't support complex numbers (our method does). Making this function the best of both worlds then will update enzyme.
=> Use reference to tensor data when converting to dense elements attr

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp
StableHLO port of MHLO change https://github.com/openxla/xla/commit/cc4fbd8dd81274a9bbed8c34309944c30f5678f4
=> Preserve unregistered attrs in while op simplification

.github/workflows/buildAndTestBazel.yml, stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp, stablehlo/transforms/optimization/StablehloAggressiveSimplificationPatterns.td
This improves stack traces as well as general code readability.
=> Give the StableHLO Aggressive Simp. patterns names

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/optimization/StablehloAggressiveSimplificationPatterns.td
=> Add a pattern for folding no-op Pad ops.

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir
In a certain corner case, we don't simplify already-dead `case` ops as much as we could. This change adds a (currently disabled) test for that case as well as a TODO reminding us to address it. It's a fairly insignificant optimization oppurtunity, but it's probably worth addressing in future.
=> Add a TODO pertaining to CaseOp folding

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
Add float support to several folder patterns.
=> Add more thorough support for float folding.

stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
The case-op folder pattern currently supports only int and float types (and tensors thereof). We plan to extend this in future, but for now, fail to match if the op's return type is unsupported.
=> Don't try to fold case ops with unsupported types
