.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Adding some more community friendly issue templates. I believe much of the early work will be completed using blank templates for tasks, but as users begin to use this repo, a bug_report template will come in handy. Also a link to our discord for users encountering issues is helpful too.
Based on IREE templates:
https://github.com/iree-org/iree/issues/new/choose
https://github.com/iree-org/iree/tree/main/.github/ISSUE_TEMPLATE
=> Add issue templates. Based on IREE templates.

docs/spec_draft.md
Here is the skeleton of the StableHLO specification: Presented as a draft to signify that this is a preliminary version of the specification and will follow additions in future w.r.t different ops.
=> Skeleton of the StableHLO spec

CMakeLists.txt, tests/lit.site.cfg.py.in
This is similar to how things are done in Clang: http://google3/third_party/llvm/llvm-project/clang/CMakeLists.txt;l=3-13;rcl=469417476.
Thank you, Mehdi, for the tip!
Backported from https://github.com/tensorflow/mlir-hlo/commit/32be07f12c82144965fd90671ca7c742e5c5f3f0
=> Allows StableHLO to be built as part of other CMake projects

CMakeLists.txt, build_tools/README.md, integrations/CMakeLists.txt, integrations/c/CMakeLists.txt, integrations/c/ChloAttributes.cpp, integrations/c/ChloAttributes.h, integrations/c/ChloDialect.cpp, integrations/c/ChloDialect.h, integrations/c/StablehloAttributes.cpp, integrations/c/StablehloAttributes.h, integrations/c/StablehloDialect.cpp, integrations/c/StablehloDialect.h, integrations/c/StablehloTypes.cpp, integrations/c/StablehloTypes.h, integrations/python/CMakeLists.txt, integrations/python/ChloModule.cpp, integrations/python/StablehloModule.cpp, integrations/python/mlir/dialects/ChloOps.td, integrations/python/mlir/dialects/StablehloOps.td, integrations/python/mlir/dialects/chlo.py, integrations/python/mlir/dialects/stablehlo.py, integrations/python/tests/CMakeLists.txt, integrations/python/tests/smoketest.py
In this pull request, I took the existing Python bindings for MLIR-HLO
and mostly copy/pasted them into the StableHLO repository.
One change from MLIR-HLO is that we have two separate bindings for
CHLO and StableHLO in the StableHLO repository. This follows the recent
trend in both repositories where we severed the dependency from CHLO
to MHLO.
=> Add Python bindings for CHLO/StableHLO

docs/spec_draft.md
fixes https://github.com/openxla/stablehlo/issues/53
Has the following changes:
- A few spec types:
-  Fix the header of the table names from "Operand Names" to "Name" and "Result Name" to "Name". The redundant prefixes can be derived from the section name.
- not consider tensor as keyword. 
- Addition of the spec of the Bitwise ops.
=> Add specifications for and, or, xor, not operators

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/print_types_invalid.mlir
Pretty print for SelectOp based on vector display of `arith.select`: https://mlir.llvm.org/docs/Dialects/ArithmeticOps/#arithselect-mlirarithselectop
```
// Element-wise vector selection in arith:
%vx = arith.select %vcond, %vtrue, %vfalse : vector<42xi1>, vector<42xf32>
// StableHLO display:
%0 = stablehlo.select %arg0, %arg1, %arg1 : tensor<2x3xi1>, tensor<2x3xi32>
```
Note that if branch types do not match exactly, `functional-type` is used:
```
%1 = stablehlo.select %arg0, %arg2, %arg3 : (tensor<2x3xi1>, tensor<2x?xi32>, tensor<?x2xi32>) -> tensor<2x?xi32>
```
Now that `SameOperandsAndResultType` is merged into main, we can use it in other ops that _may_ have the same operands and result types like ClampOp, or ops that _must_ have matching types like AfterAllOp:
```
%0 = …
```
=> Implement pretty printing for SelectOp, ClampOp, AfterAllOp types. Clean up type prints.

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/verify_reduce.mlir
The new `ReduceOp::inferReturnTypeComponents()` replaces the old `ReduceOp::verify()` with all the checking logic.
Note that a unit test is removed: it had a `llvm.add` inside its region, and intended to return a scale from its region and catch the error in `ReduceOp::verify()`. Now when we replace verifier with infer function, there will be two errors:
1. `'llvm.add' op operand #0 must be integer or LLVM dialect-compatible vector of integer, but got 'f32'`: can be fixed by change `f32` -> `i32`
2. In the last line of region, stablehlo.return supports return tensor only, instead of scalar: No way to fix this.
The HEAD code tolerated these errors because the `ReduceOp::verify()` fails first. Now decide to remove this unit test which is a case that will not happen.
=> Add type inference for stablehlo.reduce

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
This change adds type inference method for `stablehlo.batch_norm_grad`,  `stablehlo.batch_norm_training` and `stablehlo.batch_norm_inference`, and revisit their `verify()`:
1. Existing comments in `verify()` are verbose and hard to read and maintain: ODS provides clear constrains for those many operands/atts/result and much more readable than the long comments in nature language. Besides, the existing comments also miss some points like element type match for some items. So they are removed, instead, this change states clearly that `verify()`only contains checks beyond ODS.
2. These ops shares quite similar logic, so refactor by reusing them.
3. XLA semantics is very long because it includes everything that the ODS of StableHLO already covers. The missing pieces are covered by `verify()`.
=> Add type inference for stablehlo.batch_norm_* ops.

docs/spec_draft.md
The PR adds a tables indexing to all the documented ops and back to the index. This improves navigation through the doc.
=> spec: Add an index of documented ops

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
So far, additional context in our tickets has always been empty.
Let's remove it for the time being.
=> Remove "Additional context" from bug and FR templates

.github/ISSUE_TEMPLATE/config.yml
At the GitHub organization level, we've restructured discussions, so
that they all end up at https://github.com/orgs/openxla/discussions,
similarly to how we have the OpenXLA Discord server and
multiple channels within that server.
=> Update the "Discussions" link

docs/spec_draft.md
The semantics of ops on FP element types is currently specified slightly inconsistently. The idea of this PR is to have a consistent wording (if possible).
=> Clarify the floating point semantics of add/max/min

docs/spec_draft.md
closes https://github.com/openxla/stablehlo/issues/71
Also, fixes some typos in the specification docs.
=> spec-draft: floor/ceil

docs/spec_draft.md
closes https://github.com/openxla/stablehlo/issues/73
Also, fixes some typos in the specification docs.
=> spec-draft: negate/abs

docs/spec_draft.md
- All constraints can be referred to now (this will be useful in the future when writing verifiers for more complicated ops).
- Some constraints are merged into one.
- "Supported shapes: all static shapes" is redundant at this point, because the spec only defines static shapes.
=> Refactor constraints

README.md, docs/spec_draft.md
Doesn't run if all files in PR are `*.md` or `docs/...`. This will prevent B&T from running for spec updates.
Closes #110
=> Don't run Build and Test Action if only doc or readme changes.

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/verify_conv.mlir, stablehlo/tests/verify_reduce_window.mlir, stablehlo/tests/verify_select_and_scatter.mlir
The new `ReduceWindowOp::inferReturnTypeComponents()` replaces the old `ReduceWindowOp::verify()` with all the checking logic. And expect to cover all XLA checks as well.
And invalid test with `llvm.add` is removed in the same reason as the description of [the PR of "Type inference of ReduceOp"](https://github.com/openxla/stablehlo/pull/50). Please see the reason there.
`ReduceWindowOp` has similar but not same code as `ReduceOp` which is not ideal. So align them to be same in P1~P2 checks.
To address the legacy TODOs, `convertDenseIntAttr` add check for 1-D tensor, and change all caller respectively. Those ops like `SelectAndScatterOp` will be fully addressed in later PRs recently.
=> Add type inference for stablehlo.reduce_window

.github/actions/setup-build/action.yml, .github/workflows/buildAndTest.yml, build_tools/github_actions/ci_build_stablehlo_api.sh, build_tools/github_actions/ci_build_stablehlo_python_api.sh
- Added build script for Python API `ci_build_stablehlo_api.sh`
- Added a github action to build and check Python API.
- Added to `buildAndTest.yaml`. 
- Modified `setup-build` to also install required python libraries for mlir bindings.
Timing (first time cost any time we bump llvm version):
- First time cost: ~1.5hr 
- With ccache, following builds: ~3min
_Open question:_
I have a feeling a lot of common LLVM machinery is being built twice. Is there a way to combine API bindings build with the LLVM build? Do we want to do this?
Closes #62.
=> Add Python API Testing to GitHub Actions

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
The verifications are aligned with XLA semantics with only one difference: XLA [shape_inference.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/shape_inference.cc#L1131) seems to allow scalar in inputs, but there isn't any test for it in XLA [shape_inference_test.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/shape_inference_test.cc#L968). So no change in StableHLO: still only support tensor instead of scalars. 
Add a positive test and move all positive cases before negative ones.
Add support when 1) all inputs are unranked, or 2) some are unranked.
=> Add type inference for stablehlo.map.

stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/StablehloOps.cpp
Raw has been deprecated and will be removed soon. The migration for CHLO/StableHLO has started in MLIR-HLO, but the recent internal infrastructure changes in tensorflow/mlir-hlo@3227ee1 have rolled it back. This progress needs to be restored. Closes #129
=> Migrate away from kEmitAccessorPrefix_Raw

stablehlo/dialect/CMakeLists.txt
Without this change, users of dialect headers will have to remember to add these targets to their dependencies, which can be easily forgotten and can lead to hard to reproduce CMake build errors. A similar issue in the MLIR-HLO repository only showed with `ninja -j1`.
=> Add TableGen targets to mlir-headers

stablehlo/tests/lit.cfg.py, stablehlo/tests/lit.site.cfg.py.in
This is going away (or has already gone away) in MLIR upstream.
Context: https://reviews.llvm.org/D133270.
=> Remove mlir_runner_utils_dir replacement from lit.cfg.py

README.md, build_tools/README.md
Wrap at 80 characters, use headers correctly (no more than one level-one header in one file).
=> Format markdown files consistently with MLIR-HLO

docs/interpreter.md
Added a missing link to spec draft while maintaining 80 lines wrap.
=> updated a link to spec-draft in interpreter.md

docs/status.md
* Fix typos: "FooOP" => "FooOp".
* Left align the column with op names. I think the table is easier to read this way, but please let me know if you disagree!
=> Further tweaking of status.md

stablehlo/dialect/ChloBytecode.cpp, stablehlo/dialect/StablehloBytecode.cpp
Use `LLVM_PRETTY_FUNCTION` instead of `__PRETTY_FUNCTION__` since it is portable. IREE had reported build errors on windows using `__PRETTY_FUNCTION__` for this reason.
Tested debug trace locally, and verified that all uses were changed with the following:
```bash
./openxla/stablehlo$ grep -rnw . -e ".*PRETTY.*"
./stablehlo/dialect/ChloBytecode.cpp:43:                      << _EXTRACT_AFTER(LLVM_PRETTY_FUNCTION, func) << '\n')
./stablehlo/dialect/ChloBytecode.cpp:50:                                       << LLVM_PRETTY_FUNCTION << '\n')
./stablehlo/dialect/StablehloBytecode.cpp:42:                      << _EXTRACT_AFTER(LLVM_PRETTY_FUNCTION, func) << '\n')
./stablehlo/dialect/StablehloBytecode.cpp:49:      llvm::errs() << "***Not Implemented: " << LLVM_PRETTY_FUNCTION << '\n')
```
Closes …
=> Replace uses of __PRETTY_FUNCTION__ with LLVM_PRETTY_FUNCTION

stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloOps.td
https://github.com/openxla/stablehlo/commit/3511b6b2810d2f183ecf2e10c2441cc719874838 was supposed to do this, but I forgot to update TableGen files.
=> Switch CHLO and StableHLO to kEmitAccessorPrefix_Both

CMakeLists.txt, stablehlo/reference/Tensor.h
Fixes a build warning with `Tensor.h`:
```
In file included from /usr/local/google/home/gleasonk/Coding/openxla/stablehlo/stablehlo/reference/Tensor.cpp:16:
/usr/local/google/home/gleasonk/Coding/openxla/stablehlo/stablehlo/reference/Tensor.h:44:11: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
Buffer &operator=(Buffer &&other) = default;
^
/usr/local/google/home/gleasonk/Coding/openxla/stablehlo/stablehlo/reference/Tensor.h:33:16: note: move assignment operator of 'Buffer' is implicitly deleted because base class 'llvm::RefCountedBase<Buffer>' has a deleted move assignment operator
class Buffer : public llvm::RefCountedBase<Buffer> {
^
/usr/local/google/home/gleasonk/Coding/llvm-project/llvm/include/llvm/ADT/IntrusiveRefC …
```
=> Build with all warnings as errors.

docs/spec_draft.md
Addressing the comments missed in https://github.com/openxla/stablehlo/pull/156
=> fix typos in  AddOp spec

stablehlo/tests/TestUtils.cpp, stablehlo/tests/TestUtils.td
Figured it out - the constructor gets auto-generated when an explicit constructor field is not specified in ODS.
=> Use auto-generated pass create functions

stablehlo/tests/interpret_add.mlir, stablehlo/tests/interpret_constant.mlir
The current tests do not address all special values for floats.
The list of special values are:
* +/- 0
* +/- inf
* +/- NaN
* +/- Subnormal
However, the spec does not differentiate signedness of the NaN, so only the +NaN is tested. An investigation will be done in the near future to determine whether the tests include all special cases which are addressed in the spec for all ops in question.
=> Add additional special test cases for interpret_add.mlir and interpret_constant.mlir

docs/status.md
The new values in Markdown table of all 114 ops are copied from StableHLO audit sheets with local handy script and the rule to map the old value in sheets to the new value in Markdown table is:
``` 
convert_value_for_md = {
'Yes (Declarative)': 'yes(match-xla)',
'Yes (Imperative)': 'yes(match-xla)',
'Yes (need revisit)': 'yes(need-revisit)',
'TODO': 'no',
'Yes (revisit)': 'yes(need-revisit)',
'No (Infeasible)': 'no-plan',
'WIP': 'wip',
}
```
The values of `Type Inference` column is clear and fully up to date. The `Verifier` column actually means both ODS and `verify()`. As `verify()` are removed for a lot of ops, the value of them are still set to `yes(match-xla)`. 
If an op's type inference is done or revisited in the future: its value of `Verify` column will also be revisited and …
=> Populate progress of verifier and type inference.

stablehlo/tests/ops_chlo_roundtrip.mlir
There is currently no bytecode test for `compare_type` in CHLO. See [coverage report](https://htmlpreview.github.io/?https://raw.githubusercontent.com/GleasonK/stablehlo/ccov/reports/ccov_2022_09_21_14-51-15/stablehlo/dialect/ChloBytecode.cpp.gcov.html).
Added tests that uses all attributes of `chlo.broadcast_compare`.
=> Add bytecode test for compare_type attr.

.clang-format, .github/workflows/lint.yml, build_tools/github_actions/lint_clang_format.sh
Two changes in this PR:
1) Refactor the lint action to be a locally runnable bash script. This should give _more_ predictable results in terms of addressing CI failures.
2) Update `.clang-format` to use Google style in the short term. More on this rationale below.
Background on all this is that my editor formatted a large chunk of a file which caused the lint action to fail remotely, and took me quite some time to roll back the individual formatting changes, since google styling appears to prefer the most common spacing of `Type* var` vs `Type *var` in a file as the proper formatting.
This change will allow local qualification / fixing, as well as provide a stop-gap on editor formatting issues while #15 is discussed. While I agree that we should resolve #15, I think more discussion is …
=> Refactor the lint action into a build script, temporarily update .clang-format

docs/spec_draft.md
fixes #36 
The indent is to differentiate the added link to the following "Back to Ops" link.
=> adding links to elaborative testing

docs/spec_draft.md
When reviewing #170, I was looking at
`%result = stablehlo.reshape %operand : tensor<3x2xi32>` which was used as an example of reshape, and I realized that it might be pretty confusing to readers because it doesn't say anything about the tensor which is being reshaped.
First I thought to propose using whatever syntax we're currently using in StableHLO, i.e `... : (tensor<2x3xi32> -> tensor<3x2xi32>)`, but then I realized that we shouldn't expect spec readers to know implementation details of the StableHLO dialect, which can also change over time.
Given that, I'd like to propose that we consistently use MLIR generic syntax in examples, and additionally drop the informal mnemonic + signature notation used to introduce ops.
Finally, I'd also like to propose that we align type names in the …
=> Refactor op syntax in the spec draft

docs/spec_draft.md
Consistently left-aligns prose, removes double newlines.
=> Minor fixes to the formatting of the spec draft

stablehlo/reference/Interpreter.h, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.h
Add missing includes, fully qualify llvm::ArrayRef, llvm::SmallVector and llvm::StringRef.
=> Fix up headers in the interpreter

docs/interpreter.md, stablehlo/reference/CMakeLists.txt, stablehlo/reference/Element.cpp, stablehlo/reference/Index.cpp, stablehlo/reference/Index.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h
Tensor class currently supports APIs like `Tensor::get(int64_t index)` and `Tensor::set(int64t index, const Element &e)` which provides linearized access to the underlying storage, that is, the `index` points directly to the underlying storage byte array. This kind of "raw" indexing on tensor was done because, that way, it was simple to bootstrap the interpreter,  and secondly, it works pretty well for the element-wise operations. We understood that with more complex ops these APIs might need to be revised, which is what this PR is about.
Instead of using the raw indexing, we can use a more intuitive logical multi-dimensional indices based on the shape of the tensor. Internally we can use dimension [strides](https://en.wikipedia.org/wiki/Stride_of_an_array) to map the muiti-dimensional …
=> Use multi-dimensional indices to access tensor elements

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
Currently the build spews many warnings of the form:
```
[14/42] Building StablehloOps.h.inc...
/usr/local/google/home/burmako/stablehlo/stablehlo/dialect/StablehloOps.td:981:1: note: Skipping generation of prefixed accessor `getOperands` as it overlaps with default one; generating raw form (`operands`) still
def StableHLO_OutfeedOp : StableHLO_Op<"outfeed", []> {
^
```
This is because we are switching from raw accessors `$a --> a()` to prefixed accessors `$a --> getA()`. This causes a conflict when the variable name `$operands` is used since `getOperands()` is an existing method on the `Operation` class.
Solution is to rename all instances of `$operands --> $inputs`, and all accessors `operands() --> getInputs()`.
Closes #195
=> Fix build warning spew. Change $operands->$inputs.

docs/spec_draft.md
This is surfaced in in PR https://github.com/openxla/stablehlo/pull/214 at [here](https://github.com/openxla/stablehlo/pull/214#discussion_r983038960).
=> Fix a spec bug for negate and abs op

docs/interpreter.md, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/tests/interpret_add.mlir, stablehlo/tests/interpret_constant.mlir, stablehlo/tests/interpret_cosine.mlir, stablehlo/tests/interpret_sine.mlir, stablehlo/tests/interpret_subtract.mlir, stablehlo/tests/interpret_tanh.mlir
The proposal here is to use a discriminated union of APInt and APFloat as the storage mechanism for Element objects.
fixes https://github.com/openxla/stablehlo/issues/79
=> Revisit use of mlir::Attribute storage of Element Class

stablehlo/reference/Index.cpp, stablehlo/reference/Index.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Tensor.cpp, stablehlo/tests/interpret_add.mlir
Ideally, we are supposed to use valid indices from the index space of a Tensor to access individual elements. An invalid index might lead of OOB access. While testing the interpreter we found that the eval function of cosine op is still using the linearized index to access the tensor elements. 
```
Tensor eval(CosineOp op, const Tensor &operand) {
  Tensor result(op.getType());
  for (auto i = 0; i < operand.getNumElements(); ++i) {
    result.set(i, cosine(operand.get(i)));
  }
  return result;
}
``` 
While calling the `Tensor::get(rrayRef<int64_t>)`  API, these linear indices are implicitly converted to an `ArrayRef<int64_t>` of size 1. For a tensor with >= 1 rank, these are illegal indices and might cause OOB based on the shape and choice of index. 
We realized that it is  left over …
=> Enforce compatible indices and shape while indexing into Tensor

stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Tensor.cpp
* Inlines various errors directly into report_fatal_error (there doesn't seem to be a use case for having a temporary variable which is then immediately moved).
* Uses SmallVector in permute (Sandeep, you were right - the actual type is such a mouthful!).
=> Assorted cleanup

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
Add type inference for `stablehlo.dot_general` and fix trailing spaces
Note: a test for element type mismatch does not exist due to quantization for dot, hence why `SameOperandsAndResultElementType` interface is not present. 
closes #152
=> Add type inference for stablehlo.dot_general

docs/spec_draft.md
* Rename "max" and "min" in the TOC to "maximum" and "minimum" to follow the StableHLO mnemonics.
* Rename "exp" in the TOC and in the actual spec to follow the StableHLO mnemonics.
* Reorder `sqrt` and `subtract` to keep alphabetical order.
* Also, remove the deprecated way of specifying op syntax.
=> Consistently use StableHLO mnemonics in the spec

docs/spec_draft.md
"is equal to" is replaced with "=".
=> Simplify the language in specs of reshape and transpose

docs/status.md
Now that we've switched from op C++ names to op mnemonics, we need to reshuffle the table a little bit.
=> Reorder status.md alphabetically

docs/spec_draft.md
As Gunhyun pointed out in a nearby PR, we should do that until #22 is fixed.
=> Stop using signed integer types in MLIR examples

stablehlo/tests/interpret_cosine.mlir, stablehlo/tests/interpret_sine.mlir, stablehlo/tests/interpret_tanh.mlir
The current mode of testing the implementation is to use LLVM's lit-test framework to syntactically match the output of the operation with a (user provided) golden output. We do have some ops (like sine, cosine, tanh) which might produce results with implementation defined precision, failing the lit checks. 
To avoid that this PR allows the lit checks to match the accuracy up to 12 places after the decimal point. The number 12 is chosen   arbitrary but provides a descent approximation of the checked values.
=> Fix lit checks with ops having implementation defined precision

stablehlo/dialect/CMakeLists.txt, stablehlo/tools/CMakeLists.txt
This patch reorders the libraries linked into the stablehlo-interpreter
target, since otherwise, the CMake build fails with the error:
StablehloOps.cpp: undefined reference to `mlir::DataLayout::closest`
This patch also adds `target_include_directories()` for the
`StablehloBase` and `StablehloBroadcastUtils` so that path to the
Stablehlo header files is added to the include path of downstream
targets.
=> Fix CMake build

docs/spec_checklist.md
The current version of the checklist recommends to update `description` only if the implementation of the op conforms to the spec.
When I wrote that recommendation, it was deliberate. I thought that the process could be: 1) if the implementation doesn't conform don't update the description, 2) fix the tickets, 3) update the description.
But now I think that this simply introduces an extra step into the process (step number 3) without a good reason. If there's a spec for the op, it's already useful to make it part of documentation. And if there are some bugs in the implementation, that's fine as long as we have tickets for them.
=> Unconditionally update `description` in op's ODS

docs/status.md, stablehlo/dialect/StablehloOps.td
Updates the ODS description to include:
* One sentence description from the spec
* Link to the spec
* Pretty print syntax
The changes in `status.md` for Verification and Type Inference columns are also now in sync with the spec.
=> Update ODS links to reference StableHLO spec

stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/print_stablehlo.mlir
This PR has two patches that close #236 and #237.
---
cc: @burmako These are two very small patches, but in general, I am not sure if you prefer each issue to be addressed in a separate commit.  Apologies if I misjudged!
=> Add `DefaultValuedOptionalAttr` and `use_global_device_ids`

docs/status.md
As established in #250, #262 and #263, verifiers for these ops are actually correct. It's the spec which is incorrect.
=> Flip Verification status of abs, add, minimum and maximum

docs/spec_draft.md, docs/status.md
Cleans up formatting in `spec_draft.md` and `status.md`. Fixed typo `max` in `stablehlo.min` semantics.
=> Clean up format and fix typos

docs/interpreter.md, stablehlo/reference/Ops.cpp
This better matches the spec, where our formal notation always says `result[...] = operand[...]`. The only exception so far is transpose where the spec derives result index from operand index.
=> Anchor evals to result's index space iterator

stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td
Follows up on #203 to complete the migration of the StableHLO repository to kEmitAccessorPrefix_Prefixed.
=> Update CHLO to use prefixed accessors

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/infer_stablehlo.mlir
This makes it possible to propagate the input bounds while creating the Transpose op.
=> Handle bounds in the Transpose op shape function

docs/spec_draft.md, docs/status.md
Partially solves https://github.com/openxla/stablehlo/issues/262 w.r.t the ops add, maximum, and minimum.
That way these ops will be aligned with the ODS and the HLO semantics.
=> update spec of add, maximum, and minimum w.r.t supporting bool type

docs/spec_draft.md
I remembered that in the spec we already define "tensor constant", so let's use that definition.
=> Rename "array of type si64" to "tensor constant of type si64"

docs/spec_draft.md
This allows us to avoid thinking about whether something is an operand, an attribute or a region. See #310 for an inspiration.
=> Rename Operands/Results to Inputs/Outputs

stablehlo/dialect/StablehloOps.td
These parts should be part of https://github.com/openxla/stablehlo/pull/145 but somehow did not get deleted. This PR fix this issue.
IfOp, CaseOp, ConcatenateOp, RngOo.
The corresponding MHLO parts are well maintained.
=> Delete redundant calls of isCompatibleReturnTypes

stablehlo/dialect/StablehloOps.td
As part of integrate from MHLO to StableHLO.
=> Consistent spacing between attributes types and names

docs/spec_draft.md
Instead of "`si64`", expand to "constant of type `si64`" to be in line with other places in the spec.
=> Tweak the description of ConcatenateOp::dimension

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
This PR purely move the code without change, I expect to add the bounds to the it directly in the shared file. @smit-hinsu 
Following PRs will move more ops for which we will add bounds soon, but more refactoring code needed, so let's keep this PR simple to review.
=> Move SliceOp to shared file before we add bounds to it

docs/spec_draft.md
Changes ConcatenateOp's Type description from `variadic number of tensors of any supported types` to `variadic number of tensors of any supported type` to clarify only one supported type is allowed for the variadic tensors.
=> Clarify wording for variadic types and fix format

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
For shape functions, the interface`inferReturnTypeComponents()` infers `SmallVectorImpl<ShapedTypeComponents>& inferredReturnShapes` while `inferReturnTypes()` inferes`SmallVectorImpl<Type>& inferredReturnShapes`.  However `ShapedTypeComponents` dose not fit for the Token case for the result type `HLO_TensorOrToken` for if/case/while ops. Thus, we need use the `Type` as inferred type: choose `inferReturnTypes()`.
Besides, these functions will be called by with MHLO, so this PR is expected to check in before shared with MHLO.
=> Change shape function interface for branch ops

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/StablehloOps.cpp
Created `stablehlo/dialect/AssemblyFormat.h` with shared code for pretty printing. This only depends on `StablehloBase` and upstream MLIR.
Skipping the move of print operations that rely on specific attribute types. Will reconsider these in a later PR. Custom printer machinery requires functions to have a certain signature, so there is a good change these will need to be templated.
`StablehloOps.cpp` has many `using mlir::hlo::print*` declarations. An alternative is to `using namespace mlir::hlo` in the file scope, but that is not super desirable and clang tidy complains.
=> Refactor pretty printing machinery to separate files (NFC)

stablehlo/dialect/Base.h
Switch from SmallVector to ArrayRef and save on llvm::to_vector.
=> Minor optimization for inferMostSpecificType

docs/spec_draft.md
The comparator must satisfy the same requirements as C++'s Compare concept, i.e. two elements `v1` and `v2` are considered to be equal by the comparator iff `comparator(v1, v2) = false && comparator(v2, v1) == false`. This precision is important to exclude comparators such as LE or GE, for which setting is_stable to true does not produce a stable sort.
=> Clarify the semantics of StableHLO's sort operation.

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
Add bounds support for `PadOp`
Why change the shape function interface from `inferReturnTypeComponents` to `inferReturnTypes`? Appending `inferredReturnShapes.emplace_back(..., encoding_attr)` inside `inferReturnTypeComponents` will trigger error in [upstream](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Interfaces/InferTypeOpInterface.cpp#L190)
```
assert(shapeAndType.getAttribute() == nullptr && "attribute not supported");
```
This PR follow the verification of in dim loop similar to https://github.com/openxla/stablehlo/pull/378/files.
Also add @smit-hinsu as reviewer.
=> Handle bounds in the PadOp shape function

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h
Move code comments for `printComplexOpType` to header file. Add description for `printSelectOpType`.
Noticed during MHLO integration work.
=> Add code comments for print functions (NFC)

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
fix https://github.com/openxla/stablehlo/issues/391
Please see the detailed link in the related bug.
=> Remove ReduceOp::build() to sync with MLIR-HLO

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/tests/print_types_invalid.mlir
The code `DenseI64ArrayAttr::parse(parser, Type{}).dyn_cast<DenseI64ArrayAttr>();` is problematic since if parsing fails, the null attribute will crash on `dyn_cast`.
Move the `dyn_cast` to after error handling. Add test case.
=> Fix error handling and add testing for printDenseI64Array

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir
=> Expose channel_id in CollectivePermuteOp

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
`ConcatenateOp` has variadic inputs, so `inferMostSpecificType` need to be used to infer multiple dims (size, bound) from multiple input tensors, which set the rules of how to infer the return bounds for binary ops like `AddOp`.
However, `ConcatenateOp` is more complicated:
1. For the dim that will be concatenated, we need a new set of different rules to infer the dimension sizes and bounds.
2. For the rest N-1 dimension, the existing rules used by binary ops can be re-used.
More details for (1) from the new code comment:
```
// Inference rules to concat dimensions with bounds (lhs/rhs are commutative):
//       Dim of lhs     Dim of rhs      Infer
//  c0:  X              Y               X+Y
//  c1:  X              ?               ?
//  c2:  X              ?, B            ?, X+B
//  c3: …
```
=> Handle bounds in the ConcatenateOp shape function

docs/spec_draft.md
"implementation-dependent" => "implementation-defined".
As we're making our language around implementation-defined and undefined behavior stricter, rewording this looked appropriate.
=> Fix typo in spec_draft.md

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/transform_stablehlo.mlir
This hasn't been discussed much, but as part of defining the
relationship between StableHLO and MHLO, it looks reasonable to avoid
doing transformations on StableHLO and leave that to MHLO.
This way, we don't have to duplicate stuff like constant folding,
canonicalization, etc etc.
Inlining is one of the transformations that's in a gray area because
this is something that we get for free from upstream, so I don't think
that the duplication argument applies here.
=> Allow inlining StableHLO ops

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/print_types_invalid.mlir
This is consistent with `func.call` printing, and relies entirely on upstream machinery. Using this printing is cleaner and more consistent, and if we eventually consider modifying what is permitted in CustomCallOp target names, this printing will not need to be updated.
```
%0 = stablehlo.custom_call @foo(%arg0) ...
%1 = stablehlo.custom_call @"foo-not-id"(%arg0) ...
```
This is a little messier for non-identifier target names, but there are _very_ few cases that target non-C or non-MLIR identifier names. The only ones I was able to find were in a single test file in mlir-hlo.
The implementation directly calls upstreams `AsmPrinter::printSymbolName`/`AsmParser::parseSymbolName`. These methods are able to handle identifier and non-identifier targets.
Closes #431
=> Prettyprint CustomCallOp target using SymbolRef printing

stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloOps.td
This is the default and the option will be removed by https://reviews.llvm.org/D136727
=> Remove explicit references to kEmitAccessors_Prefixed

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Updates ODS to use `HLO_FpOrComplexTensor` instead of `HLO_Tensor` for `operand`.
closes #357
=> Add spec for FftOp

docs/spec_checklist.md
It no longer exists and has been long replaced by the "Inputs" and "Outputs" sections.
=> Fix the reference to the "Operands" section in the spec checklist

stablehlo/dialect/CMakeLists.txt
Found it in an [onnx-mlir pr](https://github.com/onnx/onnx-mlir/pull/1829)
=> Fix the LINK_LIBS of StablehloTypeInference

.github/workflows/buildAndTest.yml
GitHub Actions is deprecating save-state and set-output commands, need to update to use new Environment Files:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I made a PR on my forked repo to test, and it had the following in the logs:
```
Run ./.github/actions/setup-build
with:
llvm-version: d4c61314420ca8794ad6d2588566c64109482505
env:
LLVM_PROJECT_DIR: llvm-project
LLVM_BUILD_DIR: llvm-build
STABLEHLO_BUILD_DIR: stablehlo-build
STABLEHLO_PYTHON_BUILD_DIR: stablehlo-python-build
```
This confirms that the new syntax is working. The `llvm-version` is set by the output of the previous command.
=> Use new github actions output environment files

docs/spec_checklist.md, docs/spec_draft.md, stablehlo/dialect/StablehloOps.td
In #439, we documented the conventions for examples in spec/ODS, and I went to check how closely the previous work on the spec follows these conventions.
I discovered quite a few divergencies, so I started going through the spec fixing things. This PR covers 10 out of the currently specced 43 ops.
=> (abs..constant) Align examples in spec/ODS with spec_checklist.md

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Update semantics of ReduceOp to align with MapOp semantics.
closes #437
=> Add spec for MapOp

CMakeLists.txt
Revert the bit of #457 that caused build failures in mlir-hlo.
Created #544 to build embedded properly with warnings as errors enabled.
=> Revert #457 embedded build change

stablehlo/tests/infer_chlo.mlir, stablehlo/tests/ops_chlo.mlir
Decided to take a little time to focus on code coverage. Specifically focused on `ChloOps.cpp`.
`ChloOps.cpp` coverage improvements:
- Before: [55% line, 39% func coverage](https://htmlpreview.github.io/?https://raw.githubusercontent.com/GleasonK/stablehlo/ccov/reports/ccov_2022_11_15_16-34-38/stablehlo/dialect/ChloOps.cpp.gcov.html)
- After: [91% line, 77% func coverage]( https://htmlpreview.github.io/?https://raw.githubusercontent.com/GleasonK/stablehlo/ccov-test/reports/ccov_2022_11_15_19-08-26/stablehlo/dialect/ChloOps.cpp.gcov.html)
This brings our entire repo code coverage from `84.6% -> 86.5%`. We have a goal of hitting `90%` in Q4.
=> Improve CHLO code coverage for verifiers, type inference, reify

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/print_stablehlo.mlir
- Migrate unknown dimension printing `printDimensionSizes`.
- Move `parseIntArray` to `AssemblyFormat.h` to be shared.
This unblocks work to make a few other attributes declarative. Also opens the door to make some printing infrastructure communal between MHLO/StableHLO. Will look into removing `parseDims` today.
=> Migrate MHLO changes for printing dimensions

docs/spec_checklist.md
For tickets like https://github.com/openxla/stablehlo/issues/369 which is applicable to many PRs and prevents the status of one or more implementations from being a `yes`, it would be useful to track all the Ops which needs to be tracked before closing this issue. Linking the ticket in the PR could be a solution and hence the proposal.
=> update spec checklist: Adding ticket link in PR

docs/spec_checklist.md, docs/spec_draft.md
This is really useful (see #565 for details).
Also remove the "Structure of an Op’s Specification" section of the spec since it has been superseded by the checklist a while ago.
=> Expand the checklist to include HloInstruction::CreateFromProto

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Updates the description of ceil and floor op to call out IEEE-754 operation names.
closes #475
=> Add spec for RoundOp

.github/workflows/buildAndTest.yml
Unless I'm missing something, these look like typos.
=> Fix typos in step names of GitHub workflows

docs/spec_draft.md
I merged #434 and only then realized that the explanation of why `bits` has implementation-defined behavior could've been updated to reflect the latest conversation on the pull request.
It's not just the floating-point representation is implementation-defined, it's also integer representation and boolean representation.
=> Slight rewording of the BitcastConvertOp spec

docs/spec_draft.md
I think that recent PRs with specs for collective ops (e.g. #503) would benefit from a more formal definition of parallel execution semantics of StableHLO programs.
That will provide additional clarity which is needed at the moment (see discussions in the PRs) and reduce the duplication between the specs of individual collective ops.
The description of execution semantics isn't yet as formal as I'd like, but it can already benefit specs for collective ops. I'll leave the rest to follow-up work within #484.
=> Add spec for parallel execution semantics

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Verification is set to `revisit` due to #557
Updates semantics of SliceOp to match DynamicSliceOp
closes #519
=> Add spec for DynamicSliceOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Verification is left `revisit` due to #554.
Type Inference is left `no` since no type inference exists currently and added issue #656.
Updates spec of ScatterOp to mirror this op.
closes #520
=> Add spec for DynamicUpdateSliceOp

docs/spec_draft.md
Added headers to the process_group paragraphs in parallel execution semantics, so they can be linked from other parts of the spec.
=> Add headers to parallel execution semantics

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir
fixes #462 
Address the followings:
1. Adds verification checks for AllGather w.r.t. https://github.com/openxla/stablehlo/issues/498
2. fixes https://github.com/openxla/stablehlo/issues/491
A few points
- Type Inference is marked `infeasible` as the return type of the op depends upon the [shard_count](https://github.com/tensorflow/tensorflow/blob/20c6943d3cd7e07da162f7778a0af5d3776274b4/tensorflow/compiler/xla/service/hlo_verifier.cc#L452) which [depends on the result type](https://github.com/tensorflow/tensorflow/blob/20c6943d3cd7e07da162f7778a0af5d3776274b4/tensorflow/compiler/xla/service/hlo_verifier.cc#L426). Note that the `shard_count` is a parameter in HLO spec, where as in MHLO it is [derived](https://github.com/tensorflow/tensorflow/blob/a1acd6a6466f58ed4197b7beaa2f3e0b6fcfc32a/ten …
=> Add spec for AllGatherOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Raised issue #643 to track which types are supported for the inputs/outputs.
Verification is set to `revisit` due to #486.
closes #414
=> Add spec for RngBitGeneratorOp

docs/spec_draft.md
Fixed the fact that size(`replica_groups`) is not always `num_replicas` and depends on the process group formation strategy.
Added an action item to #498 to verify these facts.
=> fix size constraint on replica_groups for AllGatherOp

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/integrations/python/tests/stablehlo.py, stablehlo/tests/TestUtils.cpp, stablehlo/tests/infer_chlo.mlir, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
Prepare for dynamic dim size to be changed from -1 to INTMIN.
This is a first step at removing the reliance on upstream `kDynamicSize`. There is more refactoring that can be done, but this change will at least make it so that some of our error messages will display `?` instead of the value, and our infer tests will continue to display `-1` regardless of what the underlying dynamic size is.
=> Change -1 to ? printing when possible

.github/workflows/lint.yml, build_tools/github_actions/lint_whitespace_checks.sh, docs/bytecode.md, docs/type_inference.md, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/print_types_invalid.mlir, stablehlo/tests/verify_conv.mlir
```
$ lint_whitespace_checks [flags]
-f  Auto-fix whitespace issues
```
Perform the following whitespace checks:
- No trailing whitespace (clang-format covers this for `h/cpp`, but not `md/yml/td/txt/mlir`)
- Files must end in EOL (many editors enforce this, but not clang-format/tidy)
Can auto-fix issues using the `-f` flag.
Example of failure message when I added whitespace and removed EOL from end of file:
https://github.com/GleasonK/stablehlo/actions/runs/3605629099/jobs/6076206738
=> Add CI lint for invalid whitespace in files. Fix existing issues.

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
fixes #525 
verification of infeed op is revisit based on https://github.com/openxla/stablehlo/issues/639
Note that for outfeed op we are using the  output name  as `results` based on the implicit name [introduced by the tablegen file](https://github.com/openxla/stablehlo/blob/dbf9964c6ce980e1976041700807bd94e6adf849/stablehlo/dialect/StablehloOps.td#L1030 ) even though it should be explicitly called out as `result` (singular). This will be addressed in https://github.com/openxla/stablehlo/issues/351#issuecomment-1326914173, item 4.
=> Add spec for InfeedOp and OutfeedOp

docs/spec_draft.md
The dimension sizes of the `update` tensor be equal to the dimension sizes of the `operand` tensor.
=> Fix typo in DynamicUpdateSliceOp's constraint

docs/spec_draft.md
They are related to each other, and "Streaming communication" even calls out similarities and differences with "P2P communication". I think it would be good to have them next to each other.
=> Move "Streaming communication" next to "P2P communication"

docs/status.md
Type Inference is set to "no", because "revisit" implies that there is an implementation that needs to be revisited.
=> Fix typos in AllGatherOp's status

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
Batching dimensions of lhs/rhs must match (same for contracting dimensions), but that check should account for dynamic dimension sizes.
=> Fix verification of DotGeneralOp

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
This output argument is only used by the reduce op verification and there also it is only using the element type. But, the function already verifies that the element types match the input types so we could directly use those and remove the extra output argument.
=> NFC: Remove unnecessary argument  in reducer function verification

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/verify_reduce.mlir
In the verification of the reducer function, while verifying that the block argument shape is a sub-sequence of the computed output shape, it doesn't consider dynamic shapes.
The original intention here might have been to check that `allowedDimensions[argShapeIdx]` was dynamic and not `argShape[argShapeIdx]`. Keeping the original check for now but I wonder if the op should simply disallow dynamic block arguments. Those are not going to be refined based on the input shapes. If so, such a check could be added later on.
=> Fix verifier check disallowing dynamic shapes in reduce and related ops

stablehlo/dialect/StablehloOps.cpp
PR #672 was based off HEAD which didn't yet have PR #510, and the former PR happened to make an incompatible change to an API (verifyReducerShape) used by the latter PR.
This PR fixes the incompatibility and fixes HEAD.
=> Fix broken HEAD

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
The implementation says "the output shape should be the most general of the operand shapes at each dimensions", but falls a bit short of delivering that. This PR fixes it.
Also merges the verifier into the shape function, to follow the design pattern that we've established for type inference, and switches to `inferMostSpecificType` which is used for the same purpose in several other ops. The latter prompted switching from `inferReturnTypeComponents` to `inferReturnTypes`, because `inferMostSpecificType` is only compatible with the latter.
=> Improve type inference for SelectOp

docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
Cannot write a FileCheck-based test because ReturnOp doesn't have result values.
=> Implement type inference for ReturnOp

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/verify_bounds.mlir
Implements TODO to add verification for bounds.
This is in preparation for moving bounds out of experimental as part of https://github.com/openxla/stablehlo/pull/194
I considered doing this in the RFC itself but better to do the code change separately and immediately given that these invariants are already assumed during type inference.
=> Verify bounds of ranked tensors

stablehlo/dialect/VhloOps.cpp
The fixes are suggested by internal presubmits.
=> fix clang-tidy suggestions

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
In addition, it updates the semantics of OutfeedOp and SendOp to explicitly mention that the 'result' is a token type.
Also removes adaptors from CreateTokenOp and AfterAllOp that are not used.
closes #699
=> Add type inference for OutfeedOp

stablehlo/dialect/StablehloBytecode.cpp, stablehlo/tests/ops_stablehlo_roundtrip.mlir
Based on MHLO implementation in: https://github.com/tensorflow/mlir-hlo/commit/984b124ecf96d3c0d1d447ffb70c1baca3d9868c
=> Add bytecode implementation for OutputOperandAlias

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
I missed something important when reviewing #711.
We cannot have a dependency from TypeInference.h to StablehloOps.h. It should be the other way around - both StablehloOps.h and hlo_ops.h depending on TypeInference.h
This PR severs the dependency by introducing an interface that abstracts away creating token types.
=> Sever the dependency from TypeInference.h to StablehloOps.h

stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloBytecode.h, stablehlo/dialect/VhloOps.cpp, stablehlo/tests/legalize_stablehlo_to_vhlo.mlir
Closes #675.
Favoring code duplication given the nature of the dialects, that they will diverge over time as any differences are introduced. StableHLO serialization only needs to support reading the latest version of the dialect. VHLO needs to support reading all versions of attributes and types. Also the only good way to share this code is via heavily templated methods.
=> Implement VHLO Bytecode Interface

docs/status.md
The type inference already exists under [StablehloOps.cpp](https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/StablehloOps.cpp#L302), so this PR only updates the status.md to reflect that, marking it as `yes*` since we do not have a spec for it yet.
closes #701
=> Update type inference status for CrossReplicaSumOp

docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/tests/print_stablehlo.mlir
Had this change in an internal repo from awhile ago, but did not submit since I was unsure if these would move to CHLO. This change can be submitted independently to that work.
```
%0 = "stablehlo.einsum"(%arg0, %arg1) { einsum_config = "ab,bc->ac" } : (tensor<8x16xf32>, tensor<16x8xf32>) -> tensor<8x8xf32>
%1 = "stablehlo.unary_einsum"(%arg0) { einsum_config = "ab->a" } : (tensor<8x16xf32>) -> tensor<8xf32>
-->
%0 = stablehlo.einsum %arg0, %arg1, config = "ab,bc->ac" : (tensor<8x16xf32>, tensor<16x8xf32>) -> tensor<8x8xf32>
%1 = stablehlo.unary_einsum %arg0, config = "ab->a" : (tensor<8x16xf32>) -> tensor<8xf32>
```
=> Prettyprinting for Einsum and UnaryEinsum

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
This is a pure refactor PR which fixes https://github.com/openxla/stablehlo/issues/400 (deprecated) and https://github.com/openxla/stablehlo/issues/623 (new)
As in the https://github.com/openxla/stablehlo/issues/623 , "we only need this for ops with regions", a full list of ops with region extract from https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/StablehloOps.td includes **11 ops** in total:
| Op | what's done |
| --- | --- |
| AllReduceOp | No change (already split) |
| CaseOp |  No change (region is indispensable for type inference)  |
| IfOp |  No change (region is indispensable for type inference)  |
| MapOp |  No change (region is indispensable for type inference)  |
| ReduceOp |  Split |
| ReduceScatterOp |  No change (Type Inference implementation on hold see …
=> Split verifiers and shape functions for ops with regions

docs/spec_draft.md
I noticed that something breaks markdown highlighting, and it was this typo.
=> Fix typo in the spec of AllReduceOp

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
fixes #523
A few points
1. adds verification checks for ColllectivePermute w.r.t. https://github.com/openxla/stablehlo/issues/498 
2. We do not have the upper bound check for replica ids in `source_target_pairs` as in https://github.com/tensorflow/tensorflow/blob/54926b8320184c2f07066d84b798e52ba6a74675/tensorflow/compiler/xla/service/hlo_verifier.cc#L714 because those checks [depends on](https://github.com/tensorflow/tensorflow/blob/54926b8320184c2f07066d84b798e52ba6a74675/tensorflow/compiler/xla/service/hlo_verifier.cc#L694) HloModuleConfig which not exposed in StableHLO. 
upd:
1. verification is `revisit` based on https://github.com/openxla/stablehlo/issues/498 (check empty replicas) and (2) above
=> Add spec for CollectivePermuteOp

stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
https://github.com/openxla/stablehlo/pull/686 implemented type inference for DynamicUpdateSliceOp using the currently statically-shaped spec. To support the previous dynamically-shaped uses of DynamicUpdateSliceOp, this PR adds support for dynamic shapes as well.
=> Support dynamic shapes in DynamicUpdateSliceOp's type inference

docs/spec_draft.md, docs/status.md, stablehlo/dialect/StablehloOps.td
=> Add spec for CustomCallOp

rfcs/20220912-compatibility.md, rfcs/20221031-fp8.md
Added "Status", "Initial version", "Last updated" metadata. Also added an FP8 RFC which redirects to the OpenXLA RFC to keep track of it.
=> Minor bookkeeping for recently approved RFCs

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
[Here](https://github.com/openxla/stablehlo/issues/498#issuecomment-1331396793) we decided on StableHLO to dis-allowing empty `replica_groups` but that needs some extra work to achieve that. 
If we want to share [verifyReplicaGroups](https://github.com/openxla/stablehlo/blob/59b68c586ea1381a7cb53e1217904f31755bb390/stablehlo/dialect/TypeInference.cpp#L326) logic with MHLO, we cannot just prevent empty `replica_groups` as there exists MHLO based tests [allowing](https://github.com/tensorflow/tensorflow/blob/1c83485345d1d7ff3e9c3afcce55d303e793e216/tensorflow/compiler/xla/mlir_hlo/mhlo/IR/hlo_ops_common.h#L67) that. 
The current  PR will temporarily preserve the same behavior of MHLO to allow code sharing till #498 is fixed.  Note the verification for all the collective ops are already …
=> Temporarily allow empty `replica_group` for MHLO parity

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
The implementation is a oneliner, but I think it'll still be good to share it with MHLO for consistency reasons.
=> Introduce inferSendOp

docs/spec.md, stablehlo/dialect/StablehloOps.td
1) Change api_version from enum to integer constant (since we're calling it implementation-defined anyway).
2) Change the example from using `%inputs0` to the more conventional `%input0`. (Also fix the outfeed example to follow the same convention as well).
=> Minor updates to the CustomCallOp spec

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
Extended reduce op shape function to also propagate bounds for dimensions that are not reduced.
Also, moved verifyCompatibleShapeWithBounds to public in Base.h
cc @zhouxin913  for review
=> Infer bounds for Reduce op

docs/spec.md, stablehlo/dialect/Base.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_while.mlir
The FP8 RFC has been approved (https://github.com/openxla/xla/discussions/22), so I'm following up and adding support for the proposed FP8 data types to StableHLO.
As discussed in RFC comments, there are other FP8 data types (https://github.com/openxla/xla/discussions/22#discussioncomment-4337622), and they can be included in StableHLO as well in the future, following the same RFC process. Please let us know if you're interested in working on this, and we will be happy to help!
=> Add support for f8E4M3FN and f8E5M2

docs/spec.md
stablehlo.case index input is an operand and not a constant.
=> NFC: Fix spec for stablehlo.case op

docs/bytecode.md, docs/reference.md, docs/status.md, docs/type_inference.md
This is a first pass at some simple issues found by `markdownlint`, but more will come as I gradually enable some of the lint rules that are currently disabled. Also, fixing the spec will be a massive change so that will be a separate PR perhaps done once the spec is near a more final state.
Partially fixes #792
=> Various markdown syntax fixes

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir
To continue deduplicate the verifiers and shape functions among StableHLO and MHLO, this PR, following https://github.com/openxla/stablehlo/pull/26, continue move 24 verifiers & shape functions from `StablehloOps.cc` to `TypeInference.h/cpp` with change to static methods and organize with alphabetical order.
This PR also includes:
1. Unify emit error methods with static `emitOptionalError()`
2. Similar to the discussion of https://github.com/openxla/stablehlo/issues/481, in the signuature of the new `inferAllToAllOp()`, I use `int64_t` instead of `uint64_t` to pass all the parameters to avoid verbose "static_cast to int" for each of attr in the method body. 
5. **Few or trivial tests changes**: No semantic changes or optimization.
Includes moves for (they are select in the first half of …
=> Move 26 verifiers shape functions to shared target

build_tools/README.md, docs/bytecode.md, docs/reference.md, docs/status.md, docs/type_inference.md, rfcs/20220912-compatibility.md
More fixes for #792 with expanded scope to MD files not under /docs. (Still not touching the spec yet.)
This includes markdownlint fixes that could not be fixed by `markdownlint-cli`, such as line length (80 char), consistent list item indications, proper heading levels, removal of bash "$" character when not necessary ([rationale](https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code); if the snippet includes multiple commands, then add a line break).
=> More MD syntax fixes, mostly line length

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td
Verification is missing two constraints. Filed https://github.com/openxla/stablehlo/issues/790 for that.
RFC discussing this op: https://github.com/openxla/stablehlo/pull/194
=> Add spec for GetDimensionSizeOp

docs/status.md, stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/TestUtils.cpp, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_conv.mlir
In their current formulation, these ops cannot have shape functions because their lhs/rhs element types can be different from their result element type.
Perhaps in the future we will add the `preferred_element_type` attribute to these ops (see #600), and then shape functions will be feasible to write again, but today we have to disable them.
=> Disable shape functions for ConvolutionOp, DotOp and DotGeneralOp

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBase.td, stablehlo/dialect/VhloEnums.td, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td
This is similar to how MHLO manages their custom types in [hlo_ops_typedefs.td](https://github.com/tensorflow/mlir-hlo/blob/master/mhlo/IR/hlo_ops_typedefs.td). 
These typedefs will also grow in upcoming submissions as other types are forked.
This allows us to use `VhloBase.td` as a tablegen target in a bazel build since it does not have complicated dependencies (adding typedefs makes a new dependency to VHLO_Dialect from VhloOps.td).
=> Separate VhloTypes into separate tablegen file

docs/spec.md
The PR fixes a typo in the specification of `DynamicUpdateSliceOp` related to how `max` argument of `clampOp` is determined. 
As a side note:
Recommended one improvement related to dynamic_slice/dynamic_update_slice ops in https://github.com/openxla/stablehlo/issues/289#issuecomment-1363409092
=> Fix some typo in  dynamicUpdateSlice

docs/spec.md
ToCs are automatically maintained by GitHub when there are 2 or more
headings: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/.
=> Remove the index of ops from the spec

docs/spec.md, stablehlo/dialect/StablehloOps.td
The "stablehlo" part of spec sections and spec permalinks is redundant.
It's a StableHLO spec, so it is reasonable to assume that it specs
StableHLO ops.
=> Remove "stablehlo" from "#stablehloadd" links

docs/spec.md
This is a convention that dates back to the very first specs that we wrote, but upon second look I think it's just boilerplate. E.g. we don't say "function of any supported types" or "tuple of any supported types".
The newly introduced formalization for types makes it very clear what are the various supported tensor types, value types, etc, so let's make things easier to read.
=> Replace "foo of any supported type" with "foo"

docs/spec.md
This PR follows up on #794 and updates the spec which I forgot to update originally.
=> Update the spec of AllToAllOp

docs/spec.md, stablehlo/dialect/StablehloOps.td
Compresses the definitions of numerical ops to:
* Drop mentions of implementation-defined behavior (in the Errors section, we already say that errors lead to implementation-defined behavior).
* Drop mentions of numerical accuracy (at the moment, we always say that it's implementation-defined, so we might as well say nothing to avoid boilerplate).
* Prefer oneliner bullets to describe behavior for individual categories of element types.
I didn't quite understand the spec for RemainderOp, so I left it mostly alone and opened #846 to track it.
=> Reduce the boilerplate in specs of numerical ops

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir
Note in `inferFftOp()` this old message
```
return emitOptionalError(
location, stringifyFftType(fftType),
" takes a complex tensor as input, but is given ", operandType, ".");
}
```
is replaced by
```
return emitOptionalError(
location, "FFT/IFFT/IRFFT",
" takes a complex tensor as input, but is given ", operandType, ".");
)
```
To avoid passing the arg FFType `fftType` to `inferFftOp()`. No tests changes for this because the test message happens to be "IRFFT takes a complex tensor as input".
=> Move inferFftOp and verifyRngOp with Enums

stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
The declaration of these util functions are removed in previous PRs because they are used in `TypeInference.cpp` only. But it turns out that they are used by MHLO as well: so need reinstate them.
=> Reinstate util functions in TypeInference.h

stablehlo/dialect/TypeInference.cpp
This enables code sharing opportunities with StableHLO.
Related MLIR-HLO commit: https://github.com/tensorflow/mlir-hlo/commit/b90f997f15d7e9d19714a8ac6886f8edf9472661.
=> Expose verifyConvolutionAttributes in TypeInference.h

stablehlo/tests/infer_stablehlo.mlir
I found a couple of inconsistencies in the tests in regards to what value to return (and lack thereof), so this PR fixes it.
=> Fix typos in infer_stablehlo.mlir tests

stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
DynamicUpdateSliceOp's ODS currently says:
```
def StableHLO_DynamicUpdateSliceOp: StableHLO_Op<"dynamic_update_slice",
[Pure, AllElementTypesMatch<["operand", "update", "result"]>,
AllShapesMatch<["operand", "result"]>, InferTensorType]> {
...
}
```
This was working fine before we introduced the notion of isCompatibleForHloTypeInference, but nowadays this is too restrictive. We should just drop AllShapesMatch<["operand", "result"]> because shape compatibility between operand and result is anyway checked by our type inference infrastructure.
=> Remove AllShapesMatch from DynamicUpdateSliceOp

build_tools/github_actions/lint_clang_format.sh
Changed to `git diff $BASE_BRANCH HEAD --name-only --diff-filter=d`
In plain terms this reads:
Diff the base branch (`origin/main` by default) with `HEAD`, only show file names, and skip any deleted files.
The lint action was failing since `clang-format FileNotFound.cpp` exits with a bash error code.
I made the changes in #895 locally to test the fix. Should work after we merge this in.
=> Fix clang-format lint action to skip deleted files

stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/ChloOps.cpp, stablehlo/tests/transform_chlo.mlir
When working on #622, I discovered that functions with CHLO ops aren't getting inlined, which is a miss because there's no reason for these ops to not be inlinable. For comparison, StableHLO and MHLO both implement this interface.
This PR fixes that and adds tests to make sure that things stay this way in the future as well.
=> Make CHLO ops inlinable

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
inferTriangularSolveOp currently directly compares dimension sizes for constraints C2 and C3.
This was working fine before we introduced the notion of isCompatibleForHloTypeInference, but nowadays this is too restrictive. We should use verifyCompatibleDims instead.
=> Relax dimension checks in TriangularSolveOp

stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td
Some ops in the StableHLO dialect have "load-bearing" result shapes, meaning that these shapes cannot be inferred from op's operands, attributes and regions.
For these ops, the current design philosophy involves one of the two approaches:
1) The shape is specified statically in the result type, e.g. see
ReshapeOp.
2) The shape is passed dynamically as an operand (or can be computed
indirectly from shape-related operands), e.g. see DynamicReshapeOp.
In the future (#8), we want to have one unified approach in these situations, but we're not there yet, and this PR is about an incremental improvement to the state of the art.
One important piece of the design philosophy for 1) is that these ops need to be restricted to produce HLO_StaticShapeTensor, otherwise it is unclear what their semantics …
=> Consistently use HLO_StaticShapeTensor

stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir
In this PR, we introduce inferFooOp functions for ops where result's element type is load-bearing: convert, convolution, dot, dot_general, uniform_quantize.
These functions return SmallVectorImpl<ShapedTypeComponents>& and only fill in the shape part. Even though these functions aren't be usable from the existing type inference framework (missing element types will mean that type inference will fail), they will allow sharing shape inference logic with #622.
bitcast_convert is an odd one. It does belong in this category, but its shape curiously depends on the relationship between the operand type and the result type, so implementing inferBitcastConvertOp is not possible, even if it returns ShapedTypeComponents.
=> Create inferFooOp functions for some infeasible ops

docs/status.md
As per https://github.com/openxla/stablehlo/pull/441#discussion_r1041744301, the spec should be a `revisit` for #730 which is now  fixed.
=> Update spec status for convolution op: `revisit` to `yes`

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloOps.td, stablehlo/tests/legalize_stablehlo_to_vhlo.mlir
Found this while converting some models to VHLO. `PrecisionConfigAttr` in stablehlo is an optional attribute. Missed this since it appears without the `OptionalAttr` tag in op definitions, because the attribute itself is defined using it.
=> Make precision config optional in VHLO

stablehlo/integrations/c/StablehloAttributes.cpp
The recent integrate PR (#912) missed fixing a few deprecated makeArrayRef calls because our build infrastructure didn't flag them (see #544 for the ticket that talks about the details).
This PR handles the missed calls.
=> Replace makeArrayRef with ArrayRef in Python bindings

stablehlo/tests/infer_stablehlo.mlir
WhileOp has trivial shape function which use operands types as result type. So nothing changes in this PR except providing a unit test cover that the result types are same as operand types with bounds. 
@smit-hinsu for review.
=> Handle bounds in the WhileOp shape function

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
closes #885 
Infer bounds for `SortOp`
* For ranked tensors infer bounds from corresponding tensors in `inputs` to` results`.
* For unranked tensors copy the shape as is.
Additional context - A stricter inference can be implemented where we can infer the most specific shape from all tensors in the input, as of now having a simple solution that is standard across most ops tops the requirement of inferring most specific shape.
=> Infer bounds for SortOp.

stablehlo/tests/infer_stablehlo.mlir
fixes #749 
For the ScatterOp, where the 
(C16) inputs[k] and result[k] have the same type for any k  [0, N)
and this is how the result type is inferred. 
(https://github.com/openxla/stablehlo/blob/81d520685c5cfe2620f995dbb09ac4399d000c9a/stablehlo/dialect/TypeInference.cpp#L2513).
IMO, we do not need to do anything special to handle the bounds as the bounds should get copied as part of copying the types. I wrote a test to check that input bounds are indeed propagated. Also I note that I do not have to use `inferReturnTypeComponents`  at all, for this case.
=> Handle bounds for ScatterOp shape function

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
Notes
* `verifyReduceScatterOp` function terminates early if the `operandType` or `resultType`'s `scatterDimension` is dynamic, so this particular change is not needed, but still revised it just to be safe.
* rng_bit_generator tests were defining unused constants, so those are removed.
closes #572 
closes #873
=> Relax remaining dimension checks to better support dynamism

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
SelectAndScatterOp's bound inference is very simple. There are two inputs: `operand` and `source`. The `source` contains the indices to the `result` tensor to place the reduced values from `operand`, so it does not affect the bound of the `result` tensor. As for `operand`, the type is equal to the `result` tensor. There is only a movement of values happening in this op (after reduction is applied, but this also does not affect the bounds), so we can propagate the bounds with no further inference done.
closes #754
=> Handle bounds in the SelectAndScatterOp shape function

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/integrations/c/ChloAttributes.cpp, stablehlo/integrations/c/StablehloAttributes.cpp, stablehlo/integrations/c/StablehloAttributes.h, stablehlo/reference/Index.h
llvm::Optional has been replaced with a legacy alias of std::optional and is planned to be removed after LLVM 16. Let's migrate away.
=> Remove remaining usages of llvm::Optional

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
closes #801
Infer bounds for `all_to_all` op
* Infer bounds information from operand type and update the bounds and dimension sizes for split and concat dimensions
according to the op logic.
=> Infer bounds for AllToAllOp.

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
The bounds are dictated by how the shape is manipulated during the reduction on a window moved by the strides. `inferWindowOutputShape` takes the shape and inferred window to calculate the output shape. Conveniently, we can replace the shape with the bound and get our desired inferred bounds.
closes #753
=> Handle bounds in the ReduceWindowOp shape function

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
closes #809, closes #810, closes #811, closes #869
Unify verification and inference for BatchNorm* Ops
* For all `batch_norm_*` ops infer all shapes and bounds from `operand` only.
* Verify `operand` feature dimension compatibility with `dim[0]` of `scale`.
* Remove `AllShapesMatch` and convert `AllTypesMatch` to `AllElementTypesMatch`.
* Check for shape compatibility instead of equality.
=> Infer bounds for BatchNorm* Ops.

docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/tests/print_stablehlo.mlir
Notes:
* Atan2: As discussed in #500, [shape_inference.cc](https://github.com/tensorflow/tensorflow/blob/2c1b3efe573befdda3f3db399eebb875e690082c/tensorflow/compiler/xla/service/shape_inference.cc#L1028-L1043) does allow integers, but our spec doesn't. However, since the ODS is now in sync with StableHLO spec, I'm marking the verification status to `yes`.
closes #262 
closes #499
closes #512 
closes #513 
closes #587
=> Update ODS to sync supported types to the spec

docs/spec.md
Some arguments are missing constraints as they are mentioned in the semantics section and/or are part of the Type column
Steps I followed to add the constraints for all ops (including ops that already have constraints column):
1. Add (missing) constraints for all instances of the Name occurring in the constraint
2. Abbreviate 3 or more consecutive constraints to save horizontal space
3. Omit adding Constraints column if none of the sections have constraints
Exception to the above steps:
* bitcast_convert: (C2) does not pertain to specific inputs/outputs
Other notes:
* Fixed typo in OrOp
* Minor formatting change in ScatterOp
closes #614
=> Add "Constraints" column to Inputs/Outputs

docs/status.md, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
`inferDynamicUpdateSliceOp` also has the same verification logic, so I've moved the duplicate logic to `variadicTensorsHaveSameElType` function.
closes #557
=> Verify that start_indices have the same type in DynamicSliceOp

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
encoding attribute is not required if the result is a scalar but the current code will end up incorrectly setting it to the input encoding attribute.
For the added test, the inferred result type was `tensor<f32, #stablehlo.type_extensions<bounds = [3]>>` but scalar tensors shouldn't have a bounds attributes. This was happening because boundsToEncoding returns the original encoding if the provided bounds are empty. boundsToEncoding doesn't differentiate between bounds being empty for scalars or bounds being empty for unbounded tensors.
I also checked that the other inference functions are not having a similar issue. (May have missed recently submitted shape functions.)
Reduce op inference also doesn't deal with sparse encoding attribute so we don't have to worry about that here.
cc …
=> Fix Reduce op bounds inference for scalar results

README.md
use `mkdir -p`, so that it doesn't fail if the dir already exists
=> Make build instructions repeatable

build_tools/github_actions/ci_build_stablehlo_code_coverage.sh, build_tools/github_actions/llvm_gcov.sh
```
Usage:
$ ci_build_stablehlo_code_coverage.sh [-g][-o output_dir] <llvm_build_dir> <stablehlo_build_dir>
-g               Generate HTML report (default false)
-o <output_dir>  Set the output to generate report (default /tmp/ccov)
```
```
./build_tools/github_actions/ci_build_stablehlo_code_coverage.sh ~/path-to/llvm-build/ ~/path-to/stablehlo-build/
-- Building StableHLO standalone
-- Using MLIRConfig.cmake in: /usr/local/google/home/gleasonk/Coding/llvm-build//lib/cmake/mlir
-- Using LLVMConfig.cmake in: /usr/local/google/home/gleasonk/Coding/llvm-build/lib/cmake/llvm
-- Building with -fPIC
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/gleasonk/Coding/stablehlo-build
[0/1] Running the StableHLO regression tests
Testing Time: 1.01s …
```
=> Add local code coverage generation tooling

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/ops_stablehlo.mlir
Of the two constraints mentioned in #790:
* (C1) is already checked by [verifyDimAttr](https://github.com/openxla/stablehlo/blob/main/stablehlo/dialect/StablehloOps.cpp#L117-L120), but have added a negative test
* (C2) is not added per discussion [here](https://github.com/openxla/stablehlo/pull/791#discussion_r1053899143)
closes #790
=> Verify dimension in GetDimensionSizeOp

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
The dimension sizes of result, corresponding to offset dimensions, depend on attributes (like `collapsed_slice_dims` and `slice_sizes`) and hence are always static. 
Whereas, the dimension sizes of result, corresponding to batch dimensions, depends on input `start_indices` and could be dynamic. The corresponding bounds, in that case,  are propagated from the `start_indices`.
Side notes:
I deliberately avoid making any changes in `inferGatherShape` which is currently shared by `GatherOp::inferReturnTypeComponents` and `GatherOp::reifyReturnTypeShapes`. The reason being I do not `reifyReturnTypeShapes` needs to handle the bounds. 
Because of the decision, we have  some duplicate code in line 1237 (duplicate of https://github.com/openxla/stablehlo/blob/afcbb953c12a2a3a8564cab73278f4b47021ec01 …
=> Handle bounds of Gather op

stablehlo/tests/TestUtils.cpp, stablehlo/tests/infer_chlo.mlir, stablehlo/tests/infer_stablehlo.mlir
* Move all usages of get_return_type_componets to get_return_types.
* Move `CHECK` directives in tests before the corresponding MLIR code.
closes #938
=> Remove InferReturnTypeComponents test pattern from hlo_test_infer.

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
Bounds of the result are inherited from the bounds of the operand, except for the bound of the last dimension for RFFT/IRFFT which is ? because it is computed statically.
closes #805
=> Handle bounds in the FftOp shape function

docs/interpreter_checklist.md, docs/reference.md
Provides a doc to be followed while introducing the interpreter implementation of an op. 
Added @GleasonK.
Can you please take a look the the item related to running the `ccov`.
=> Interpreter implementation and review guidelines

stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h
Based on the proposal discussed @ https://github.com/openxla/stablehlo/issues/1000, this PR implements the first step:  "to replace `eval(AddOp, ...)` with `eval_add(Type returnType, ...)`.
This changes immediately enables reusing the `eval_op` for an `op` whose type can be trivially inferred (like most of the elementwise ops).
=> Update eval signature for re-usability

docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
I added a shape function for ReturnOp when working on an initial version of #622 which was relying on --tf-shape-inference.
TensorFlow's shape inference needs all ops which are not hardcoded in the pass to have shape functions, so I added one for ReturnOp even though it is has unclear utility beyond this specific use case (ReturnOp doesn't have any results, so its shape function returns an empty vector, which isn't super useful).
Now that we're working towards a dedicated shape refinement pass for StableHLO, we no longer need a shape function for ReturnOp, so I'm proposing to remove it in this PR.
=> Remove type inference for ReturnOp

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
If slice_sizes are constant, then we can infer static dimension sizes for the offset dims parts of the result shape.
=> Improve type inference for DynamicGatherOp

docs/reference_checklist.md
Adding constrain-labels, from specification, in the ODS. This is along the same line with the checklist items of adding the labels in `TypeInference.cpp` and `StablehloOps.cpp`.
=> Update reference_checklist: Add constraint labels in ODS

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
Based on the proposal discussed @ https://github.com/openxla/stablehlo/issues/1000, this PR implements the second step: "Sharing the shape inference code from TypeInference.cpp"
Some of the salient  features of the PR:
1. Addresses updating the signature of the type-inference-methods of 4 four ops (`concatenate, dot_general, reduce, slice`) which, according to #1000, could be shared for type-inference and reference implementation.
2. The shared code (e.g. `inferDotGeneralOp, inferConcatenateOp, inferSliceOp, inferReduceOp`)  do have code related to verification of input/output constraints. That means, the reference implementation will execute that verification code
whenever it wants to re-use the eval for those ops. Those verification checks are  redundant, as they must have already been …
=> Update signature of `infer<Op>` function for re-usability

.github/actions/setup-build/action.yml, .github/workflows/buildAndTestCMake.yml, .github/workflows/buildBazel.yml, .github/workflows/lint.yml, .github/workflows/markdown_lint.yml
This PR contains a number of assorted cleanups:
1) Alignment between buildAndTestCMake.yml and buildBazel.yml
(including workflow and job names as well as commits).
2) Adding license headers next to copyrights, to be consistent with
other files in the repository.
=> Clean up GitHub workflows

WORKSPACE.bazel, build_tools/github_actions/lint_llvm_commit.sh
In our previous LLVM Integrate, the SHA256 was calculated incorrectly. This PR addresses this by also verifying that the SHA256 value is also correct even if the llvm commit matches.
=> Update lint_llvm_commit.sh to also verify SHA256

stablehlo/dialect/Base.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir
For all dimensions, it infers the most specific of the `onTrue` and `onFalse` bounds, following the same inference rule in `inferMostSpecificTypeComponents`, so there is no change required to the inference rule except that the code for `inferMostSpecificTypeComponents` is updated to also include bounds information.
closes #750
=> Handle bounds in the Select shape function

stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h
This PR migrates away from using `DenseIntElementsAttr` in favor of `SmallVector<int64_t>`. The rationale is that it is harder to construct MLIR wrapper classes, and we want to avoid having a mix of custom classes (Tensor) and MLIR classes (DenseIntElementsAttr, with ConstantOp being an exception for now) so that we can use the `evalFoo` functions when a more complex op can benefit from reusing them.
closes #1031
=> Migrate away from using MLIR Attributes in `evalTransposeOp`

stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp
Removes braces around functions which only have one line for conciseness.
=> Standardize formatting in Ops.cpp and Interpreter.cpp

build_tools/github_actions/lint_llvm_commit.sh
The SHA256 check takes awhile, and really only impacts llvm revision bump changelists. Given that I run all lint scripts on pre-commit, I'd prefer a way to only verify commit, if commit changes, then I can worry about sha256 validation. In CI we will always check both.
Also I refactored the script a bit, there was so much global state that it was difficult to make modifications, modified to have minimal global state and functions that echo their results. We lose some logging with this, but the error messages we see are still pretty good.
Mismatch error messages:
```bash
$ ./build_tools/github_actions/lint_llvm_commit.sh -s .
Validating LLVM commit hash...
Commit mismatch:
1c1
< f58de2125caf75ec0d40bc3e094a93c0b314a66a
---
> 858de2125caf75ec0d40bc3e094a93c0b314a66a
Auto-fix using:
$ …
```
=> Update llvm lint tool with flag to disable SHA256 check

stablehlo/dialect/Base.cpp
This is to fix the case when all the `inputTypes` in `inferMostSpecificTypeComponents` is unranked.
=> Handle unranked input types in `inferMostSpecificTypeComponents`

.bazelignore
This enables Bazel to skip the Bazel build of the llvm-project/ folder that shows up when building the repo using the standard CMake workflow documented in README.md.
Without this, Bazel gets pretty confused and produces rather cryptic error messages.
=> Add .bazelignore

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h
This is a quick fix revert back the return type of inferMost/LeastType methods from ShapeType to Type, to accommodate the tuple type in MHLO tests.
=> Change return type for shape function of bounds

docs/reference.md
The PR updates the interpreter testing guidelines  based on https://github.com/openxla/stablehlo/pull/996#discussion_r1093590287.
=> Update interpreter testing guideline with coverage criterion

.github/workflows/buildAndTestCMake.yml, .github/workflows/buildBazel.yml, .github/workflows/lint.yml, .github/workflows/markdown_lint.yml
Resolves actions stalling endlessly on forks with:
See: https://github.com/GleasonK/stablehlo/actions/runs/4087406604
- clang-format has the change and uses the public runner
- lint whitespace does not and waits for runner
Forked repo running CI: https://github.com/GleasonK/stablehlo/actions?query=ci-runner
OpenXLA repo running CI: https://github.com/openxla/stablehlo/actions?query=ci-runner
=> Use public runners on forked repos

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Reverting https://github.com/openxla/stablehlo/pull/958 to unblock downstream integration.
The tests which are failing downstream falls into two categories:
(1) Verifier failing on compareOps with  wrong combination of element-type and compare_type. 
(2) Verifier  failing on creating `compareOp` with `compare_type == NOTYPE`. Note that creating a compareOp with `NOTYPE` is still allowed. 
(3) Type inference failures: As the implementation of verification and type inference is unified for this op, the above mentioned categories also contributed to type inference failures.
=> Revert #958: Verify compare_type for compare_op

docs/spec.md
Now that we have clearly identified the deltas between how the StableHLO dialect is used by frontends and what is specced (see https://github.com/orgs/openxla/projects/6), I figured it would be good to link these deltas in the spec, so that it's clear what areas are expected to change in the near future.
As I was working on this pull request, I also called out several tickets which are not part of the Frontend Contract project, because they represented highly likely todos from the New Features project. I think this is also useful to include in the spec for the readers to understand the anticipated direction of StableHLO evolution.
=> Link frontend contract tickets in the spec

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Interpreter.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_slice.mlir, stablehlo/tests/ops_stablehlo.mlir
```
// Ix constraints come from the Inputs table
(I1) operand tensor
(I2) start_indices 1-dimensional tensor constant of type si64
(I3) limit_indices 1-dimensional tensor constant of type si64
(I4) strides 1-dimensional tensor constant of type si64
(C1) operand and result have the same element type.
(C2) size(start_indices) = size(limit_indices) = size(strides) = rank(operand).
(C3) 0 <= start_indices[d] <= limit_indices[d] <= dim(operand, d) for all dimension d.
(C4) 0 < strides[d] for all dimension d.
(C5) dim(result, d) = ... for all dimension d in operand.
```
```
I1: a) operand is not a tensor. (Covered by ODS).
I2: a) start_indices is not a tensor. (Covered by …
```
=> Add interpreter for SliceOp

docs/spec.md
Added Input constraint labels to help refer to input constraint while
1. writing PR description like [this]( https://github.com/openxla/stablehlo/pull/996#discussion_r1096336612) which makes sure all the constraints  have corresponding verification logic and tests.
2. Adding comments in tests and implementation of verifiers.
=> Add Input constraint labels

stablehlo/dialect/StablehloOps.cpp
I recently noticed this code when reviewing #849, and I'm not sure why we need it there.
This seems like a pretty strong statement about a fundamental role of the Tensor dialect in the workings of the StableHLO dialect, and I don't think we have established that yet.
It would seem that we've inherited this from MHLO when bootstrapping StableHLO (#1), but I don't think I understand the reasoning on the MHLO side either. This change was introduced as part of an LLVM integrate (https://github.com/tensorflow/mlir-hlo/commit/ba0346b071f4212008943c50f47766e677992b56), and the commit description doesn't go into detail about motivation.
Given that, I propose to revert this in the StableHLO dialect and see what happens. All tests in this repository are passing, but maybe we'll learn more after …
=> Don't load Tensor dialect in StableHLO dialect constructor

BUILD.bazel
This should allow us to use one build file for mlir-hlo, tensorflow, and stablehlo repositories.
Boils down to: tablegen targets need `include = ["."]` and most other targets need `skip_include_prefix = "."`, inspired by https://github.com/tensorflow/mlir-hlo/blob/master/BUILD
=> Modify build file so StableHLO can be included in other projects

stablehlo/dialect/StablehloOps.cpp
Manually fixing as part of clang-tidy check which is currently not supported in StableHLO #61
=> Use const reference for loop variable to avoid copy

docs/reference_checklist.md
Allow consistency cover all the spec constraints.
=> Update the ODS with input constraints from the spec

build_tools/github_actions/lint_markdown.sh
This change allows for 2 arguments to be specified, and forward them to the `markdownlint-cli`. This allows us to use the `-f` flag to autofix markdown issues.
Modifying contribution from @scottamain, if there is any reason to avoid this flag let me know!
=> Allow -f fix for lint_markdown.sh

BUILD.bazel, stablehlo/dialect/CMakeLists.txt, stablehlo/integrations/c/CMakeLists.txt, stablehlo/integrations/c/VhloDialect.cpp, stablehlo/integrations/c/VhloDialect.h, stablehlo/integrations/python/CMakeLists.txt, stablehlo/integrations/python/VhloModule.cpp, stablehlo/integrations/python/mlir/dialects/VhloOps.td, stablehlo/integrations/python/mlir/dialects/vhlo.py, stablehlo/integrations/python/tests/CMakeLists.txt, stablehlo/integrations/python/tests/vhlo.py
These are pretty minimal VHLO bindings. We don't intend for Python/C users to directly interact with VHLO attributes / types, so we only need the ability for Python to register the dialect to parse and serialize.
Currently this is based on CHLO bindings, except only Dialect-related bindings are provided currently, no attributes or types.
=> Add VHLO Python/C Bindings

stablehlo/dialect/StablehloOps.td
For "Not in HLO" ops, the ODS now indicates that they are on their way out of StableHLO and informally explains their semantics.
For "Dynamism" ops, the ODS now says that they are being worked on and also informally explains their semantics.
Closes #739.
=> Update ODS documentation for yet unspecced ops

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_broadcast_in_dim.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) operand tensor.
(I2) broadcast_dimensions 1-dimensional tensor constant of type `si64`.
(C1) `operand` and `result` have the same element type.
(C2) size(`broadcast_dimensions`) $=$ rank(`operand`).
(C3) $0 \le$ `broadcast_dimensions[i]` $\lt$ rank(`result`) for all
dimensions i in `operand`.
(C4) All dimensions in `broadcast_dimensions` are unique.
(C5) For all dimensions `j` in `operand`:
* `dim(operand, j) = 1` or
* `dim(operand, j) = dim(result, i)` where `i = broadcast_dimensions[j]`.
```
```
I1: a) operand is not a tensor. (Covered by ODS).
I2: a) broadcast_dimensions is not a 1-dimensional tensor.
b) broadcast_dimensions does not have `si64` type. …
```
=> Add interpreter for BroadcastInDimOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_pad.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) operand tensor
(I2) padding_value 0-dimensional tensor
(I3) edge_padding_low 1-dimensional tensor constant of type si64
(I4) edge_padding_high 1-dimensional tensor constant of type si64
(I5) interior_padding 1-dimensional tensor constant of type si64
(C1) `operand`, `padding_value`, `result` have the same element type.
(C2) `edge_padding_low`, `edge_padding_high`, `interior_padding` have the
size equal to `operand`'s rank.
(C3) 0 $\le$ `interior_padding[i]` for all `i` values in `interior_padding`.
(C4) 0 $\le$ `dim(result, i)` for all `i`th dimension of `operand`, where
`dim(result, i) = di + max(di - 1, 0) * interior_padding[i] + edge_padding_low[i] + edge_padding_high[i]`
and `di = dim(operand, i)`.
```
These constraints will be …
=> Add interpreter for PadOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_dynamic_update_slice.mlir, stablehlo/tests/ops_stablehlo.mlir
Unlike the spec, the interpreter uses its own implementation of clamp to calculate `adjustedStartIndices` since the start indices are given as variadic tensors, and formulating as one tensor to use the ClampOp is more loc.
```
(I1) operand tensor.
(I2) update tensor.
(I3) start_indices variadic number of 0-dimensional tensors of integer type.
(C2) element_type(`update`) $=$ element_type(`operand`).
(C3) rank(`update`) $=$ rank(`operand`).
(C4) size(`start_indices`) $=$ rank(`operand`).
(C5) All `start_indices` have the same type.
(C6) dim(`update`, `k`) $\in$ [0, dim(`operand`, `k`)] for all `k` $\in$ [0, rank(`operand`)).
```
These constraints will be comprehensively covered by the following …
=> Add interpreter for DynamicUpdateSliceOp

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
This PR adds a RefineConvolutionOpPattern pattern that reuses inferConvolutionOp to do shape refinement for DynamicConvOp.
Additionally, it makes some changes to constant folding patterns to support related shape computations.
=> Add support for DynamicConvOp to --stablehlo-refine-shapes

README.md, docs/roadmap.md
As we've been exploring the StableHLO opset, we've been making notes about all kinds of todo items - starting from minor cleanups in the StableHLO dialect all the way to missing functionality in the opset.
This is great because thanks to that we have documented at great length what it would take for StableHLO to reach its full potential - with perfect frontend contract, 100% specification compliance, etc etc.
This level of detail (at the moment of writing, we have 275 tickets in our issue tracker) would benefit from some organization, and this is something that this PR proposes.
Recently, we have categorized the tickets in the issue tracker into multiple workstreams and tied these workstreams to the milestones. The roadmap.md introduced in this PR brings this all together.
=> Organize ongoing work items in workstreams and milestones

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
This is a prototype of the CustomCallOp shape refinement mechanism to enable specializing dynamically-shaped programs with custom calls to static shapes (#851).
Based on the results of prototyping, I'm planning to propose an RFC to extend CustomCallOp, so that the logic can migrate from using an unregistered attribute to something more solid.
=> Prototype a mechanism to customize shape refinement for CustomCallOp

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloOps.cpp, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Need to escape string with unprintable characters because it can cause printer/parser issues.
Namely, I recently was parsing a string where the binary data included the ascii for `"`, which caused the string to be malformed as `vhlo.string<"ab"cd">`
=> Print escaped string to preserve binary data

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_dynamic_slice.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) operand tensor.
(I2) start_indices variadic number of 0-dimensional tensors of integer type.
(I3) slice_sizes 1-dimensional tensor constant of type `si64`.
(C1) `operand` and `result` have the same element type.
(C2) size(`start_indices`) $=$ size(`slice_sizes`) $=$ rank(`operand`).
(C3) All `start_indices` have the same type.
(C4) `slice_sizes[k]` $\in$ [0, dim(`operand`, `k`)] for all `k` $\in$ [0,
rank(`operand`)).
(C5) shape(`result`) $=$ `slice_sizes`.
```
```
I1: a) operand is not a tensor. (Covered by ODS).
I2: a) start_indices is not a variadic 0-dimensional tensors. (Covered by ODS).
b) start_indices does not have integer type. (Covered by ODS).
I3: a) …
```
=> Add interpreter for DynamicSliceOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_clamp.mlir, stablehlo/tests/ops_stablehlo.mlir
ClampOp has Inputs and constrains:
(I1) min is tensor. (By ODS)
(I2) operand is tensor. (By ODS)
(I3) max is tensor. (By ODS)
(C1) Either rank(min)=0 or shape(min)=shape(operand).
(C2) Either rank(max)=0 or shape(max)=shape(operand).
(C3) min, operand, and max have the same element type. (By ODS)
(C4) operand and result have the same type.
I1, I2, I3, and C3 is done by ODS.
C1, C2, C4 are verified by `inferClampOp()` in `TypeInference.cpp`
=> Add interpreter for ClampOp

stablehlo/dialect/Base.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/Version.cpp, stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td, stablehlo/integrations/c/ChloAttributes.cpp, stablehlo/integrations/c/StablehloAttributes.cpp
See https://discourse.llvm.org/t/llvm-unreachable-is-widely-misused/60587 for motivation.
=> Replace all uses of llvm_unreachable with llvm::report_fatal_error

docs/spec.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/VhloDialect.td, stablehlo/dialect/VhloOps.td, stablehlo/integrations/python/tests/vhlo.py, stablehlo/tests/vhlo_to_version_attrtype_invalid.mlir, stablehlo/tests/vhlo_to_version_upgrade.mlir
Our design principle for VHLO ops has been radical minimalism, and this
PR further streamlines operation definitions:
1) Sorts all ops alphabetically.
2) Removes the stray assemblyFormat from ReturnOp.
3) Spells out VHLO op design principles in a comment in VhloOps.td.
4) Updates the description of VhloDialect.td to align with the
design principles.
Using the results of streamlining (the part where all ops got sorted
alphabetically), I completed an audit of VhloOps.td, aligning it as
much as possible with the StableHLO spec and leaving todos where that
is not yet possible.
During that audit, I discovered minor discrepancies between the spec
and StableHLO/VHLO ODS, involving names and order of program elements,
and fixed them as well.
=> Audit VhloOps.td

stablehlo/dialect/VhloEnums.td
As I was auditing the VHLO dialect for the correspondence with the spec, I figured I'd streamline the VhloEnums.td as follows:
1) Order alphabetically.
2) Factor out I32EnumAttr boilerplate into VHLO_I32EnumAttr and
reformat to compress the code a little bit.
3) Drop summaries from I32EnumAttrs (this is aligned with the notion
of VHLO being a shallow dialect, e.g. we don't have them for ops).
4) Removed a few unused definitions.
I've also noticed that getMinVersion/getMaxVersion implementations for VHLO_EnumAttr didn't have explicit error handling - probably this resulted from partially addressed feedback on one of the VHLO PRs? Anyway, I made these implementations consistent with similar VHLO code, using llvm::report_fatal_error instead of llvm_unreachable to forward port the …
=> Audit VhloEnums.td

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloOps.cpp, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/tests/vhlo_to_version_upgrade.mlir, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp, stablehlo/transforms/VhloToVersion.cpp
This is one of the several steps towards aligning VhloAttrs.td with the StableHLO spec.
Keeping the forked name is understandable, but I think that alignment with the spec is more important. See #1047.
=> Rename VHLO_DenseIntOrFPElementsAttr to VHLO_TensorAttr

stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloOps.cpp, stablehlo/dialect/VhloTypes.cpp, stablehlo/dialect/VhloTypes.td, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/tests/vhlo_to_version_upgrade.mlir, stablehlo/transforms/VhloToVersion.cpp
This pull request completes the audit of VhloTypes.td, including refactorings aimed to align the file with the spec.
1) Order alphabetically, merging native and forked types.
(Within the vision that types must correspond 1:1 to the
specification, there's no difference between where these types
are originally coming from, so there's no need to separate the
two categories).
2) Introduce BooleanType to match the spec.
3) Rename FunctionType::results to FunctionType::outputs to match
the spec.
4) Rename IntegerI...Type to IntegerSI...Type to match the spec.
5) Rename floating-point types to FloatBF...Type or FloatF...Type
to match the naming style used for integer types.
6) Add comments to each attribute, either identifying the
corresponding program element from the spec or linking a ticket …
=> Audit VhloTypes.td

stablehlo/dialect/VhloAttrs.td
Minor refactoring for FuncOp-related attributes
VHLO_DictionaryAttrV1 didn't have "V1" appended to its name, unlike
other nearby attributes.
Also, since neither VHLO_DictionaryAttr nor VHLO_TypeAttr are called
out in the spec yet, I've added corresponding todos that link to
the appropriate ticket. See #1047.
=> Minor refactoring for FuncOp-related attributes

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBytecode.cpp, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
This is one of the several steps towards aligning VhloAttrs.td with
the StableHLO spec.
As far as representational power goes, UnitAttr is equivalent
to BooleanAttr, so in the spirit of VHLO being a shallow dialect, I
think that we should remove the former and use the latter instead.
When making this change, I noticed that BooleanAttr attributes from
StableHLO get translated to IntegerAttr attributes from VHLO. This has
been changed to use the newly introduced BooleanAttr from VHLO.
This is a breaking change for VHLO, and I was hesitating whether to
provide proper versioning for it or not. Ultimately, I decided that
I won't be doing that, similarly to how the work on forking attributes
and types (also a breaking change) didn't do that. We haven't yet
officially released VHLO, so I think …
=> Replace VHLO_UnitAttr with VHLO_BooleanAttr

BUILD.bazel, stablehlo/reference/Axes.cpp, stablehlo/reference/Axes.h, stablehlo/reference/CMakeLists.txt, stablehlo/reference/Index.cpp, stablehlo/reference/Index.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Sizes.cpp, stablehlo/reference/Sizes.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h
closes https://github.com/openxla/stablehlo/issues/1163
The PR:
1. Introduces a class `Index` to represent the index vector of a `Tensor`. That is to replace the explicit use of `ArrayRef<int64>` for the purpose. 
2. `Tensor::begin_index` and `Tensor::end_index` to return `Index` objects instead.
3. Promote the use of `Index` in various `evalFooOp`. The use of overload `Index::operator+` is handy for `DynamicSlice`  and `DynamicUpdateSlice` op.
=> Introduce Index class

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloOps.td, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/tests/vhlo_to_version_downgrade_invalid.mlir, stablehlo/tests/vhlo_to_version_upgrade.mlir, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp, stablehlo/transforms/VhloToVersion.cpp
I think that grouping of the elementary attrs into bigger attrs is
pretty incidental as far as serialization format goes, so I would
propose to break all of them down, just like the spec does.
This is a breaking change for VHLO, and I was hesitating whether to
provide proper versioning for it or not. Ultimately, I decided that
I won't be doing that, similarly to how the work on forking attributes
and types (also a breaking change) didn't do that. We haven't yet
officially released VHLO, so I think that it's fine. See #1047.
=> Inline VHLO_ConvDimensionNumbersAttr and friends

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloBytecode.cpp, stablehlo/dialect/VhloOps.cpp, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
This pull request completes the audit of VhloAttrs.td, following a
significant refactoring aimed to align the file with the spec.
1) Order alphabetically, merging native and forked attributes.
(Within the vision that attributes must correspond 1:1 to the
specification, there's no difference between where these attributes
are originally coming from, so there's no need to separate the
two categories).
2) Add comments to each attribute, either identifying the
corresponding program element from the spec or linking a ticket
that tracks the alignment effort.
3) Rename kFooAttr to kFooV1Attr to be consistent with the TableGen
file that defines the attributes.
4) Renumber kFooAttr in increasing order to match the alphabetical
order of the names. (This is a breaking change for VHLO, but I
think …
=> Audit VhloAttrs.td

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
This follows up on the recent DynamicConvOp pull request and introduces additional functionality to handle accompanying shape computations.
=> Add support for folding SignOp in --stablehlo-refine-shapes

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
At the moment, AllGatherOp and ReduceScatterOp don't have shape functions because they rely on `dim(process_groups, 1)` which in its full generality requires knowledge of `num_partitions`.
(Per https://github.com/openxla/stablehlo/blob/main/docs/spec.md: For cross_replica and flattened_ids process grouping strategies, `dim(process_groups, 1)` is equal to `dim(replica_groups, 1)`. However, for cross_replica_and_partition `dim(process_groups, 1)` is equal to `dim(replica_groups, 1) * num_partitions`).
Even though we cannot have shape functions for these two ops without changing the StableHLO spec, we can still make best effort at refining their shapes for cross_replica and flattened_ids cases. This is what this PR implements.
=> Add support for collective ops in --stablehlo-refine-shapes

stablehlo/dialect/VhloBytecode.cpp
This change was depending on two independent PR chains landing, so it couldn't be done in either of these chains.
Now that both PR chains have landed, this has become a very straightforward change.
=> Stop using BooleanV1Type in IntegerV1Attr

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_rsqrt.mlir
closes #986 
```
(C1) operand and result have the same type.
```
```
(I1) operand is not a tensor of floating-point or complex type. (covered by ODS)
(C1) operand and result do not have the same type. (covered by ODS)
```
=> Add interpreter for RsqrtOp.

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_divide.mlir
closes #971 
```
(I1) lhs is a tensor of integer, floating-point, or complex type.
(I2) rhs is a tensor of integer, floating-point, or complex type.
(C1) lhs, rhs, and result have the same type.
```
```
(I1) lhs is not a tensor of integer, floating-point, or complex type. (covered by ODS)
(I2) rhs is not a tensor of integer, floating-point, or complex type. (covered by ODS)
(C1) lhs, rhs, and result do not have the same type. (covered by ODS)
```
Add a binary op version of mapWithUpcastToDouble
=> Add interpreter for DivideOp

BUILD.bazel
A downstream linter noticed a change in BUILD.bazel and decide to opine on overall formatting in the file, even beyond the changed lines.
I think it's a reasonable idea to humor it and apply the formatting changes here as well.
=> Reformat BUILD.bazel

docs/reference_checklist.md
* The checklist now covers tests in `infer_stablehlo.mlir` and moves related test from `ops_stablehlo.mlir` to this file.
* Clarification made on the example to remove ambiguity in certain cases.
=> Update checklist to review shape inference

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_real.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(C1) shape(`result`) = shape(`operand`).
(C2) element_type(`result`) $=$
* element_type(`operand`) if it's a floating-point type.
* real_type(element_type(`operand`)) otherwise.
```
I1 and C1 is covered by the ODS and C2 is covered in inferRealOp() as part of the type inference. Two redundant ODS tests are removed.
closes #1108
=> Add interpreter for RealOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_imag.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(C1) shape(`result`) = shape(`operand`).
(C2) element_type(`result`) $=$
* element_type(`operand`) if it's a floating-point type.
* real_type(element_type(`operand`)) otherwise.
```
I1 and C1 is covered by the ODS and C2 is covered in inferImagOp() as part of the type inference. Two redundant ODS tests are removed.
closes #1103
=> Add interpreter for ImagOp

stablehlo/reference/Ops.cpp
Using a range-based for loop makes things easier to read.
=> Simplify evalConcatenateOp

docs/spec.md
PR #1164 updated the spec of IfOp to say that pred is a 0-dimensional tensor, fixing an oversight from the PR that introduced this spec.
However, this PR also said that pred is a constant, which it is not. I missed that during review, and this PR fixes this.
=> Fix a typo in the spec of IfOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_rem.mlir
(I1) lhs tensor of integer, floating-point or complex type (covered by ODS)
(I2) rhs tensor of integer, floating-point or complex type (covered by ODS)
(C1) lhs, rhs and result have the same type. (covered by ODS)
Note that all constraints are covered by ODS, so no tests in ops_stablehlo.mlir.
It is expected that `hlo_evaluator` and `mlir_interpreter` handle corner case differently ([hlo_evaluator](https://github.com/tensorflow/tensorflow/blob/c4c3c066d48983f57afd9e8fbe3734b03ee98018/tensorflow/compiler/xla/hlo/evaluator/hlo_evaluator_typed_visitor.h#L686) vs [mlir_interpreter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/mlir_hlo/tools/mlir_interpreter/dialects/cwise_math.h#L83)). Here is our way (same as comment in code):
// These cases are …
=> Add interpreter for RemOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_case.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) index 0-dimensional tensor constant of type `si32`.
(I2) branches variadic number of functions.
(C1) `branches` have at least one function.
(C2) All functions in `branches` have 0 inputs.
(C3) All functions in `branches` have the same output types.
(C4) For all `i`, `type(results[i]) = type(branches[0].outputs[i])`.
```
```
I1: a) index is not 0-dimensional tensor.
b) element_type(index) != `si32`. (Covered by ODS).
I2: a) branches is not variadic functions. (Covered by ODS).
C1: a) size(branches) < 1.
C2: a) not all functions in `branches` have 0 inputs.
C3: a) not all functions in `branches` have the same output types.
C4: a) type(results[i]) != …
```
=> Add interpreter for CaseOp

stablehlo/tests/CheckOps.cpp
Even though we have a dedicated issue https://github.com/openxla/stablehlo/issues/1196 to help improving such cases, this change will have some immediate benefits during debugging.
=> Add index info in interpreter-mismatch error message

docs/status.md
We don't have a ticket for writing an interpreter for this op, and it's not something that we can test in isolation, but it is supported, and this PR reflects that.
=> Mark ReturnOp as having an interpreter

stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
In the last few pull requests, I crammed a lot of adhoc logic into
the corresponding conversion patterns.
When working on removing optional attrs from VHLO, I needed to further
update the conversion patterns, and I found it to be unnecessarily
complicated with all the stuff in there.
This PR refactors the conversion patterns to encapsulate the logic
that bridges the gaps between StableHLO and VHLO. I think that modifying
the conversion patterns will become considerably easier now.
=> Refactor StableHLO <=> VHLO

stablehlo/dialect/VhloOps.td, stablehlo/integrations/python/tests/vhlo.py, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
Continuing to explore the design principle of aligning VHLO with the
spec, I realized that having optional attributes goes against that.
In the spec, we deliberately skipped the notion of optional attributes
and default values, treating all attributes as mandatory. Given that,
I think it's worth considering doing the same in VHLO.
More concretely, for all OptionalAttr and Default...Attr in StableHLO,
this PR changes the corresponding VHLO attributes from
OptionalAttr<VHLO_AnyAttr> to VHLO_AnyAttr. (FWIW, the three attributes
modeled via DefaultValuedStrAttr in StableHLO have already been modeled
via VHLO_AnyAttr in VHLO).
Furthermore, the StableHLO => VHLO conversion is changed to add these
attributes to VHLO operations in case they are missing from StableHLO
operations. And vice versa - …
=> Remove OptionalAttr from VHLO

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloEnums.td, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td, stablehlo/integrations/python/tests/vhlo.py, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
We've been oscillating on vhlo.foo vs vhlo.foo_v1 in the last few months, but vhlo.foo_v1 has won because of its explicitness - we have encountered quite a few questions along the lines of "if I see vhlo.foo, what version does it have?".
In the current design, VHLO isn't supposed to be manipulated by users directly, so we figured that the downside of increased verbosity is going to be relatively minor in practice. If this ends up not being the case, then this decision isn't going to be set in stone - we will always be able to drop _v1 before the 1.0 release.
=> Use _v1 in VHLO mnemonics

stablehlo/testdata/CMakeLists.txt
PR #1221 renamed stablehlo/conformance to stablehlo/testdata because we're not ready to call it a conformance suite, and this PR cleans up the remaining traces of the original name in the build file.
=> Update build to remove traces of conformance

stablehlo/dialect/StablehloOps.td, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Currently printing CholeskyOp with default value will cause a crash since the attribute is not assigned.
This disables the diff test in `legalize` since there are a few diffs that were hidden due to this crashing behavior. These will be addressed in a followup.
=> Fix prettyprint bug with default optional attr in CholeskyOp

docs/compatibility.md, rfcs/20220912-compatibility.md
In preparation for the imminent v0.9 release, we put together a document which describes the exact extent of compatibility guarantees at this moment, including testing strategy and future work.
Closes #679.
=> Add compatibility.md

build_tools/github_actions/lint_whitespace_checks.sh
Now that we have a bunch of test files, it saves a lot of time to only lint changed files.
Granted we will likely be shedding most of these test files soon (reorganizing, trimming, changing where they are stored, or something else), this is still a worthwhile change to make.
Also updated the fix link so that it is copy-pastable. This tool is only runnable from the root directory as it is, so including full relative path is probably best.
=> Only lint whitespace for changed files

docs/compatibility.md
This PR reformulates compatibility.md solely in terms of StableHLO to avoid exposing users to the implementation details of the serialization format.
There are dedicated document about those details - bytecode.md and vhlo.md - but the entire target audience of compatibility.md doesn't have to know about them.
=> Treat VHLO as an implementation detail in compatibility.md

docs/compatibility.md
Making final adjustments to the docs to make sure that they clearly state how to obtain portable artifacts.
=> Update compatibility.md with a link to the VHLO cookbook

build_tools/github_actions/lint_whitespace_checks.sh
1. Pass if file list to lint is empty.
2. Enforce extension checking at end of file (was checking .mlir.bc files)
Given the pipe into bash using $0:
```
get_source_files | xargs -L1 bash -c 'test "$(tail -c 1 "$0")"
```
This requires the output of get_source_files to be non-empty. Added a `-z` check before calling this command. This is odd, but I can't find a better way to go about this check.
=> Two minor bugs fixes in lint whitespace check

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_power.mlir
closes #981 
```
(I1) lhs is a tensor of integer, floating-point, or complex type.
(I2) rhs is a tensor of integer, floating-point, or complex type.
(C1) lhs, rhs, and result have the same type.
```
```
(I1) lhs is not a tensor of integer, floating-point, or complex type. (covered by ODS)
(I2) rhs is not a tensor of integer, floating-point, or complex type. (covered by ODS)
(C1) lhs, rhs, and result do not have the same type. (covered by ODS)
```
=> Add interpreter for PowOp

README.md, build_tools/build_mlir.sh, stablehlo/testdata/CMakeLists.txt, stablehlo/testdata/lit.cfg.py, stablehlo/tests/CMakeLists.txt, stablehlo/tests/lit.cfg.py
I've tried to follow our build instructions on my personal macbook to see how smooth the experience is and how onerous it is to run the testdata/ suite on a reasonably mainstream machine.
Turns out that our instructions don't really work on macOS, and predictably checking the entire testdata/ takes a considerable amount of time (20+ seconds on a 2021 M1 Pro macbook).
This PR fixes the build instructions to work on macOS and updates the CMake target called out in the readme to only check the tests/ suite.
=> Improve newcomer experience

stablehlo/dialect/Serialization.cpp
Found during integrate, we don't have a bazel dependency for this include file because it is unused.
=> Remove unnecessary include

stablehlo/reference/Element.cpp
Just `0l` is ambiguous between multiple Element::Element constructors, including the ones that take int64_t, double and bool.
=> Fix compilation error on macOS

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/transforms/StablehloRefineShapes.cpp
This is a follow up PR to #1019 that partially addresses the proposal in #1000 and #1028. This PR enables ConvolutionOp to share PadOp's shape inference code.
=> Update signature of `inferPadOp` function for re-usability

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/transforms/StablehloRefineShapes.cpp
This is a follow up PR to #1019 that partially addresses the proposal in #1000 and #1028. This PR enables ConvolutionOp to 
use its shape inference code in the interpreter as well. The signature of `verifyConvolutionOp` is also updated as well.
=> Update signature of `inferConvolutionOp` function for re-usability

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
This is a follow up PR to #1019 that partially addresses the proposal in #1000 and #1028. This PR enables ConvolutionOp to share ReverseOp's shape inference code.
=> Update signature of `inferReverseOp` function for re-usability

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_logistic.mlir
```
(I1) operand is a tensor of floating-point or complex type. (Covered by ODS).
(C1) `operand` and `result` have the same type. (Covered by ODS).
```
No additional tests are needed as all constraints and shape inference is covered by ODS.
closes #978
=> Add interpreter for LogisticOp

docs/reference_checklist.md
The example is updated to explicitly show standard format discussed in the first bullet point under "**In `StablehloOps.td`**" section.
=> Update reference checklist example

stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_sparse.mlir, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/stablehlo_refine_shapes.mlir
Before:
```
%0 = "stablehlo.dot_general"(%arg0, %arg1) {
dot_dimension_numbers = #stablehlo.dot<
lhs_batching_dimensions = [0],
lhs_contracting_dimensions = [2],
rhs_batching_dimensions = [0],
rhs_contracting_dimensions = [1]
>
} : (tensor<2x2x2xi8>, tensor<2x2x3xi8>) -> tensor<2x2x3xi32>
```
After:
```
%0 = stablehlo.dot_general %arg0, %arg1,
batching_dims = [0] x [0], contracting_dims = [2] x [1]
: (tensor<2x2x2xi8>, tensor<2x2x3xi8>) -> tensor<2x2x3xi32>
```
The batching_dims part is optional and can be dropped if the corresponding dims are empty.
=> Implement prettyprinting for dot_general

README.md
Following https://github.com/openxla/community/commit/62833d737ed5fc6756e0cc1b10aa44d9979b5790, this PR replaces the link to GitHub Discussions with a link to openxla-discuss@.
=> Retire the link to GitHub Discussions

rfcs/20220912-compatibility.md
Looks like one of our RFCs has formatting which is not compliant with our linters. This PR fixes that.
=> Fix formatting in the rfcs/ directory

docs/spec.md
Today I realized that all "Consider removing" tickets are actually Frontend Contract tickets, not New Features. If we don't clean them up now in preparation for StableHLO v1.0, we will have to support them for a long long time.
The outcome of some of these tickets might actually be "we considered removing this feature because it has problems, but it's actually in use so we'd need to introduce a new feature to replace it", but we still need to get them through the Frontend Contract phase.
This PR updates the spec to call out these tickets. Also, it cleans up mentions of Specification Compliance tickets because those belong in the StableHLO dialect (there can be multiple implementations of the spec, so we shouldn't be preferring one of them in the spec by linking to its tickets).
=> Link recently added frontend contract tickets in the spec

.github/workflows/buildAndTestCMake.yml, .github/workflows/buildBazel.yml, .github/workflows/lint.yml, .github/workflows/markdown_lint.yml
I was looking to fix the long-standing issue with checks being skipped by paths/paths-ignore, leading to: 1) spuriously blocked merges if the checks are required, 2) weird "in progress" dots next to PRs.
I discovered that there is no easy solution to this, but there is a workaround: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks.
This solution works, but it's quite fiddly. Defining a shadow workflow, making sure that its paths/paths-ignore are an exact negation of the real workflow - this got old pretty fast.
Then I realized that we don't have to suffer through this. We can just enable all our workflows on all pull requests. Now …
=> Streamline the on: part of all GitHub workflows

BUILD.bazel
Our BUILD.bazel file has diverged from the downstream build file a little bit, and this PR gets them back in sync again.
=> Synchronize our BUILD.bazel with downstream build

docs/reference_checklist.md
The checklist is updated to enable additional tests in the `testdata` directory now that we have them to use extensively.
=> Update interpreter checklist

stablehlo/dialect/TypeInference.h, stablehlo/transforms/StablehloRefineShapes.cpp
The TypeInference signatures mismatch - not sure why they work in our CI, but fail during integ.
```
//.h
LogicalResult verifyConvolutionAttributes(
std::optional<Location> location, Value lhs, Value rhs,
// .cpp
LogicalResult verifyConvolutionAttributes(
std::optional<Location> location, Type lhsType, Type rhsType,
```
Refine shapes doesn't handle complex numbers properly, minor update to get their underlying type.
=> Fix issues found during integration testing.

stablehlo/dialect/Serialization.cpp
Since VHLO is an implementation detail of StableHLO, we shouldn't expect users of the API to pre-load the dialect.
Serialization isn't an issue since we list dependent dialects in our conversion passes which get loaded.
=> Load VHLO before deserialization

docs/spec.md
ReduceOp can generate multiple results and that is not reflected in the summary.
=> fix a typo in reduceOp spec

stablehlo/reference/Ops.h
It looks like the decl of evalCompareOp has an extra `compareType` parameter.
=> Fix CompareOp interpreter interface inconsistency

rfcs/20230309-e4m3b11.md
This is a proposal to add a new floating point type to StableHLO, please see rfcs/20230309-e4m3b11.md for more details.
=> [RFC] Add a new type to StableHLO: E4M3B11FNUZ

docs/compatibility.md, rfcs/20220912-compatibility.md
We have recently had the first official release of StableHLO, which fully implemented the compatibility guarantees established by the compatibility RFC accepted in December.
These guarantees ended up being more compelling than we anticipated in the RFC discussions, and there are stakeholders who are interested in using them in production right away. To enable that, we have received a request to bump up the backward compatibility guarantees to 6 months (from 1 month for the 0.x.x series, as established by the original RFC).
I would like to proposes to fulfil this request to further strengthen the practical usefulness of the StableHLO opset, given that the additional maintenance cost looks acceptable (5 extra months of maintaining backward-compatible VHLO ops).
This RFC does not affect the …
=> [RFC] Increase backward compatibility guarantees to 6 months

stablehlo/testdata/acos_shape_complex64_20_20.mlir, stablehlo/testdata/convert_element_type_dtypes_to_dtypes_shape_complex64_100_100__olddtype_complex64_newdtype_bool.mlir, stablehlo/testdata/cummax_dtype_by_fun_shape_complex64_8_9__associative_scan_reductions_axis_0_reverse_False.mlir, stablehlo/testdata/cummax_dtype_by_fun_shape_complex64_8_9__axis_0_reverse_False.mlir, stablehlo/testdata/cummin_dtype_by_fun_shape_complex64_8_9__associative_scan_reductions_axis_0_reverse_False.mlir, stablehlo/testdata/cummin_dtype_by_fun_shape_complex64_8_9__axis_0_reverse_False.mlir, stablehlo/testdata/dynamic_slice_dtypes_a_complex64_3__start_indices__1___limit_indices__2___enablexla_True.mlir, stablehlo/testdata/dynamic_update_slice_dtypes_operand_complex64_3__update_complex64_1__start_indices__1___enable_xla_True.mlir, stablehlo/testdata/eq_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/ge_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/gt_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/le_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/lt_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/max_broadcasting_lhs_complex128_1_20__rhs_complex128_20_20.mlir, stablehlo/testdata/max_broadcasting_lhs_complex128_20_20__rhs_complex128_1_20.mlir, stablehlo/testdata/max_broadcasting_lhs_complex64_1_20__rhs_complex64_20_20.mlir, stablehlo/testdata/max_broadcasting_lhs_complex64_20_20__rhs_complex64_1_20.mlir, stablehlo/testdata/max_dtypes_lhs_complex64_20_20__rhs_complex64_20_20.mlir, stablehlo/testdata/max_inf_nan_complex64.mlir, stablehlo/testdata/min_broadcasting_lhs_complex128_1_20__rhs_complex128_20_20.mlir, stablehlo/testdata/min_broadcasting_lhs_complex128_20_20__rhs_complex128_1_20.mlir, stablehlo/testdata/min_broadcasting_lhs_complex64_1_20__rhs_complex64_20_20.mlir, stablehlo/testdata/min_broadcasting_lhs_complex64_20_20__rhs_complex64_1_20.mlir, stablehlo/testdata/min_dtypes_lhs_complex64_20_20__rhs_complex64_20_20.mlir, stablehlo/testdata/min_inf_nan_complex64.mlir, stablehlo/testdata/ne_dtypes_lhs_complex64___rhs_complex64.mlir, stablehlo/testdata/select_n_dtypes_shapepred_int32_2_3__shapeargs_complex64_2_3.mlir
As part of https://github.com/openxla/stablehlo/issues/1291,
enabling  a few test which should have passed with current state of interpreter, without any change of  precision.
=> Enabling a few passing interpreter tests

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
The way the refine function type algorithm works currently has an assumption that ReturnOp does not have redundant operands. This is not always the case in practice.
Several JAX tests were hitting this issue.
Closes #1350
=> Update function type for return with multiple operands, some repeating

stablehlo/reference/Ops.cpp
This is to make sure that, during compilation, the interfatce-type-checking  for the `evalOp*` function calls in eval function (https://github.com/openxla/stablehlo/blob/311f14ce78c7fe35d304ee91007b58c335cf821e/stablehlo/reference/Ops.cpp#L484) are relying on the declarations in Ops.h. Currently, the checking is happening locally within Ops.cpp as the calls to those `evalOps*` functions are preceded by the corresponding definitions. The problem with the current setup is that a change in declaration Ops.h will go unnoticed, which is what exactly happened in  https://github.com/openxla/stablehlo/pull/1343. The proposed fix will make sure that such inconsistencies can be caught during compilation time.
=> refactor to improve evalOp function type checking

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_count_leading_zeros.mlir
```
(I1) operand is a tensor of integer type.
```
I1 and C1 are covered by the ODS, so no additional tests are added.
closes #1100
=> Add interpreter for ClzOp

rfcs/20230321-fp8_fnuz.md
This is a proposal to add Float8E4M3FNUZ and Float8E5M2FNUZ floating point types to StableHLO.
Feedback welcome, see `rfcs/20230321-fp8_fnuz.md` for more details.
=> [RFC] Add Float8E4M3FNUZ and Float8E5M2FNUZ to StableHLO.

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloRefineShapes.cpp
--stablehlo-canonicalize-dynamism can now drop indices_of_shape_operands once they are no longer needed, similarly to how it transforms dynamic_foo ops to foo ops when operands like output_shape are no longer needed.
To make sure that we only do the transformation on valid IR, I also wrote verification logic for indices_of_shape_operands as well as tests for this logic.
In the future, when we upgrade indices_of_shape_operands from an experiment to a full-fledged StableHLO feature, this logic will be moved to a proper verifier.
=> Drop indices_of_shape_operands once they are no longer needed

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloRefineShapes.cpp
When working on adding support for tuple types to
RefineCustomCallOpPattern, I noticed that some logic in
StablehloRefineShapes.cpp assumes shaped types where we aren't
guaranteed to have shaped types and casts to ShapedType at will.
1) This led me to audit our uses of casts to ShapedType, and during that
audit I realized that many of these casts are not needed because in
many cases TableGen generates TypedValue accessors for stuff like
`::mlir::TypedValue<::mlir::TensorType> getLhs()`. This simplified
the code quite a bit.
2) Furthermore, I realized that in some places in our code we use
TensorType, so I audited casts to TensorType as well. To simplify
further refactorings, I figured that we could standardize on just one
kind of type between ShapedType and TensorType, and since …
=> Audit casts to ShapedType and TensorType

rfcs/20230210-sparsity.md, rfcs/20230309-e4m3b11.md, rfcs/20230321-fp8_fnuz.md
This adds status headers to all RFCs under rfcs/ to document their timeline and status.
=> Document RFC status

docs/spec.md
StableHLO dialect currently supports quantization via:
1) Supporting `quant.uniform` element types.
2) Having dedicated ops like `uniform_quantize` / `uniform_dequantize`.
3) Allowing regular ops like `add` / `convolution` to take quantized tensors.
This support was inherited from MHLO when StableHLO was bootstrapped, and
MHLO support was motivated by mobile use cases and inherited from TFLite.
As pointed out in #1149, StableHLO specification doesn't support quantization
at the moment, and this is an important gap that we would like to fix before
StableHLO v1.0 (see #588).
To continue the discussion started in #1149 and to make progress towards v1.0,
this pull request:
A) Adds QuantizedType to the StableHLO specification, modelled after
[TFLite quantization …
=> Introduce QuantizedType

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/acos_shape_bfloat16_20_20.mlir, stablehlo/testdata/acos_shape_float16_20_20.mlir, stablehlo/testdata/acos_shape_float32_20_20.mlir, stablehlo/testdata/asin_shape_bfloat16_20_20.mlir, stablehlo/testdata/asin_shape_float16_20_20.mlir, stablehlo/testdata/asin_shape_float32_20_20.mlir, stablehlo/testdata/atan2_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir, stablehlo/testdata/atan2_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir, stablehlo/testdata/atan2_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir, stablehlo/testdata/atan2_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir, stablehlo/testdata/atan2_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir, stablehlo/testdata/atan_shape_bfloat16_20_20.mlir, stablehlo/testdata/atan_shape_float16_20_20.mlir, stablehlo/testdata/atan_shape_float32_20_20.mlir, stablehlo/tests/interpret_atan2.mlir
```
(I1) `lhs` is a tensor of floating-point or complex type.
(I2) `rhs` is a tensor of floating-point or complex type.
(C1) `lhs`, `rhs`, and `result` have the same type.
```
I1, I2, and C1 are covered by the ODS, so no additional tests are added.
closes #1097
=> Add interpreter for Atan2Op

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/sign_shape_bfloat16_20_20.mlir, stablehlo/testdata/sign_shape_complex64_20_20.mlir, stablehlo/testdata/sign_shape_float16_20_20.mlir, stablehlo/testdata/sign_shape_float32_20_20.mlir, stablehlo/testdata/sign_shape_int16_20_20.mlir, stablehlo/testdata/sign_shape_int32_20_20.mlir, stablehlo/testdata/sign_shape_int8_20_20.mlir, stablehlo/testdata/sign_special_0_dtype_bfloat16.mlir, stablehlo/testdata/sign_special_0_dtype_complex64.mlir, stablehlo/testdata/sign_special_0_dtype_float16.mlir, stablehlo/testdata/sign_special_0_dtype_float32.mlir, stablehlo/testdata/sign_special_0_dtype_int16.mlir, stablehlo/testdata/sign_special_0_dtype_int32.mlir, stablehlo/testdata/sign_special_0_dtype_int8.mlir, stablehlo/tests/interpret_sign.mlir
closes #1115 
```
(I1) operand is a tensor of signed integer, floating-point, or complex type.
(C1) operand and result have the same type.
```
```
I1: a) operand is not a tensor of signed integer, floating-point, or complex type. (Covered by ODS).
C1: a) type(operand) != type(result). (Covered by ODS).
```
=> Add interpreter for SignOp.

docs/spec.md, stablehlo/reference/Element.cpp, stablehlo/testdata/sign_special_0_dtype_complex64.mlir, stablehlo/tests/interpret_sign.mlir
Inspired by #1382, this PR: 1) reduces nesting, 2) drops the final ifs from the is_integer and is_float code blocks, 3) makes it clear that the NaN case for complex numbers returns NaN for both real and imaginary components.
=> Streamline the pseudocode describing SignOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/round_rounding_methods_shape_float32_2_5__roundingmethod_1.mlir, stablehlo/tests/interpret_round_nearest_even.mlir
Here are the constraints for the RoundNearestEvenOp:
```
(I1) operand is a tensor of floating-point type.
```
I1 and C1 are covered by the ODS, so no additional tests are added.
closes #1111
=> Add interpreter for RoundNearestEvenOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/round_dtypes_shape_bfloat16_100_100__roundingmethod_0.mlir, stablehlo/testdata/round_dtypes_shape_float16_100_100__roundingmethod_0.mlir, stablehlo/testdata/round_dtypes_shape_float32_100_100__roundingmethod_0.mlir, stablehlo/testdata/round_rounding_methods_shape_float32_2_5__roundingmethod_0.mlir, stablehlo/tests/interpret_round_nearest_afz.mlir
Here are the constraints for the RoundOp:
```
(I1) operand is a tensor of floating-point type.
```
I1 and C1 are covered by the ODS, so no additional tests are added.
closes #1110
=> Add interpreter for RoundOp

stablehlo/tests/interpret_power.mlir
As identified from the lcov coverage report, added a test to cover the following lines
```
// When the exponent is negative
if (base.abs().isOne())
exponent = exponent.abs();
```
from the interpreter implementation of power op.
=> Add missing coverage tests for power

build_tools/github_actions/lint_llvm_commit.sh
Had to run the script twice to update SHA because it was using the old commit value to calculate the hash
=> Fix llvm commit lint script to use new commit for SHA

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/shift_left_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir, stablehlo/testdata/shift_left_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_left_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir, stablehlo/testdata/shift_left_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir, stablehlo/testdata/shift_left_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir, stablehlo/testdata/shift_left_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir, stablehlo/tests/interpret_shift_left.mlir
Here are the constraints for the ShiftLeftOp:
```
(I1) lhs is a tensor of integer type.
(I2) rhs is a tensor of integer type.
(C1) `lhs`, `rhs`, and `result` have the same type.
```
I1, I2, and C1 are covered by the ODS, so no additional tests are added.
Notes:
* Corner cases (shift overflow) has not been accounted for: #1150
closes #1112
=> Add interpreter for ShiftLeftOp

BUILD.bazel
Needed since `StablehloRefineShapes.cpp` includes `Base.h`:
https://github.com/openxla/stablehlo/blob/main/stablehlo/transforms/StablehloRefineShapes.cpp#L45
=> Add missing dependency causing issues in google infra

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_get_dimension_size.mlir, stablehlo/tests/ops_stablehlo.mlir
Here are the constraints for the GetDimensionSizeOp:
```
(I1) operand is a tensor.
(I2) dimension is a constant of type `si64`.
(C1) 0 <= dimension < rank(operand).
```
```
I1: a) operand is not a tensor. (Covered by ODS).
I2: a) dimension is not a constant of type `si64`. (Covered by ODS).
C1: a) 0 < dimension.
b) dimension < rank(operand).
```
```
C1a: 0 < dimension.
C1b: dimension < rank(operand).
```
closes #1432
=> Add interpreter for GetDimensionSizeOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/shift_right_logical_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir, stablehlo/testdata/shift_right_logical_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_right_logical_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir, stablehlo/testdata/shift_right_logical_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir, stablehlo/testdata/shift_right_logical_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir, stablehlo/testdata/shift_right_logical_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir, stablehlo/tests/interpret_shift_right_logical.mlir
Here are the constraints for the ShiftRightLogicalOp:
```
(I1) lhs is a tensor of integer type.
(I2) rhs is a tensor of integer type.
(C1) `lhs`, `rhs`, and `result` have the same type.
```
I1, I2, and C1 are covered by the ODS, so no additional tests are added.
Notes:
* Corner cases (shift overflow) has not been accounted for: #1150
closes #1114
=> Add interpreter for ShiftRightLogicalOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int16_20_20__rhs_int16_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int32_20_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_int8_20_20__rhs_int8_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint16_20_20__rhs_uint16_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint32_20_20__rhs_uint32_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_dtypes_lhs_uint8_20_20__rhs_uint8_20_20.mlir, stablehlo/tests/interpret_shift_right_arithmetic.mlir
Here are the constraints for the ShiftRightArithmeticOp:
```
(I1) lhs is a tensor of integer type.
(I2) rhs is a tensor of integer type.
(C1) `lhs`, `rhs`, and `result` have the same type.
```
I1, I2, and C1 are covered by the ODS, so no additional tests are added.
Notes:
* Corner cases (shift overflow) has not been accounted for: #1150
closes #1113
=> Add interpreter for ShiftRightArithmeticOp

stablehlo/dialect/Version.h, stablehlo/integrations/python/tests/stablehlo.py
After a StableHLO release is integrated into OpenXLA ([openxla/xla](https://github.com/openxla/xla/tree/main/third_party/stablehlo)), bump the patch version so HEAD remains ahead of the latest release.
=> Bump patch to 0.10.1 after integrate

stablehlo/dialect/Version.h
After a StableHLO release is integrated into OpenXLA ([openxla/xla](https://github.com/openxla/xla/tree/main/third_party/stablehlo)), we bump the patch version so HEAD remains ahead of the latest release.
=> Bump patch version 0.10.1 -> 0.10.2

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloRefineShapes.cpp
At the moment, indices_of_shape_operands are in 1:1 correspondence with
result types, but that doesn't work when custom calls return tuples.
This pull requests addresses this problem, and changes
indices_of_shape_operands to be in 1:1 correspondence with flattened
result types. Originally, I thought that I'd need to redesign
indices_of_shape_operands, e.g. carry arrays of 1-dimensional tensors or
arrays of strings, but this solution keeps the existing structure of
the attribute, i.e. a 1-dimensional tensor of i64.
The changes are surprisingly compact and cover the following three
areas of the implementation:
1) Verification logic for the attribute that lives in
getShapeRefinements in Base.h.
2) Helper logic which applies refinements to operation types
that lives in refineReturnTypes in …
=> Extend indices_of_shape_operands to work for tuple types

stablehlo/transforms/StablehloRefineShapes.cpp
NOTE: This pull request is based on https://github.com/openxla/stablehlo/pull/1387.
While working on refineReturnTypes, I made some improvements to
how the application of ShapedTypeComponents to Type happens.
This is mostly an NFC that restructures the code to improve readability
and logging.
=> Improve logging in refineReturnTypes

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/cbrt_shape_bfloat16_20_20.mlir, stablehlo/testdata/cbrt_shape_float32_20_20.mlir, stablehlo/tests/interpret_cbrt.mlir
Here are the constraints for CbrtOp:
```
```
I1 and C1 are covered by the ODS, so no additional tests are added.
Notes:
* The implementation is inspired from De Moivre's formula to calculate nth root of a complex number. k is assumed 0 for principal root. See: https://en.wikipedia.org/wiki/De_Moivre%27s_formula
closes #1099
=> Add interpreter for CbrtOp

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloRefineShapes.cpp
As I was cleaning up the uses of matchInts, I figured I'd do the long-standing refactoring to switch to using APSInt.
This had the benefit of simplifying partial evaluation logic in --stablehlo-refine-shapes because with APSInts we no longer need to branch on whether the underlying APInts are signed or unsigned.
=> Refactor matchInts to use APSInt instead of APInt

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/atanh_shape_bfloat16_20_20.mlir, stablehlo/testdata/atanh_shape_float32_20_20.mlir, stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__associative_scan_reductions_axis_1_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__axis_0_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_axis_by_fun_shape_float32_8_9__axis_1_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float16_8_9__associative_scan_reductions_axis_0_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_dtype_by_fun_shape_float32_8_9__axis_0_reverse_False.mlir, stablehlo/testdata/cumlogsumexp_reverse_shape_float32_8_9__associative_scan_reductions_axis_0_reverse_True.mlir, stablehlo/testdata/cumlogsumexp_reverse_shape_float32_8_9__axis_0_reverse_True.mlir, stablehlo/testdata/digamma_shape_float32_20_20.mlir, stablehlo/testdata/erf_inv_shape_float32_20_20.mlir, stablehlo/testdata/lgamma_shape_float32_20_20.mlir, stablehlo/testdata/log1p_shape_bfloat16_20_20.mlir, stablehlo/testdata/log1p_shape_complex64_20_20.mlir, stablehlo/testdata/log1p_shape_float16_20_20.mlir, stablehlo/testdata/log1p_shape_float32_20_20.mlir, stablehlo/tests/interpret_log_plus_one.mlir
closes #1105 
```
(C1) operand and result have the same type.
```
```
I1: a) operand is not a tensor of floating-point or complex type. (Covered by ODS).
C1: a) type(operand) != type(result). (Covered by ODS).
```
=> Add interpreter for Log1pOp.

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/complex_broadcast_lhs_float32_3_1__rhs_float32_3_2.mlir, stablehlo/testdata/complex_broadcast_lhs_float32_3_2__rhs_float32_3_1.mlir, stablehlo/testdata/complex_dtypes_lhs_float32_3_4__rhs_float32_3_4.mlir, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_complex.mlir, stablehlo/tests/ops_stablehlo.mlir
Closes #1101 .
```
(I1) lhs is a tensor of 32 bit floating-point or 64 bit floating-point.
(I2) rhs is a tensor of 32 bit floating-point or 64 bit floating-point.
(C1) lhs and rhs have the same type.
(C2) result and lhs have the same shape.
(C3) the return type should be a complex type of the element type of the lhs i.e. element_type(`result`) = complex_type(element_type(`lhs`)).
```
```
I1: lhs is not a tensor of 32 bit floating-point or 64 bit floating-point. (ODS)
I2: rhs is not a tensor of 32 bit floating-point or 64 bit floating-point. (ODS)
C1: type(lhs) != type(rhs).
C2: shape(result) != shape(lhs).
C3: element_type(`result`) != complex_type(element_type(`lhs`)). (ODS)
```
=> Add interpreter for ComplexOp.

stablehlo/testdata/asinh_shape_bfloat16_20_20.mlir, stablehlo/testdata/asinh_shape_float32_20_20.mlir, stablehlo/testdata/atanh_shape_complex64_20_20.mlir, stablehlo/testdata/conj_dtypes_operand_complex64_3_4__kwargs.mlir, stablehlo/testdata/conj_dtypes_operand_float32_3_4__kwargs.mlir, stablehlo/testdata/conj_kwargs_operand_float32_3_4__kwargs____input_dtype___class_numpy_float32.mlir, stablehlo/testdata/shift_right_arithmetic_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_right_arithmetic_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir, stablehlo/testdata/shift_right_logical_broadcasting_lhs_int32_1_20__rhs_int32_20_20.mlir, stablehlo/testdata/shift_right_logical_broadcasting_lhs_int32_20_20__rhs_int32_1_20.mlir, stablehlo/testdata/sinh_shape_float32_20_20.mlir
Tests can slip through if a test contains more than one op from the PR queue and one PR is merged while the other PR does not check for enabling additional tests after rebase.
=> Enable passing interpreter tests

stablehlo/dialect/Base.td, stablehlo/reference/Tensor.cpp, stablehlo/reference/Types.cpp, stablehlo/tests/interpret_constant.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir
Migrating changes made in https://github.com/tensorflow/mlir-hlo/commit/ed8f354a68855753128e60e40c88b54af1fef6f5.
closes #1454
Reintroducing PR from #1459 as it was closed prematurely.
=> Add missing checks/tests for supported f8 types

docs/spec.md
The PR proposes the specification for quantized add op.
At some point we [decided](https://github.com/openxla/stablehlo/pull/1352#discussion_r1166196224) to drop the introduction of the specification of this op mainly because we were unsure about the fate of https://github.com/openxla/stablehlo/issues/1406.
Please have a look at my revised proposal on https://github.com/openxla/stablehlo/issues/1406 and let me know if I am missing something. Otherwise, let us review this op  and let me know your feedback.   
Side note: For those who are already aware of the context of prior introduction of this op, please note that the current proposal is almost same as before except that it does not have any additional constraint imposed by the op's semantics on `storage_min` or `storage_max`.
=> Specification for quantized  AddOp

BUILD.bazel, stablehlo/api/CMakeLists.txt, stablehlo/api/PortableApi.cpp, stablehlo/api/PortableApi.h, stablehlo/dialect/Serialization.cpp, stablehlo/dialect/Serialization.h, stablehlo/dialect/Version.h, stablehlo/integrations/python/CMakeLists.txt, stablehlo/integrations/python/PortableApi.cpp, stablehlo/integrations/python/PortableApi.h, stablehlo/integrations/python/StablehloModule.cpp
Portable APIs are APIs with signatures that do not depend on MLIR. This provides a way to access some StableHLO APIs without needing an MLIR dependency/visibility at the call site.
These APIs also can be safer in cases where shared objects are used, as passing MLIR Context across shared objects can cause problems.
=> Split portable StableHLO APIs into separate file

stablehlo/api/PortableApi.cpp, stablehlo/api/PortableApi.h, stablehlo/integrations/python/PortableApi.cpp, stablehlo/integrations/python/tests/stablehlo.py
This is based on https://github.com/openxla/stablehlo/pull/1480
=> Add API to get minimum supported StableHLO version

BUILD.bazel, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/integrations/python/tests/stablehlo.py, stablehlo/reference/CMakeLists.txt, stablehlo/reference/Ops.cpp, stablehlo/reference/Tensor.cpp
* BUILD.bazel & CMakeLists.txt: add a missing dependency.
* stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Tensor.h: fix clang-tidy warnings.
* stablehlo/integrations/python/tests/stablehlo.py: fix formatting.
=> Fix issues identified during integrate

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Sizes.h, stablehlo/tests/interpret_cholesky.mlir, stablehlo/tests/ops_stablehlo.mlir
Here are the constraints for CholeskyOp:
```
(I1) `a` is a tensor of floating-point or complex type.
(I2) `lower` is a tensor constant of `i1` type.
(C1) `a` and `result` have the same type.
(C2) rank(`a`) >= 2.
(C3) dim(`a`, -2) = dim(`a`, -1).
```
```
I1: a) `a` is not a tensor of floating-point type or complex type. (Covered by ODS).
I2: a) `lower` is not a tensor constant of `i1` type. (Covered by ODS).
C1: a) type(a) != type(result).
C2: a) rank(a) < 2.
C3: a) dim(`a`, -2) != dim(`a`, -1).
```
```
C1a: type(a) != type(result).
C2a: rank(a) < 2.
C3a: dim(`a`, -2) != dim(`a`, -1).
```
Notes:
* Implementation inspired by the …
=> Add interpreter for CholeskyOp

docs/compatibility.md
1\) With the addition of new content, the "Out of scope" section seemed a bit out of place, so I moved it to the bottom of the document.
2\) Shortened "Creating portable artifacts" to "APIs" and applied further shortenings to subordinate sections.
3\) Consistently referred to these APIs as "compatibility APIs" since we are in a document called compatibility.md.
=> Slightly reword compatibility.md

CMakeLists.txt, build_tools/github_actions/ci_build_cmake.sh, build_tools/github_actions/ci_build_cmake_code_coverage.sh, stablehlo/conversions/tosa/tests/CMakeLists.txt, stablehlo/conversions/tosa/tests/binary.mlir, stablehlo/conversions/tosa/tests/lit.cfg.py, stablehlo/conversions/tosa/tests/nullary.mlir, stablehlo/conversions/tosa/tests/ternary.mlir, stablehlo/conversions/tosa/tests/unary.mlir, stablehlo/integrations/python/tests/CMakeLists.txt, stablehlo/testdata/CMakeLists.txt, stablehlo/tests/CMakeLists.txt
In #1466, we ran into some issues when adding the newly introduced tosa/ suite to relevant test targets, so this PR revamps this system to properly integrate tosa/ as well as simplify similar work in the future.
Instead of the state of the art with one `check-stablehlo` custom target and a bunch of suites becoming its dependencies, we now have three custom targets:
1) check-stablehlo-ci whose name makes it clear that this is what
runs in CI.
2) check-stablehlo-slow for slow-running tests like the testdata/
suite that we'd like to separate from the other suites, so that
humans don't have to run them every time.
3) check-stablehlo-quick for everything else.
Each suite becomes a dependency of either -slow or -quick, making its nature explicit and clearly documented.
Also, it looks like the …
=> Incorporate tosa/ tests into our test infrastructure

stablehlo/dialect/Version.h
Our integrate process involves bumping Version.h on GitHub after a successful landing of an downstream integrate. This is done to make sure that the subsequent downstream integrate is guaranteed to receive a different version, so that we can tell them apart down the line.
Unfortunately, I forgot to do that after the previous downstream integrate: https://github.com/tensorflow/mlir-hlo/commit/e46e2b655d70a9099acd47be940ca3c0973583a2 which had its Version.h say 0.11.4.
Now we have another downstream integrate that has just landed: https://github.com/tensorflow/mlir-hlo/commit/a1cd423b7ae9cf9f48cd21494756d85d04e97411, and it has the same version as its predecessor (its Version.h also says 0.11.4). This is exactly what the integrate process was trying to avoid.
To untangle this, I propose …
=> Belatedly bump patch version after integrate 0.11.4 -> 0.11.5

stablehlo/dialect/Version.h
This PR concludes this weeks integrates, which were a bit messed up because of my oversight. #1506 explains what happened and provides a fix, and this PR is the final step towards normalcy.
=> Bump patch version after integrate 0.11.5 -> 0.11.6

stablehlo/api/PortableApi.cpp, stablehlo/dialect/Serialization.cpp
https://reviews.llvm.org/D149515 has just landed, so we must explicitly specify bytecodeVersion when using BytecodeWriter to avoid breaking forward compatibility guarantees.
More specifically, we want to avoid a situation where:
1) A StableHLO producer using a post-D149515 version of LLVM
serializes a StableHLO program to bytecode. (This will use
bytecodeVersion = 2 by default).
2) A StableHLO consumer using a pre-D149515 version of LLVM within
the 1 month StableHLO forward compatibility window cannot
deserialize the StableHLO program.
We don't have forward compatibility tests yet, so this PR doesn't have tests either. See #1498 for an RFC for forward compatibility testing.
=> Use bytecodeVersion = 1 when serializing MLIR bytecode

stablehlo/api/PortableApi.cpp, stablehlo/dialect/Serialization.cpp
#1511 introduced BytecodeWriterConfig to our serialization logic,
but I forgot to actually use it. This PR fixes this oversight.
This mistake on my part happened because we don't have forward compatibility tests yet. To make sure that I didn't mess up anything else this time, I have manually verified the following:
* At HEAD, build/bin/stablehlo-translate --serialize produces different payloads when: 1) local clone of llvm-project is pristine, 2) local clone of llvm-project has kVersion manually changed to 2. The only difference is the bytecodeVersion field in the serialized payloads.
* With this PR, build/bin/stablehlo-translate --serialize produces the same payloads when: 1) local clone of llvm-project is pristine, 2) local clone of llvm-project has kVersion manually changed to 2. As …
=> Actually use the BytecodeWriterConfig in writeBytecodeToFile

stablehlo/tools/StablehloTranslateMain.cpp
Exposes `--strip-debuginfo` as a pass from `stablehlo-translate`. This is currently available in `stablehlo-opt`.
Alternatively, we could use:
```
stablehlo-opt file.mlir --strip-debuginfo --emit-bytecode | stablehlo-translate --serialize --target=X.Y.Z
```
Must use bytecode across the bash pipe, otherwise debug info gets populated with <stdin> values:
```
#loc972 = loc("<stdin>":853:5)
#loc973 = loc("<stdin>":855:3)
#loc975 = loc("<stdin>":856:10)
#loc976 = loc("<stdin>":857:5)
```
=> Add option to stablehlo-translate to generate bytecode without debug info

docs/compatibility.md
Now that we have these APIs documented right in this file, let's link directly to it.
=> Update the link to serialization APIs in compatibility.md

stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir
Use https://github.com/openxla/stablehlo/pull/1524 as diffbase.
This is a stop-gap measure to improve the detection of forward incompatibilities in the StableHLO repo, and repos where StableHLO is exported like openxla/xla, while the Forward Compatibility Testing RFC (https://github.com/openxla/stablehlo/pull/1498) is reviewed. These tests will be reworked based on the outcome of the RFC review.
The forward compatibility test is a byte-wise comparison using:
```bash
diff %s.bc <(stablehlo-translate --serialize --target=0.10.0 --strip-debuginfo %s)
```
=> Add stop-gap static forward compatibility tests

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td
We already have an implementation to handle custom_call ops by passing a fallback function to handle them. This PR updates the status to reflect that. Other minor change include updating the example in td file to use pretty-print format following the [guide](https://github.com/openxla/stablehlo/blob/main/docs/reference.md#testing-guidelines).
=> Update CustomCallOp status to `yes` and update ODS

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp
This PR introduces `Element convert(Type type, const Element &e)` which considerably simplifies `evalConvertOp` by hiding type-based dispatch in Element.h, consistently with many other implementations of evalFooOp functions.
=> Simplify evalConvertOp

BUILD.bazel, docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/CMakeLists.txt, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_batch_norm_training.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand`: tensor of floating-point type.
(I2) `scale`: 1-dimensional tensor of floating-point type.
(I3) `offset`: 1-dimensional tensor of floating-point type.
(I4) `epsilon`: constant of type `f32`.
(I5) `feature_index`: constant of type `si64`.
(C1) 0 <= `feature_index` < rank(`operand`).
(C2) `operand`, `scale`, `offset`, `result`, `batch_mean` and `batch_var`
have the same element type.
(C3) size(`scale`) = `dim(operand, feature_index)`.
(C4) size(`offset`) = `dim(operand, feature_index)`.
(C5) size(`batch_mean`) = `dim(operand, feature_index)`.
(C6) size(`batch_var`) = `dim(operand, feature_index)`.
(C7) `operand` and `output` have the same type.
```
``` …
```
=> Add interpreter for BatchNormTrainingOp

stablehlo/api/PortableApi.h
During review of https://github.com/google/jax/pull/16081, we received feedback that the name `get_minimum_version` is not very intuitive.
While we haven't yet come up with a better name, improving documentation is the second best thing that we can do.
=> Improve documentation for getMinimumVersion

BUILD.bazel, stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_chlo.mlir
This is needed to support the work on introducing mhlo::TopKOp. MLIR-HLO commit: https://github.com/tensorflow/mlir-hlo/commit/4651ac2e8375b706643fdab809e0bc30a7ecd666
=> Move chlo::TopKOp type inference into TypeInference.h

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_batch_norm_grad.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand`: tensor of floating-point type.
(I2) `scale`: 1-dimensional tensor of floating-point type.
(I3) `mean`: 1-dimensional tensor of floating-point type.
(I4) `variance`: 1-dimensional tensor of floating-point type.
(I5) `grad_output`: tensor of floating-point type.
(I6) `epsilon`: constant of type `f32`.
(I7) `feature_index`: constant of type `si64`.
(C1) 0 <= `feature_index` < rank(`operand`).
(C2) `operand`, `scale`, `mean`, `variance`, `grad_output`, `grad_operand`
`grad_scale` and `grad_offset` have the same element type.
(C3) `operand`, `grad_output` and `grad_operand` have the same shape.
(C4) `scale`, `mean`, `variance`, `grad_scale` and `grad_offset` have the
same shape.
(C5) size(`scale`) = `dim(operand, …
```
=> Add interpreter for BatchNormGradOp

docs/spec.md
The stablehlo.func and stablehlo.return syntax in the opening example of the spec was aspirational, and at the time we expected that we'll soon adopt it.
A lot of the time has passed, and we still haven't gotten around to doing this, while we've been getting regular questions about this. Let's reflect reality in the example for now - we can always change it back once we address #425.
=> Use func.func and func.return in the spec

stablehlo/reference/Ops.cpp
This PR drops checking that evaluating WhileOp::cond produces exactly one result. This is guaranteed by the verifier, so this is not something that we should be checking in the interpreter.
=> Simplify evalWhileOp

stablehlo/tests/interpret_gather.mlir
In the removed test, one of the start_indices is 10 which is out of bounds for the operand, and that's currently specced as implementation-defined. Per interpreter checklist, we should remove this test.
=> Remove an implementation-defined test for GatherOp

docs/vhlo.md
We have slightly different tests in `stablehlo_legalize_to_vhlo.0_X_0.mlir` and `stablehlo_legalize_to_vhlo.mlir`, so this provides extra clarity on what the run lines should be.
This was noticed by @ghpvnist.
=> Update vhlo.md to include specific RUN lines for testing

stablehlo/dialect/Version.h
Integrated commit: https://github.com/openxla/xla/commit/767423c2c190ce25ece07a7ea4367263f2d6d6e9
=> Bump patch version after integrate 0.13.0 -> 0.13.1

docs/spec.md, stablehlo/reference/Ops.cpp, stablehlo/reference/Sizes.cpp, stablehlo/reference/Sizes.h
Data Movement operations were one of the first operations specced, so we were still working out the notation back then.
As mentioned in #484, inspired by our experience with the interpreter, it appears to be useful to express semantics of these operations in terms of result_index / operand_index rather than in terms of individual components of those indices.
I took a stab at tweaking the specification for these operations, and I think that going from scalars to tensors to represent indices results in more readable specification. Furthermore, descriptive names like result_index are more conducive to readability than i or j. Also, we can retire the somewhat weird "id" / "jd" notation for these ops.
Overall, I think that the specification and the implementation of data movement ops are …
=> Align the notation of spec and interpreter for Data Movement operations

docs/spec.md
This PR proposes a more consistent notation for spec.md and describes it in the newly introduced "Notation" section. It doesn't address all feedback from #289, and some areas are deliberately left for future work but I think it's already an improvement.
1) Introduces the ellipsis notation, to replace previously inconsistent use of colons in a similar role, to allow writing things like: `dim(lhs, lhs_batching_dimensions...) = dim(rhs, rhs_batching_dimensions...)`.
As a side effect, this also gets rid of most of the `i0`, `i1`, etc, except in two places: a) when we mix scalar indices with colons, e.g. in GatherOp or ScatterOp, b) when we create function types from individual input/output types. In these situations, I believe that scalar indices represent the best tradeoff between …
=> Tighten the formal notation that we're using in the spec

docs/spec.md, stablehlo/reference/Ops.cpp, stablehlo/testdata/reduce_window_add_window_dilation_shape_float32_4_6__initvalue_0_windowdimensions__2_2__windowstride1490052185320441557.mlir, stablehlo/testdata/select_and_gather_add_dilations_shape_float32_4_6__selectprim_le_windowdimensions__2__2__windowstrid-1234442230378059557.mlir, stablehlo/testdata/select_and_gather_add_dilations_shape_float32_4_6__selectprim_le_windowdimensions__2__2__windowstrid4494141771612406334.mlir
The current spec does not use `slice` with the same semantics as what `stablehlo.slice` does. `stablehlo.slice` version of `limit_indices` accounts for dilation and also complies with SliceOp's constraint: `(C3) 0 <= start_indices[d] <= limit_indices[d] <= dim(operand, d) for all dimension d.`
ReduceWindowOp's `limit_indices` calculation does not account for the dilation and (C3), so we need to add dilation (minus 1 since limit_indices is exclusive).
This was discussed previously in the interpreter PR https://github.com/openxla/stablehlo/pull/1336#discussion_r1142826672. We kept the formulation as-is to assume that the program provides correct values, but we may not assume this is the case when we are explicitly constructing the input values.
=> Update spec and interpreter for ReduceWindowOp to properly calculate window_end

rfcs/20230309-compatibility.md, rfcs/images/20230309-compatibility.md
This PR adds "[RFC] Increase backward compatibility guarantees to 6 months" (#1306) to rfcs/ to be consistent with other approved RFCs and preserve it for future reference.
=> Add the 6 months compatibility RFC to rfcs/ for future reference

rfcs/20230321-fp8_fnuz.md
The set bit was in the same place as for the E4M3 type - it should be the same as for Float8E5M2.
=> Correction to Min Normal bitstring for Float8E5M2FNUZ

rfcs/20220912-compatibility.md, rfcs/20221031-fp8.md, rfcs/20230210-sparsity.md, rfcs/20230309-compatibility.md, rfcs/20230309-e4m3b11.md, rfcs/20230321-fp8_fnuz.md, rfcs/20230525-compatibility.md
All RFCs now have a consistent "Discussion thread" header that points to the primary location where the discussion has been happening.
We went through quite a few approaches over the last year (GitHub discussions, GitHub PRs, mailing lists), so I think it's good to make this uniform.
Also, dates in some RFC documents were incorrectly referring to 2022 instead of 2023. I fixed that too.
=> Unify references to discussion threads in RFCs

CMakeLists.txt
This applies when stablehlo is built by other projects enabled as an
external llvm project.
This change makes it match the mlir-hlo configuration more closely:
https://github.com/tensorflow/mlir-hlo/blob/51ce2fa22bc9acff37332ad02ef39412f21ffc98/CMakeLists.txt#L113-L130,
and ease the transition from mlir-hlo to stablehlo:                                                                      
https://discourse.llvm.org/t/sunsetting-the-mlir-hlo-repository/70536.
Tested by embedding stablehlo into IREE.
Issue: https://github.com/openxla/stablehlo/issues/1549
=> [CMake] Make StableHLO build consistent with MLIR-HLO

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td, stablehlo/tests/ops_chlo.mlir
Backport of https://github.com/tensorflow/mlir-hlo/commit/bb7b1eb4565e02a822a754bb536577454ffc64b2
Allows `CHLO::BroadcastAddOp` to support quantized types with compatible differences in representation.
=> [chlo] Add HLO_CompatibleOperandsAndResultElementType to validate quantized types

stablehlo/dialect/VhloAttrs.td, stablehlo/dialect/VhloEnums.td, stablehlo/dialect/VhloOps.td, stablehlo/dialect/VhloTypes.td
`mlir::ConversionTarget::isLegal` call these two functions during StableHLO<->VHLO legalization, causing string version numbers to be repeatedly parsed by `mlir::vhlo::Version::fromString` at runtime. Our performance analysis indicates that such version number parsing can dominate the execution time of legalization pass.
Since version numbers are available to TableGen, this CL uses TableGen functions to parse version numbers at compile time. With this change, `getMinVersion()` and `getMaxVersion()` use `mlir::vhlo::Version(x, y, z)` to avoid string parsing, which greatly improves the performance.
Backport of https://github.com/tensorflow/mlir-hlo/commit/51ce2fa22bc9acff37332ad02ef39412f21ffc98
=> Make getMinVersion() and getMaxVersion() parse version numbers at compile time

docs/spec.md
The PR proposes the specification for quantized convolution op along with the specifications for a few other ops on which the convolution specification depends on, for example, `pad`, `reverse`.
1. Given `q = tensor with uniformed quantized type`, the PR covers the semantics of  static range quantized  `convolution(q, q)`. The specification is very similar to the earlier proposed [quantized dot_general op](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#dot_general).
2. Given, that many ops support both per-tensor and per-axis quantization schemes, it might be redundant to specify for each op the semantics of the computation involved in both the scheme. To avoid that we decided that the op-level semantics will only specify the per-tensor semantics, whereas, semantics of …
=> Specification for quantized ConvolutionOp

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
This complements the already existing EvalMaxOp to support shape computations which involve clamping.
=> Implement EvalMinOp and EvalClampOp in shape refinement

docs/reference_checklist.md, docs/spec_checklist.md
As brought up [here](https://github.com/openxla/stablehlo/pull/1496#discussion_r1230975223) that some parts of the `reference_checklist.md` are relevant enough to be included in the `spec_checklist.md`.
=> Augment the `spec_checklist.md`

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir
fixes #531
fixes #530 
The PR proposes the specification for `uniform.quantize` and `uniform.dequantize` ops. 
The specification of `uniform.quantize` also captures the re-quantization conversions from quantized tensor to quantized tensors. 
Please let me know your feedback. 
We have the following constraints from the spec  
```
(I1)  `operand` is a  quantized tensor
(C1) `shape(operand) = shape(result)`.
(C2) `element_type(result) = expressed_type(operand)`.
```
```
I1: a) `operand: quantized tensors`. (Covered by ODS).
C1: a) `shape(operand) != shape(result)`. (Covered by ODS)
C2: a) `element_type(result) != expressed_type(operand)`.
```
If we drop the "Covered by ODS" pieces, this will leave us with the following …
=>  Specification for UniformQuantizeOp and UniformDequantizeOp

docs/spec.md
As brought up in https://github.com/openxla/stablehlo/pull/1567#discussion_r1217167342, there is a need to introduce a computation function, with name `element_type`, which can be applied for both `TensorElementType` and `QuantizedTensorElementType` in order to simplify the operation specification.
The PR does the following:
1. Rename `ElementType` to `TensorElementType`. 
2. Rename `QuantizedElementType` to `QuantizedTensorElementType`.
3. Introduction a quantization computation function `element_type`.
4. Use the function at (3) for `convolution` and `pad`.
=> Refactor the grammar for element types

stablehlo/tools/StablehloLspServerMain.cpp
Follows up on #1620 to consistently follow the convention that we're using in the codebase.
=> Add license header to StablehloLspServerMain.cpp

stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_0_enable_xla_True_mode_fill.mlir, stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_1_enable_xla_True_mode_fill.mlir, stablehlo/testdata/gather_from_take_indices_name__5_oob__axis_2_enable_xla_True_mode_fill.mlir, stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_0_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__6_neg__axis_1_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_0_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__7_neg__axis_1_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_0_enable_xla_True_mode_fill.mlir, stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_clip.mlir, stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_1_enable_xla_True_mode_fill.mlir, stablehlo/testdata/gather_from_take_indices_name__8_neg_oob__axis_2_enable_xla_True_mode_fill.mlir
This PR disables `gather` related tests enabled by a script prematurely as part of #1597 (these were conditionally passing at the time of merge). They would be reenabled by #1541 which correctly passes these tests.
=> Disable OOB gather tests

.github/workflows/buildAndTestCMake.yml
Felt inspired after seeing a presentation on JAX CI in [openxla/openxla-pjrt-plugin](https://github.com/openxla/openxla-pjrt-plugin) (like [run_jaxtests_cpu.yml](https://github.com/openxla/openxla-pjrt-plugin/blob/main/.github/workflows/run_jaxtests_cpu.yml)), decided to add some frequent (every 6hr) builds against the latest LLVM revision to detect compatibility / other issues as soon as possible.
This is built on top of existing CI. The name of the buildAndTestCmake job now includes what StableHLO is being built against. Examples from my fork:
- [cmake-build (llvm-project@HEAD)](https://github.com/GleasonK/stablehlo/actions/runs/5136120754/jobs/9242454311)
- [cmake-build (llvm_version.txt)](https://github.com/GleasonK/stablehlo/actions/runs/5136234330/jobs/9242713655)
_Note: This only …
=> Add scheduled CI for StableHLO builds against LLVM@HEAD

docs/compatibility.md
This follows up on #1606, further removing the traces of the compatibility policy that got updated in a recent compatibility RFC.
=> Sharpen wording in compatibility.md

docs/spec.md
As recommended in https://github.com/openxla/stablehlo/pull/1566/files/13a2c8b6e518d611fb7bd0747096392478291eef#r1237644676, the constraint in `bitcast_convert` is revised to make sure that the `num_bits(E) % num_bits(E') == 0` when `num_bits(E') < num_bits(E)` and `num_bits(E') % num_bits(E) == 0` when  `num_bits(E) < num_bits(E')`. 
Note that this does not need a change in existing verification and testing as the the verifier for `bitcast_convert` is doing the exact [check](https://github.com/openxla/stablehlo/blob/d8f0c12e2a7541cfe6ba3a04c8a2fb350bdab43d/stablehlo/dialect/TypeInference.cpp#L3174) as proposed in the PR.
=> Fix a constraint in `bitcast_convert` op

CMakeLists.txt
To follow up on #1612, this PR further aligns StableHLO and MLIR-HLO builds to facilitate the transition from mlir-hlo to stablehlo.
Changes in this PR:
1) Adds Ccache support.
2) Adds support for LLVM_ENABLE_ZLIB.
3) Removes STABLEHLO_STANDALONE_BUILD, to better align with MLIR-HLO
terminology.
Deltas between CMakeLists.txt in this PR and CMakeLists.txt in MLIR-HLO:
a) Says "StableHLO" instead of "MHLO".
b) Supports STABLEHLO_ENABLE_STRICT_BUILD (there is no equivalent
in the MLIR-HLO build).
c) Doesn't support ${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules yet,
as well as some MLIR_HLO_FOO_DIR variables needed for that.
(We have #1549 to follow up on this).
=> Further align StableHLO and MLIR-HLO builds

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_optimization_barrier.mlir, stablehlo/tests/ops_stablehlo.mlir
There are no constraints for this op, so no additional tests were added besides renaming/moving tests.
closes #1129
=> Add interpreter for OptimizationBarrierOp

stablehlo/reference/Ops.cpp
As pointed out in https://github.com/openxla/stablehlo/pull/1635#discussion_r1240498968, we can clean up some code by calling `getResult()` on the specific op class in favor of calling `getResult(0)` on the wrapper everywhere.
=> Specialize `getResult()` calls to specific `FooOp` classes

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_bfloat16_5_7.mlir, stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_float16_5_7.mlir, stablehlo/testdata/reduce_precision_in_bfloat16_5_7__out_float32_5_7.mlir, stablehlo/testdata/reduce_precision_in_bfloat16___out_bfloat16.mlir, stablehlo/testdata/reduce_precision_in_bfloat16___out_float16.mlir, stablehlo/testdata/reduce_precision_in_bfloat16___out_float32.mlir, stablehlo/testdata/reduce_precision_in_float16_5_7__out_bfloat16_5_7.mlir, stablehlo/testdata/reduce_precision_in_float16_5_7__out_float16_5_7.mlir, stablehlo/testdata/reduce_precision_in_float16_5_7__out_float32_5_7.mlir, stablehlo/testdata/reduce_precision_in_float16___out_bfloat16.mlir, stablehlo/testdata/reduce_precision_in_float16___out_float16.mlir, stablehlo/testdata/reduce_precision_in_float16___out_float32.mlir, stablehlo/testdata/reduce_precision_in_float32_5_7__out_bfloat16_5_7.mlir, stablehlo/testdata/reduce_precision_in_float32_5_7__out_float16_5_7.mlir, stablehlo/testdata/reduce_precision_in_float32___out_bfloat16.mlir, stablehlo/testdata/reduce_precision_in_float32___out_float16.mlir, stablehlo/testdata/reduce_precision_in_float32___out_float32.mlir, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_reduce_precision.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand`: tensor of floating-point type.
(I2) `exponent_bits`: constant of type `si32`.
(I3) `mantissa_bits`: constant of type `si32`.
(C1) `operand` and `output` have the same type.
(C2) `exponent_bits` >= 1.
(C3) `mantissa_bits` >= 0.
```
```
(I1) `operand` is not a tensor of floating-point type. (Covered by ODS).
(I2) `exponent_bits` is not a constant of type `si32`. (Covered by ODS).
(I3) `mantissa_bits` is not a constant of type `si32`. (Covered by ODS).
(C1) type(`operand`) != type(`output`). (Covered by ODS).
(C2) `exponent_bits` < 1.
(C3) `mantissa_bits` < 0.
``` …
=> Add interpreter for ReducePrecisionOp

docs/compatibility.md
This PR aggregates missing information from multiple RFCs:
1) Situations which are not covered by compatibility guarantees
(numerical accuracy, bug compatibility and unspecced features).
2) How our compatibility suite works (this part of compatibility.md
is pretty outdates).
=> Further update compatibility.md

docs/spec.md
The PR proposes the specification of remaining data movement ops. Specifically, the PR covers `concatenate`, `sort`, `broadcast_in_dim`, `gather`, `scatter`, `dynamic_slice`, and `dynamic_update_slice`.  The rest are covered in a separate [PR](https://github.com/openxla/stablehlo/pull/1535). 
I note that 
-  The specifications are very similar to each other and hence i thought about putting it in a single PR.
- Following the discussion item in [link](https://groups.google.com/a/openxla.org/g/openxla-discuss/c/iwE9is49SS4/m/mi9AyvKZAQAJ), I proposed the specification to use using pex-tensor quantization granularity.  Feel free to provide your input if any of the op has a use-case to support per-axis scheme.
=> Specification of the remaining quantized data movement ops

docs/compatibility.md
Based on a conversation with Kevin from earlier today. This is a nice catch and an important clarification.
We do want to provide compatibility guarantees around new features (e.g. make sure that they cannot be serialized to portable artifacts with older target versions) - unspecced features mean something different, which is explicitly elaborated in the document now.
=> Clarify what "unspecced features" means

stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
Some of the stablehlo ops does not have support for quantized types in their  tablegen specification, prohibits writing StableHLO quantized programs using those ops. The PR is about adding the missing support for the following ops. Also, I believe the ongoing specification [work](https://github.com/openxla/stablehlo/issues/588), should not deviate much from the  proposed changes here.  
```
stablehlo.atan2
stablehlo.divide
stablehlo.power
stablehlo.remainder
stablehlo.subtract
stablehlo.abs
stablehlo.cbrt
stablehlo.cosine
stablehlo.exponential
stablehlo.exponential_minus_one
stablehlo.log
stablehlo.log_plus_one
stablehlo.logistic
stablehlo.negate
stablehlo.rsqrt
stablehlo.sign
stablehlo.sine
stablehlo.sqrt
stablehlo.tanh
stablehlo.cholesky
stablehlo.triangular_solve
```
Other than these …
=> Adding the missing quantized-type support in the ODS

docs/spec.md, stablehlo/reference/Ops.cpp, stablehlo/tests/interpret_reduce_window.mlir
Turns out https://github.com/openxla/stablehlo/pull/1492 didn't actually fix the bug since `window_end` is still calculated incorrectly.
Shoutout to @pravnar for filing the bug :)
closes #1662
=> Fix incorrect `window_end` calculation for ReduceWindowOp

.github/workflows/lint.yml, build_tools/github_actions/lint_version.sh
This will fail if we bump the version to `Version(0, 15, 0)` without adding new compatibility tests.
Fixes https://github.com/openxla/stablehlo/issues/1563
=> Add lint to ensure that compatibility tests are implemented for new versions of StableHLO

BUILD.bazel, stablehlo/dialect/Serialization.cpp, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/tools/StablehloOptMain.cpp, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/PassPipelines.cpp, stablehlo/transforms/Passes.h, stablehlo/transforms/VhloToVersion.cpp
Some users want to write APIs that accept portable artifacts _and_ other programs. Currently adding support for portable artifacts requires additional logic to test if input is a portable artifact, then deserialize it before running any other passes. This is not ergonomic, as the more MLIR way of doing this is to offer a pass that will deserialize _if_ the input is a portable artifact - for example, support for StableHLO was added to some TF APIs using a `createHloLegalizeToStablehlo` pass.
To get to a point to permit this, we need two changes:
1. Don't error on non-VHLO dialects when deserializing, currently only happens in `--vhlo-to-version`.
This isn't a big issue, as `--stablehlo-legalize-to-vhlo` already validates that programs are stable. The current way VHLO to version is written …
=> Offer StableHLO portable artifact deserialization as a pass pipeline

stablehlo/dialect/AssemblyFormat.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Ops.cpp, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
This PR addresses clang-tidy issues found during the ongoing downstream integrate (we don't run clang-tidy on our PRs yet, so these issues have deferred detection).
Also, I changed stablehlo_canonicalize_dynamism.mlir to explicitly specify operation types in CHECK directives. This pass is all about operation types, so let's check them explicitly.
=> Cleanup after a downstream integrate

stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll
Apparently, tosa.logical_not doesn't implement type inference, so the build warning was asking to explicitly provide a return type in the PDLL pattern, which this PR does.
=> Fix a build warning in conversion to TOSA

rfcs/20230517-forward-compatibility-testing.md
This is a proposal for forward compatibility testing in StableHLO. This ensures that payloads serialized at HEAD can be deserialized at a previous release.
Note, this plan is built on top of our existing backward compatibility testing infrastructure, and as such does not include semantic forward compatibility testing. Once we have addressed semantic compatibility testing in #1416 we can expand this machinery to include semantic forward compatibility testing.
- **Proposed design prototype:** https://github.com/GleasonK/stablehlo/pull/35
- **Alternate design prototype:** https://github.com/GleasonK/stablehlo/pull/33
Notification of this PR will be sent to the [openxla-discuss](https://groups.google.com/a/openxla.org/g/openxla-discuss) group.
Related to #1318.
UPDATE 5/25: While this RFC is …
=> [RFC] Forward Compatibility Testing

docs/spec.md
This PRs provides the specification of the ops from the following categories:
* **Control-flow ops**: `after_all, case, if, optimization_barrier, while`
- `afer_all`: Not applicable for quantization as the ops deals with setting data-flow ordering using tokens. 
- `case, if`: These ops  implicitly captures operands from the parent scope. The result of these operations and the corresponding blocks  can be quantized types. 
- `optimization_barrier`: The `operand` and `result` can both be quantized tensors.
- `while`: The `operand` and `result` can both be quantized tensors and of same type. Per the semantics of `while` op, the output of the associated block is used for the next iteration with the `operand` used for the very first iteration. With that,  I do not think we can use the …
=> Specification of quantized ops from `Control-flow`, `Distribution`, `Extensibility`, and `Miscellaneous` categories. 

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
After https://reviews.llvm.org/D155687 the builtin Commutative trait has folders by default. StableHLO does not want to have any default folding or canonicalization. Adding a `hlo::OpTrait::IsCommutative` and `HLO_Commutative` trait to avoid these folders.
=> Add `HLO_Commutative` trait to avoid inheriting folders

stablehlo/reference/Ops.cpp
Some functions were alphabetically ordered up to their op name disregarding the suffix "Op". This now orders all ops to alphanumerically order on the entire Operation name (e.g. `LogOp` should come first before `LogisticOp` since `O` < `i`).
=> Alphanumerically order ops

BUILD.bazel
These include some lint related changes on the `BUILD.bazel` file.
=> Patch BUILD.bazel files after integrate

docs/spec.md
fixes #1628 
The idea behind the PR is to treat the quantization of `dot_general` and `convolution` similar to how various other element wise ops are specified. Other than the obvious parity of the specification with other ops, there are other benefits too.
1. `dot_general` and `convolution` are potential candidates for per-axis quantization. With this solution we can define per-axis scheme uniformaly in the meta-functions `dequantize`  and `quantize` and thereby do not have to  explicitly handle the per-axis scheme for these ops. 
2. `dot_general` and `convolution` uses some data_movement ops (like `reshape`, `transpose`, `pad`, `slice`) for the underlying specification. There is a concern where  the fact that `dot_general` and `convolution` can potentially use per-axis quantization …
=> Using dequant-op-quant for convolution and dot_general

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Process.cpp, stablehlo/reference/Process.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_all_reduce.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand` tensor.
(I2) `replica_groups` variadic number of 1-dimensional tensor constant of type `si64`.
(I3) `channel_id` constant of type `si64`.
(I4) `use_global_device_ids` constant of type `i1`.
(I5) `computation` function.
(C1) `is_unique(replica_groups)`.
(C2) `size(replica_groups)` is defined as:
* `num_replicas` if `cross_replica` is used.
* `num_replicas` if `cross_replica_and_partition` is used.
* `num_processes` if `flattened_ids` is used.
(C3) `0 <= replica_groups < size(replica_groups)`.
(C4) If `use_global_device_ids = true`, then `channel_id > 0`.
(C5) `computation` has type `(tensor<E>, tensor<E>) -> (tensor<E>)` where
`E = element_type(operand)`.
(C6) `type(result) = type(operand)`.
```
These constraints will be …
=> Add interpreter for AllReduceOp

BUILD.bazel
This will cause that llvm/torch-mlir failed to integrate mlir-hlo with bazel.
=> fix BUILD.bazel

stablehlo/dialect/StablehloOps.cpp
Also fixed strange naming mix of snake/camel case `non_spatialDim` to match mlir-hlo. Fixed for MHLO in tensorflow/mlir-hlo@5aa3df6 but forgot to make the stopgap fix in StableHLO as well.
=> Port of tensorflow/mlir-hlo@5aa3df6 to avoid invalid access

stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h
There is a race condition when two processes try to access `channelLocks_[channelKey]` at the same time when that key doesn't exist. The two processes will both create a mutex at the same time, acquiring different mutex instead of sharing the same one. It is also unsafe to read from `channels_[channelKey]` without a lock since this value can also be modified by another caller to `rendezvous` with a duplicate `processGroup` and `channelId` by another distribution op.
=> Fix race condition in `ProcessGrid::rendezvous`

stablehlo/tests/ops_stablehlo.mlir
This PR brings the remaining StableHLO changes from downstream changes from following #1724.
=> Followup on port of tensorflow/mlir-hlo@5aa3df6

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_all_gather.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand`: tensor or per-tensor quantized tensor.
(I2) `all_gather_dim`: constant of type `si64`.
(I3) `replica_groups`: 2-dimensional tensor constant of type `si64`.
(I4) `channel_id`: constant of type `si64`.
(I5) `use_global_device_ids`: constant of type `i1`.
(C1) `0 <= all_gather_dim < rank(operand)`.
(C2) `is_unique(replica_groups)`.
(C3) `size(replica_groups)` is defined as:
* `num_replicas` if `cross_replica` is used.
* `num_replicas` if `cross_replica_and_partition` is used.
* `num_processes` if `flattened_ids` is used.
(C4) `0 <= replica_groups < size(replica_groups)`.
(C5) If `use_global_device_ids = true`, then `channel_id > 0`.
(C6) `type(result) = type(operand)` except:
* `dim(result, all_gather_dim) =
dim(operand, …
```
=> Add interpreter for AllGatherOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_all_to_all.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand` is a tensor.
(I2) `split_dimension` is a constant of type `si64`.
(I3) `concat_dimension` is a constant of type `si64`.
(I4) `split_count` is a constant of type `si64`.
(I5) `replica_groups` is a 2-dimensional tensor constant of type `si64`.
(I6) `channel_id` is a constant of type `si64`.
(C1) `0 <= split_dimension < rank(operand)`.
(C2) `dim(operand, split_dimension) % split_count = 0`.
(C3) `0 <= concat_dimension < rank(operand)`.
(C4) `0 < split_count`.
(C5) `is_unique(replica_groups)`.
(C6) `size(replica_groups)` is defined as:
* `num_replicas` if `cross_replica` is used.
* `num_partitions` if `cross_partition` is used.
(C7) `0 <= replica_groups < size(replica_groups)`.
(C8) `dim(replica_groups, 1) = split_count`.
(C9) …
```
=> Add interpreter for AllToAllOp

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret_reduce_scatter.mlir, stablehlo/tests/ops_stablehlo.mlir
```
(I1) `operand` is a tensor.
(I2) `scatter_dimension` is a constant of type `si64`.
(I3) `replica_groups` is a 2-dimensional tensor constant of type `si64`.
(I4) `channel_id` is a constant of type `si64`.
(I5) `use_global_device_ids` is a constant of type `i1`.
(I6) `computation` is a function.
(C1) `dim(operand, scatter_dimension) % dim(process_groups, 1) = 0`.
(C2) `0 <= scatter_dimension < rank(operand)`.
(C3) `is_unique(replica_groups)`.
(C4) `size(replica_groups)` is defined as:
* `num_replicas` if `cross_replica` is used.
* `num_replicas` if `cross_replica_and_partition` is used.
* `num_processes` if `flattened_ids` is used.
(C5) `0 <= replica_groups < size(replica_groups)`.
(C6) If `use_global_device_ids = true`, then `channel_id > …
```
=> Add interpreter for ReduceScatterOp

stablehlo/tests/interpret_all_gather.mlir, stablehlo/tests/interpret_all_reduce.mlir, stablehlo/tests/interpret_all_to_all.mlir, stablehlo/tests/interpret_collective_permute.mlir, stablehlo/tests/interpret_outfeed.mlir, stablehlo/tests/interpret_reduce_scatter.mlir
There are TSAN violations for multithreaded tests. I've added #1755 to address it, and we should disable it in the meantime.
=> Disable multithreaded tests

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/InterpreterValue.cpp, stablehlo/reference/InterpreterValue.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Scope.cpp, stablehlo/reference/Scope.h, stablehlo/testdata/igamma_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir, stablehlo/testdata/igamma_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir, stablehlo/testdata/igamma_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir, stablehlo/testdata/igamma_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir, stablehlo/testdata/igamma_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir, stablehlo/testdata/igammac_broadcasting_lhs_float32_1_20__rhs_float32_20_20.mlir, stablehlo/testdata/igammac_broadcasting_lhs_float32_20_20__rhs_float32_1_20.mlir, stablehlo/testdata/igammac_dtypes_lhs_bfloat16_20_20__rhs_bfloat16_20_20.mlir, stablehlo/testdata/igammac_dtypes_lhs_float16_20_20__rhs_float16_20_20.mlir, stablehlo/testdata/igammac_dtypes_lhs_float32_20_20__rhs_float32_20_20.mlir, stablehlo/testdata/regularized_incomplete_beta__bfloat16.mlir, stablehlo/testdata/regularized_incomplete_beta__float16.mlir, stablehlo/testdata/regularized_incomplete_beta__float32.mlir, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret_tuple_and_get_tuple_element.mlir, stablehlo/tests/ops_stablehlo.mlir
TupleOp:
```
(I1) `val` is a variadic number of values.
(C1) `result` has type `tuple<E0, ..., EN-1>` where `Ei = type(val[i])`.
```
```
I1: a) `val` is not a variadic number of values. (Covered by ODS).
C1: a) `result` does not have type `tuple<E0, ..., EN-1>` where `Ei = type(val[i])`.
```
```
C1: a) `result` does not have type `tuple<E0, ..., EN-1>` where `Ei = type(val[i])`.
```
closes #1139
GetTupleElementOp:
```
(I1) `operand` is a tuple.
(I2) `index` is a constant of type `si32`.
(C1) `0 <= index < size(operand)`.
(C2) …
```
=> Add interpreters for TupleOp and GetTupleElementOp

stablehlo/tests/ops_chlo_roundtrip.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
The "grep" utility doesn't exist on Windows (except on MSYS2 systems),
making it difficult for Windows users to run a handful of lit tests in
the stablehlo/tests directory.  As a workaround, this patch replaces the
use of grep in these tests with FileCheck.
=> tests: drop the use of "grep" from lit tests

stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Element.cpp, stablehlo/reference/Ops.cpp, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
The `long` type is 32 bits wide on Windows, either 32 or 64 bits wide on
Linux (depending on x86 or x64), and 64 bits wide on macOS.
Consequently, when we use bit-shift operators to construct 64-bit
integers or when we check for splat tensors, using (signed or unsigned)
`long` integers can produce incorrect values.
This patch replaces signed and unsigned `long` integer literals with
signed and unsigned `long long` values respectively, so that the
they are always 64 bits wide on all platforms.  As a minor change, this
patch uses the lower-case suffixes (`{u}ll` instead of `{U}LL`) for
consistency.
This patch is in anticipation of downstream users of StableHlo, like
Torch-MLIR (which use Windows and macOS builds), swapping MLIR-HLO with
StableHlo.
=> build: use 64-bit integer literals across all platforms

docs/spec.md
Based on the discussion in https://github.com/openxla/stablehlo/issues/1574, I propose the quantization specification for the following data movement ops:
-  **transpose**:  The `quantization_dimension` of `result` is also transposed based on the input `permutation` order.
- **reshape**:  The `quantization_dimension` of the operand should not be merged or split.
- **broadcast_in_dim**: For [degenerate dimension broadcasting](https://www.tensorflow.org/xla/broadcasting#broadcasting_similar-rank_arrays_with_degenerate_dimensions) of the operand's quantized dimension, the scales of the result are expanded.
=> Per-axis quantization specification for reshape, transpose, and broadcast_in_dim.

stablehlo/api/CMakeLists.txt, stablehlo/dialect/CMakeLists.txt, stablehlo/integrations/python/tests/CMakeLists.txt
This patch makes two small changes.  First, it adds the `MLIRParser`
library as a dependency for the `StablehloPortableApi` and the
`StablehloSerialization` library targets, since both PortableApi.cpp and
Serialization.cpp include calls to `mlir::parseSourceString()`.
Although the code _does_ build without this dependency, it seems like an
accidental result, so this patch makes the dependency explicit.
Second, the Windows shell does not use the same rules as Bash for
setting environment variables, thus causing the `check-stablehlo-python`
target to fail.  This patch uses the (cross-platform) CMake syntax for
setting the `PYTHONPATH` environment variable before running the python
script.
=> build: miscellaneous CMake fixes

stablehlo/reference/Ops.cpp, stablehlo/reference/Process.cpp, stablehlo/reference/Process.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h, stablehlo/reference/Tensor.h, stablehlo/tests/interpret_all_gather.mlir, stablehlo/tests/interpret_all_reduce.mlir, stablehlo/tests/interpret_all_to_all.mlir, stablehlo/tests/interpret_collective_permute.mlir, stablehlo/tests/interpret_outfeed.mlir, stablehlo/tests/interpret_reduce_scatter.mlir
The TSAN violation is due to an unprotected insert shown above and replacing `llvm::RefCountedBase` with its thread-safe alternative `llvm::ThreadSafeRefCountedBase`.
In the original implementation of `rendezvous`, there were some nuances that were undesirable.
For example, it's preferred to clear out the entry once all processes have read the data and clear out the map instead of letting the next distribution op to clear it out. The current implementation is also incorrect since there is no guarantee that processGroup size is the same as previous op calling `rendezvous`.
```
if (channels_[channelKey].size() == processGroup.size())
channels_[channelKey].clear();
channels_[channelKey].insert(processId, operand);
```
The proposed update enhances the `rendezvous` logic such that each process …
=> Fix TSAN violations for Distribution ops

docs/spec.md
The specification of broadcasting a scalar operand, using broadcast_in_dim, is unclear. The PR attempts to update the semantics for the operation to accommodate the case. 
Also, the update is limited to a spec change as the following program
```
func.func @main() -> (tensor<1x750xi32>) {
  %0 = stablehlo.constant dense<1> : tensor<i32>
  %1 = stablehlo.broadcast_in_dim %0, dims = [] : (tensor<i32>) -> tensor<1x750xi32>
  return %1 : tensor<1x750xi32>
}
```
is currently a valid representation in StableHLO.
=> Allow the specification of a scalar operand for broadcast_in_dim operation

docs/spec.md
Semantics of some operations like `broadcast_in_dim`, `clamp`, and `select`, with one or more of the input operands  potentially be scalars, needs implicit broadcasting.  For example,  `operand` for  `broadcast_in_dim`, `min`/`max` for `clamp`, `pred` for `select`.
The current PR fixes the access of those operands, to indicate proper deference of the tensor type to element type, in the specification of these operations.
=> Fixing the access of scalar elements in `broadcast_in_dim`, `clamp`, and `select` operations

stablehlo/reference/Process.cpp, stablehlo/reference/Process.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h
These results should not be modified by threads once returned, thus the pointer can be to const data. Making the shared pointer const doesn't add much, just means that the thing being pointed at cant be changed, which doesn't guarantee much.
=> Fix clang tidy, change constness of rendezvous results

docs/spec.md, docs/status.md, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/InterpreterOps.cpp, stablehlo/reference/InterpreterOps.h, stablehlo/reference/InterpreterOps.td, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Process.cpp, stablehlo/reference/Process.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h, stablehlo/tests/interpret_all_gather.mlir, stablehlo/tests/interpret_all_reduce.mlir, stablehlo/tests/interpret_all_to_all.mlir, stablehlo/tests/interpret_collective_permute.mlir, stablehlo/tests/interpret_infeed.mlir, stablehlo/tests/interpret_outfeed.mlir, stablehlo/tests/interpret_partition_id.mlir, stablehlo/tests/interpret_reduce_scatter.mlir, stablehlo/tests/interpret_replica_id.mlir, stablehlo/tests/ops_interpreter.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tools/StablehloTranslateMain.cpp
```
(I1) `token` is a `token`.
(I2) `infeed_config` is a constant of type `string`.
(C1) `0 < size(results)`.
(C2) `is_empty(result[:-1])` or `is_tensor(type(results[:-1]))`.
(C3) `is_token(type(results[-1]))`.
```
```
I1: a) `token` is not a `token`. (Covered by ODS).
I2: a) `infeed_config` is not a constant of type `string`. (Covered by ODS).
C1: a) `size(results) <= 0`.
C2: a) `is_empty(result[:-1]) = false` and `is_tensor(type(results[:-1])) = false`.
C3: a) `type(results[-1]) != token`.
```
```
C1: a) `size(results) <= 0`.
C2: a) `is_empty(result[:-1]) = false` and …
```
=> Add interpreter for InfeedOp

stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
fixes https://github.com/openxla/stablehlo/issues/1765
The existing verifier for these ops  was using the trait [SameOperandsAndResultElementType](https://github.com/openxla/stablehlo/blob/b2090e9774f68c81b65615d18872b99b718eedad/stablehlo/dialect/StablehloOps.td#L2763) to check the equality of the element types which will not work for the per-axis quantized variants of these ops as the quantization dimension and quantization parameters (scales and zero points)  may differ between operand and result.
The PR proposed to replace the trait with [HLO_CompatibleOperandsAndResultElementType ](https://source.corp.google.com/piper///depot/google3/third_party/stablehlo/stablehlo/dialect/Base.td;rcl=567468454;l=216)(which just checks the equality for storage type and expressed type).
Note that the …
=> Fixing verifier for reshape, transpose, and broadcast_in_dim ops

BUILD.bazel, stablehlo/reference/CMakeLists.txt, stablehlo/reference/InterpreterOps.cpp, stablehlo/reference/InterpreterOps.h, stablehlo/reference/InterpreterOps.td, stablehlo/reference/NumPy.cpp, stablehlo/reference/NumPy.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.h, stablehlo/tests/BUILD.bazel, stablehlo/tests/CMakeLists.txt, stablehlo/tests/CheckOps.cpp, stablehlo/tests/CheckOps.h, stablehlo/tests/CheckOps.td, stablehlo/tests/interpret_probe.mlir, stablehlo/tools/StablehloTranslateMain.cpp
Reopening #1763 due to a branch corruption issue. Original text below:
===
As the number of ML frameworks continues to rapidly grow, it’s becoming increasingly desirable to be able to compare numerical results across different runtimes. This ensures that ML models run equivalently in different environments, and overall helps to instill confidence in ML frameworks. For example, given the recency of the StableHLO representation, it may be desirable to have a way to compare StableHLO interpreter results to other frameworks, such as Tensorflow, or other implementations
This PR proposes the addition of a probe instruction to the new interpreter dialect in StableHLO. The probe instruction will enable us to extract intermediate tensor state from the StableHLO interpreter. Since this new op is …
=> Add reference interpreter probe instrumentation

docs/interpreter_status.md
This PR adds documentation to the StableHLO interpreter's current status and provides a way to convert StableHLO ops without a direct implementation to ones that do via running a set of expander/transform passes within the [openxla/xla](https://github.com/openxla/xla) repo.
In summary, this PR closes most of the remaining specced ops without an interpreter with a few exceptions noted in the doc: `FftOp`, `RngOp`, `RngBitGeneratorOp`, `UniformDequantizeOp`, and `UniformQuantizeOp`. It also documents interpretation of ops categorized as "Not In HLO" which currently does not have a formal spec in our StableHLO [spec.md](https://github.com/openxla/stablehlo/blob/main/docs/spec.md).
This PR resolves most of the items in #1571 except ones mentioned above and those marked N/A in the comment …
=> Add Documentation on Reference Interpreter

BUILD.bazel
Previously, these dependencies were not sorted which triggered a lint check during a downstream integrate. Looks like a useful thing to fix.
=> Sort dependencies of the stablehlo_ci_tests target

stablehlo/reference/InterpreterOps.td, stablehlo/tests/CheckOps.td
[MLIR Properties](https://mlir.llvm.org/OpenMeetings/2023-02-09-Properties.pdf) are the new standard for non-discardable attributes. In the near future, all dialects must migrate to use properties by default. This PR migrates InterpreterDialect and CheckDialect, which turned out to be trivial.
VHLO changes are approved, the changes for StableHLO and CHLO will be slightly more involved.
Part of #1584.
=> Migrate InterpreterDialect and CheckDialect to use properties

BUILD.bazel, stablehlo/dialect/Base.h, stablehlo/tests/BUILD.bazel
* Add a comment next to #endif in Base.h.
* Sort dependencies alphabetically in BUILD.bazel.
=> Fix issues found during the recent downstream integrate

stablehlo/tests/CMakeLists.txt
Was working in a corrupt build area and got a "command `not` not found" error. CMake somehow works without it normally, but still better to add it for correctness.
References:
- [StableHLO test using `not`](https://github.com/openxla/stablehlo/blob/654c202babbab3f4bd50cdd276de02dc17ecc358/stablehlo/tests/vhlo_to_version_invalid.mlir#L4)
- [StableHLO bazel dependency on `not`](https://github.com/openxla/stablehlo/blob/654c202babbab3f4bd50cdd276de02dc17ecc358/stablehlo/tests/BUILD.bazel#L150)
- [MHLO example](https://github.com/openxla/xla/blob/fb67091154574430a8fd17b7eae7ceadd79f7139/xla/mlir_hlo/tests/CMakeLists.txt#L24) using not dependency in cmake
=> Add dependency on LLVM's not tool

rfcs/20231017-collective-broadcast.md
This RFC proposes adding `collective_broadcast` as one of the collective communication primitives. 
Please provide any feedback you feel is valuable.
=> [RFC] Add collective_broadcast to the StableHLO specification

stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h
The following error is surfaced during the StableHLO integration. 
```
function template specialization 'mlir::stablehlo::impl::mapStablehloOpToStdScalarOp<mlir::stablehlo::ClampOp>' has a primary template declaration with different parameter names
```
=> Fix clang-tidy error

stablehlo/conversions/tosa/transforms/CMakeLists.txt
**Issue:**
The issue is due to **`StablehloLegalizeToTosa.cpp`** attempting to include a TableGen'd file (**`StablehloEnums.h.inc`**) that hasn't been generated yet, resulting in the following build failure:
```bash
In file included from /stablehlo/stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp:25:
/stablehlo/stablehlo/dialect/StablehloOps.h:45:10: fatal error: 'stablehlo/dialect/StablehloEnums.h.inc' file not found
#include "stablehlo/dialect/StablehloEnums.h.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
**Reproduce:**
To reproduce this issue on Linux or Mac, follow these steps:
```bash
export LLVM_PROJECT_BUILD="/path/to/llvm-project/build"
git clone https://github.com/openxla/stablehlo.git
python3 -m venv stablehlo_venv
source …
```
=> TableGen Headers Included Before They Are Generated

docs/spec.md
The PR intends to add more clarification to the existing definition of `baseline_type` meta function.
=> Clarifying the semantics of  `baseline_type` meta function

stablehlo/reference/Api.cpp, stablehlo/reference/InterpreterOps.cpp, stablehlo/reference/InterpreterOps.h, stablehlo/tests/interpret_probe.mlir
This PR builds off of the recently submitted changes in #1784. Prior to this change, the value of `probe_id` and an internal execution counter is used to derive the filename for serializing probed tensor values (i.e. `<probe_output_dir>/<probe_id>_<execution_count>.npy`). This current design has the following disadvantage:
1. This can be unsafe as no filename sanitation is performed, relying on the compiler (or other tooling) to produce friendly `probe_id` values. Instead of having this implicit assumption on the instrumented StableHLO program, this change uses internally generated serialization filenames by using a strictly increasing counter.
This change proposes that the serialization filename now be derived as follows:
```
<probe_output_dir>/probe<i>.npy
```
Where `i` is a uniquely …
=> Allow unsafe probe_id values to be serialized properly to disk

stablehlo/reference/InterpreterOps.cpp, stablehlo/reference/InterpreterOps.td, stablehlo/tests/CheckOps.cpp, stablehlo/tests/CheckOps.td
Recently, we introduced a way to extract intermediate tensor state from the StableHLO reference interpreter (#1784) for instrumentation/debugging purposes. As part of this instrumentation process, the interpreter will create an `index.csv` metadata file which contains all serialized tensor paths and uniquely identifying `probe_id` values in the form of:
```
probe_id,/some/absolute/path/to/numpy_0.npy
...
```
In the event that an `interpreter.probe` instruction is executed more than once (i.e. due to being within a loop), there could be `N` entries with the same `probe_id` value.
This current schema however does not serialize the `mlir::TensorType` of the data. The inclusion of this type information can make it easier for post processing tools/scripts to better interpret the metadata file, …
=> Serialize MLIR type when instrumenting reference interpreter values

stablehlo/reference/Api.cpp, stablehlo/tests/interpret_probe.mlir
This PR addresses a bug introduced by PR #1797 where as a result of the new interpreter API, running empty StableHLO modules would result in an error `Requested main function not found.` whereas previously, the `stablehlo-translate` utility would not throw any error.
(Found by @ghpvnist in #1841).
=> Do not throw error when executing empty StableHLO modules

docs/spec.md
The PR implements the approved [RFC for reduce op](https://github.com/openxla/stablehlo/pull/1664) by proposing the specification related changes for `reduce`, `reduce_window` and `select_and_scatter` ops.
In https://github.com/openxla/stablehlo/pull/1647, we talked about some  of the other ops which will depend on the quantized specification of reduce op. Initially, I thought about creating separate PRs for them, but for the interest of time and the fact that their handling is going to be very similar to how `reduce` op is handled, I propose to include their PR in the current PR.
Here are the  additional ops (other than `reduce`, `reduce_window`, `select_and_scatter`) whose specification is added
- Ops with explicit computation regions: `all_reduce`, `reduce_scatter`, `scatter`: They are …
=> Specification of quantized `reduce` and other related ops

docs/reference_checklist.md, docs/spec_checklist.md, docs/status.md, docs/type_inference.md
The roadmap is in its own document (it no longer has a header in the README) and some XLA stuff was moved out of tensorflow.
The XLA MLIR interpreter was deleted in https://github.com/tensorflow/tensorflow/commit/079ab56a5b0c5aefcdffa4f20f79c7bb137c6bd0.
=> Fix broken links

BUILD.bazel, stablehlo/transforms/Passes.h, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloRefineShapes.cpp, stablehlo/transforms/StablehloRefineShapes.h, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
VHLO bug: `DenseI64ArrayAttr` doesn't have a notion of splats like `DenseIntElementsAttr` does. The following array when serialized as as the VHLO wrapper around `DenseIntElementsAttr` could not be converted to `DenseI64ArrayAttr` properly:
```
dense<0> : tensor<2xi64>
vs
array<i64: 0, 0>
```
There the value that gets serialized is just `0`. When converting to `DenseI64ArrayAttr` must look at the type and see if the splat should be expanded. This isn't a huge memory issue since these attrs are only used in cases where the number of values in the array is small.
Shape refinement: Refactor into a header file with some patterns that can be populated, instead of a single API entrypoint.
=> Fix VHLO DenseI64Array bug and refactor shape refinement pass

stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/VhloAttrs.td
The `cppNamespace` field for `AttrDef`s is [inherited](https://github.com/llvm/llvm-project/blob/2e45326b088b3b2f5c8327f6d5e61bdd2845bbbe/mlir/include/mlir/IR/AttrTypeBase.td#L255C7-L255C18) from the `Dialect`'s `cppNamespace` [via DialectAttr](https://github.com/llvm/llvm-project/blob/2e45326b088b3b2f5c8327f6d5e61bdd2845bbbe/mlir/include/mlir/IR/CommonAttrConstraints.td#L86).
=> Remove redundant cppNamespace fields

docs/spec.md, stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/interpret_broadcast_in_dim.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/tests/print_stablehlo.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_10_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_11_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_12_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_13_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_14_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_15_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_16_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.0_9_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir, stablehlo/tests/verify_while.mlir, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
This is an intermediate step in the migration to `DenseI64ArrayAttr`.
This also includes changing `dense<...>` to `array<...>` in the tests for `BroadcastInDim` and `DynamicBroadcastInDim` (both are supported, but we want to move towards `array<...>`).
https://github.com/openxla/stablehlo/issues/1578
=> Port DynamicBroadcastInDim to I64DenseArrayOrElements1DAttr

.bazelversion, stablehlo/api/PortableApi.h
Updated API version + Added copyright declaration in the newly introduced `.bazelversion` file.
=> Updating API version

stablehlo/transforms/CMakeLists.txt
Commit afd8f5bd6 introduced a file (StablehloInstrumentWithProbe.cpp)
that references `interpreter::ProbeOp` (defined in the InterpreterOps
library target), but this dependency was not added to the CMake build
rules for building the StablehloPasses target, which includes code from
StablehloInstrumentWithProbe.cpp.  As a result, builds (sometime) fail
with the following error:
```
Linking CXX shared library lib/libStablehloPasses.so
CMakeFiles/obj.StablehloPasses.dir/StablehloInstrumentWithProbe.cpp.o:
...
undefined reference to `mlir::stablehlo::interpreter::ProbeOp::build
...
```
This patch fixes the CMake build error by adding InterpreterOps as a
library dependency of the StablehloPasses target.
Credit to @hamptonm1 for discovering the problem.
=> build: add missing dependency on InterpreterOps

stablehlo/dialect/StablehloOps.td, stablehlo/tests/verify_while.mlir
Some of these were in the description for `slice` and some others were in tests where an earlier error caused the dense elements literals (which would have caused errors) to not be reached.
I used the following command to look for missed dense literals:
```
rg --multiline --multiline-dotall 'stablehlo\.(slice|dynamic_slice|fft|pad|reverse|rng|transpose)[^\n{]*?\{[^}]*?dense[^}]*?\}'
```
(where `rg` is `ripgrep`)
Thanks to @GleasonK  for catching this in the first place!
=> Remove a few dense elements attrs that were missed in #1872

BUILD.bazel, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/BroadcastUtils.cpp, stablehlo/dialect/BroadcastUtils.h, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloAttrs.td, stablehlo/tests/infer_chlo.mlir, stablehlo/tests/ops_chlo_roundtrip.mlir
This is an intermediate step in the migration to `DenseI64ArrayAttr`.
I had to move the definition for the attr to `Base.td` because it's now used in `ChloOps.td` as well as `StablehloOps.td`.
I also had to do some shenanigans to support checking if the `broadcast_dimensions` are legal in
`ReifyBroadcastBinaryOpReturnTypeShapes`. Because the attr is obtained through generic means (`op->getAttr("broadcast_dimensions")`); it doesn't go through the conversion from storage (e.g. when doing `op.getBroadcastDimensions`, which returns `SmallVector<int64_t>`), so both `DenseIntElementsAttr` and `DenseI64ArrayAttr` have to be handled.
Ideally, I would be able to do `dyn_cast<I64DenseArrayOrElements1DAttr>` and use a custom method on the attr to get the integers, but I see no way to define a custom …
=> Port CHLO ops to I64DenseArrayOrElements1DAttr

stablehlo/dialect/StablehloOps.cpp, stablehlo/tests/ops_sparse.mlir, stablehlo/tests/print_reduce.mlir
During discussion of #1523 we came to the conclusion that it's impossible to continously guarantee that location information is kept forwrad and backwards through transformations.
There is already precendent in other transformations that location information may be ellided.
Remove the constraint for the compact pretty printing of ReduceOpt that requires the locations be the same. Update the tests as necessary.
=> Remove location constraint on compact printing of ReduceOpt

stablehlo/dialect/Base.td
Uses were removed in the following PRs:
https://github.com/openxla/stablehlo/pull/1887/files#diff-c20bffbe3bc2037741cb7cf73b71ebf259fc419c15c2a6d3c39d6952ae59f89c https://github.com/openxla/stablehlo/pull/1893/files#diff-c20bffbe3bc2037741cb7cf73b71ebf259fc419c15c2a6d3c39d6952ae59f89c https://github.com/openxla/stablehlo/pull/1891/files#diff-8d62a195e9ed8776265bc22a7b8300534d4661e1c6bd659a21f27143311745dc
=> Delete BroadcastDimAttr (no longer used)

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp
In the same vein as https://github.com/openxla/stablehlo/pull/1893.
I decided to port the convolution "window_reversal" attribute to array directly, since it seems rarely used and it is the only attribute that is a 1D tensor of booleans.
Not porting the MLIR source files yet.
#1578
=> Port {Convolution,DynamicConv,Gather}Op to I64DenseArrayOrElements1DAttr

docs/_toc.yaml
This is needed for integration with internal publishing tools.
=> Add a _toc.yaml file to specify doc nav

stablehlo/conversions/linalg/tests/lit.cfg.py, stablehlo/conversions/tosa/tests/lit.cfg.py, stablehlo/testdata/lit.cfg.py, stablehlo/tests/lit.cfg.py, stablehlo/tests/stablehlo_legalize_to_vhlo.0_17_0.mlir, stablehlo/tests/stablehlo_legalize_to_vhlo.mlir
Ran into this while integrating: internal configuration sets `--enable-var-scope`, but we don't, so some tests failed internally but not here. I think in general this is a good setting to use: it's easier to understand a test if the only variables in scope are the variables defined by that test.
=> Disallow reusing variables across CHECK-LABEL directives

stablehlo/dialect/Base.td, stablehlo/dialect/StablehloAttrs.td
There is no guarantee that users of the generated .inc files are working in an `mlir` namespace, so we need to include the explicit `mlir::` prefix.
I discovered this because in some (out of repo) generated code an unqualified `Attribute` caused compilation failures.
=> Fully qualify storage types of ArrayOrElements attrs

stablehlo/testdata/lit.cfg.py
The name seems to have been copied from the tests suite. Sharing the name makes it a bit confusing which is which when listing tests, since tests under tests/ and testdata/ will be prefixed with the same name, e.g.
```
STABLEHLO_TESTS_SUITE :: infer_chlo.mlir
...
STABLEHLO_TESTS_SUITE :: zeros_like_shape_uint8_3_4_5.mlir
```
=> Use distinct, more specific name for testdata suite

stablehlo/transforms/StablehloLegalizeToVhlo.cpp
This makes the code a bit more readable. On my first read I was puzzled as to why this getter was being called.
=> Move definition of vhloOperands right before it is used

docs/_toc.yaml
The copyright message was missing `docs/_toc.yaml`.
=> Add missing copyright message

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/lint.yml, stablehlo/conversions/CMakeLists.txt, stablehlo/conversions/linalg/CMakeLists.txt, stablehlo/conversions/linalg/transforms/CMakeLists.txt
For the most part, `addlicense` handles the file types that we care about. It also doesn't handle some files that we (AFAICT) don't want license headers in: `.md` and `.mlir` files, e.g. However, it doesn't handle some files for which we may want license headers: `.bazel`, some `.in` files, `.pdll` and `.td`. I think it's debatable whether or not we want license headers in the following: `.bazelignore`, `.bazelrc`, `.bazelversion`, `.gitignore`, `.clang-format`, and these are also not handled by `addlicense`.
For `.bazel`, `.pdll` and `.td`, I will see if I can contribute to `addlicense` to handle those. For `.in` files (e.g. `lit.site.cfg.py.in`), I think whether or not we want a license actually depends on what the "true" type of the file is (e.g. `.py`). Supporting that would likely …
=> Add licensecheck lint to CI and add missing licenses

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp
The upstream change https://github.com/openxla/stablehlo/pull/1869 in StableHLO updates various API related to shape inference. MHLO shape inference functions in [hlo_ops.cc](https://github.com/openxla/xla/blob/main/xla/mlir_hlo/mhlo/IR/hlo_ops.cc) uses those APIs. The PR updates the visibility and signature of those API for a clearer integration.
Specifically, the PR does the followings:
1. **updates `getAccumulatorTypes` to return a error status when the input regions is empty**: This function is used in type inference of various reduction based operations ([eg](https://github.com/openxla/stablehlo/blob/d5b464925371092095ac934b46ba93ebd4284223/stablehlo/dialect/TypeInference.cpp#L2589)). This functions enables infering type based on the reduction block of the operation, which is …
=> Updates to shape functions enabling reuse from MHLO

docs/spec.md
The spec example for `all_reduce` a typo. [ref](https://github.com/openxla/stablehlo/blob/20255865ba299ed67bdf6267478c8477aef7a60d/stablehlo/dialect/StablehloOps.td#L1350)
=> Fix typo in the spec example for all_reduce

stablehlo/conversions/linalg/tests/convolution.mlir, stablehlo/conversions/linalg/tests/gather.mlir, stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/conversions/linalg/tests/reduce.mlir, stablehlo/conversions/tosa/tests/binary.mlir, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/interpret/gather.mlir, stablehlo/tests/interpret/map.mlir, stablehlo/tests/interpret/reduce.mlir, stablehlo/tests/interpret/reduce_window.mlir, stablehlo/tests/interpret/select_and_scatter.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/tests/print_reduce.mlir, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/tests/verify_conv.mlir, stablehlo/tests/verify_reduce.mlir, stablehlo/tests/verify_reduce_window.mlir, stablehlo/tests/verify_select_and_scatter.mlir
This change flips all the literals that can be written using `array` instead of `dense` without requiring C++ changes. The purpose of this change is to reduce the diff in a future change, where I will actually change the op fields to use `DenseI64ArrayAttr` instead of `I64DenseArrayOrElements1DAttr`. That will require making changes to parsing and serialization, among others.
=> Use array literals where possible in MLIR source

docs/_toc.yaml
Updates the openxla.org navbar to have groupings:
This is a first step toward incremental documentation improvements, TOC and doc page content should be revisited.
=> Update TOC to have more natural groupings

stablehlo/reference/Ops.cpp, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h, stablehlo/tests/interpret/all_gather.mlir
There's a data race when the last process returns via `std::move`. If the other processes are notified before the move happens, they will hang since `state.result` is still not null. To prevent this, we move it to another variable first so that `state.result` is empty before calling notify to other waiting processes.
Similarly, once the last process that contributed exits and notifies another process, it should notify other waiting processes before exiting. Otherwise, they will hang until the timeout, check the condition is true, and then proceed forward, which is not ideal.
Also includes minor formatting & typo fixes.
Here's an example output from debugging:
```
(0,0): (A) values.size() = 1
(0,1): (A) values.size() = 2
(1,0): (A) values.size() = 3
(1,1): (B) values.size() = 4
(1,1): …
```
=> Notify before returning to avoid race condition

docs/spec.md, stablehlo/dialect/StablehloOps.td
Even though there is (for the most part) no difference in how these characters are rendered, in some cases this can cause subtle issues that are hard to debug.
I used `ripgrep` to find the non-breaking spaces: `rg '\xA0'`.
=> Replace non-breaking spaces with regular spaces

stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp, stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/BroadcastUtils.cpp, stablehlo/dialect/BroadcastUtils.h, stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td
This completes the migration to `DenseI64ArrayAttr` started in https://github.com/openxla/stablehlo/pull/1658 (superseded by https://github.com/openxla/stablehlo/pull/1872) and announced in https://groups.google.com/a/openxla.org/g/openxla-discuss/c/hEoA4V5DZF0
Fixes https://github.com/openxla/stablehlo/issues/1578
=> Port *ArrayOr* -> Dense*ArrayAttr in CHLO and SHLO

.github/workflows/publishWheelRelease.yml
The workflow GitHub App default credential in OpenXLA cannot create GitHub releases.
Follow the convention identified by IREE in OpenXLA which uses a [repository secret](https://github.com/openxla/iree/blob/79b6129e2333ae26e7e13b68c27566102dcece6e/.github/workflows/validate_and_publish_release.yml#L112C37-L112C55) linked to a developers credential with repo permissions.
The secret created here was created by gleasonk@ and the secret at the moment of this commit belongs to fzakaria@.
It is valid for 1-year.
=> Change secret for wheel publishing

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp
Attrs will be implicitly copied. Avoid explicitly constructing the attrs as this introduces a dependency on the type of the attrs, meaning the code will need to be changed if the attrs' type changes.
=> Avoid explicitly constructing compatible attributes in a few places

docs/status.md
* Spec: yes, merged through RFC
* Verification: revisit, currently all of the collective ops are marked revisited. Will need to look into the verifications of this category further.
* Type Inference: yes, inferred trivially
* Pretty Printing: no
* Interpreter: no
=> Add CollectiveBroadcastOp to the status tracker

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
The PR implements the a custom `reduce` op builder similar to what we have for mhlo [code](https://github.com/openxla/xla/blob/50aec2b3b54ce7a861f45bc3b0ae9b2cc2ee2a28/xla/mlir_hlo/mhlo/IR/hlo_ops.cc#L3917). 
https://github.com/openxla/stablehlo/pull/1869 allows the block arguments of reduce op to have different element types than that of the input arguments of reduce op and the output element type of the reduce op has to equal to those block arguments. As a consequence the output type of reduce op can no longer be inferred from the operand types. The auto-generated builders creates a reduce op with empty block and, as  a result, does not allow inferring the type.
The proposed solution is to create a custom builder which takes the element-type of the block arguments as arguments allowing …
=> Add custom builder to reduce op allowing type inference

CMakeLists.txt
Fixes https://github.com/openxla/stablehlo/issues/1962#issuecomment-1919576685
Context: 
This breaks torch-mlir's CMake build when bumping stablehlo. 
The CMake build [fails](https://github.com/llvm/torch-mlir/actions/runs/7729517677/job/21072878412?pr=2821) with setup_sanitizers. Probably related to https://github.com/openxla/stablehlo/pull/1959 (cc: @fzakaria , @mlevesquedion ). I see the default for `STABLEHLO_ENABLE_SANITIZER` being `OFF`, but this code probably needs to be enclosed in an `if-endif`:
```
include(SetupSanitizers)
setup_sanitizers()
```
Error:
```
-- Building StableHLO as an external LLVM project
-- Building with -fPIC
CMake Error at /_work/torch-mlir/torch-mlir/externals/stablehlo/CMakeLists.txt:147 (include):
include could not find requested file:
SetupSanitizers …
```
=> Make setup_sanitizer include optional in CMakeLists.txt

.github/workflows/lint.yml, build_tools/github_actions/ci_build_cmake_code_coverage.sh, build_tools/github_actions/lint_buildifier.sh, build_tools/github_actions/lint_clang_format.sh, build_tools/github_actions/lint_llvm_commit.sh, build_tools/github_actions/lint_markdown.sh, build_tools/github_actions/lint_shellcheck.sh, build_tools/github_actions/lint_version.sh, build_tools/github_actions/lint_whitespace_checks.sh
shellcheck is a shell script analysis tool that can find bugs and subtle issues in shell scripts: https://www.shellcheck.net/
As part of adding the check, this commit also fixes any issues that are currently surfaced by shellcheck. These fell into the following categories:
- Adding missing shebangs to scripts because shellcheck recommendations depend on the shell being used.
- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
- [SC2034](https://www.shellcheck.net/wiki/SC2034) (warning): <variable> appears unused. Verify use (or export if used externally).
- [SC2207](https://www.shellcheck.net/wiki/SC2207) (warning): Prefer mapfile or read -a to split command output (or quote to avoid splitting).
- …
=> Add shellcheck lint to CI

build_tools/github_actions/lint_buildifier.sh, build_tools/github_actions/lint_markdown.sh, build_tools/github_actions/lint_shellcheck.sh
I forgot to include this in https://github.com/openxla/stablehlo/pull/1971 (made the change locally and forgot to push before merging).
I originally suppressed these lints because I misunderstood how `set -o errexit` interacts with `readonly`. I thought a failure would still bring down the whole script, but that's not the case. So instead of suppressing the lint, I fixed the issue.
=> Fix SC2155 issues

CMakeLists.txt, build_tools/build_mlir.sh
* Add ccache use for build_mlir.sh script
* Remove LLVM_CCACHE_BUILD which is not used and [deprecated ](https://discourse.llvm.org/t/llvm-ccache-build-is-deprecated/68431 ) (Although our use of it is not necessarily the LLVM's version)
Note: this change was pulled out of https://github.com/openxla/stablehlo/pull/1973
=> Add ccache by default when building MLIR

CMakeLists.txt
Based on feedback from
https://gitlab.kitware.com/cmake/cmake/-/issues/25649 removed the generator expression in favor of if statement.
Example output:
```
-- Building StableHLO with an installed MLIR
-- Using MLIRConfig.cmake in: /usr/local/google/home/fmzakari/code/github.com/openxla/stablehlo/build/../llvm-build/lib/cmake/mlir
-- Using LLVMConfig.cmake in: /usr/local/google/home/fmzakari/code/github.com/openxla/stablehlo/llvm-build/lib/cmake/llvm
-- Enabling LLD as the linker
-- Enabling split-dwarf build
-- Enabling GDB index in binary
-- Building with -fPIC
-- Configuring done (0.2s)
-- Generating done (0.1s)
-- Build files have been written to: /usr/local/google/home/fmzakari/code/github.com/openxla/stablehlo/build
```
=> Remove generator expression

stablehlo/reference/Ops.cpp, stablehlo/reference/Process.cpp, stablehlo/reference/Process.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/reference/ProcessGrid.h
The PR removes the use of `shared_ptr`s as it complicates the logic of `rendezvous`. Instead of relying on the use count of `shared_ptr`, I've added a variable to track the state separately instead. Now, there is no need to worry about the scope of the `shared_ptr`s and cleaning up resource before exiting.
Thanks @mlevesquedion for sharing code snippets offline to help simplify this!
=> Enhance rendezvous docs and fix race condition

build_tools/github_actions/lint_clang_format.sh, build_tools/github_actions/lint_shellcheck.sh, build_tools/github_actions/lint_whitespace_checks.sh
https://github.com/openxla/stablehlo/pull/1971 introduced a `shellcheck` lint. However, it also introduced some bugs due to adding quotes in a few places where word splitting was used.
Thanks to gleasonk@ for spotting this: https://github.com/openxla/stablehlo/pull/1976
As described in https://www.shellcheck.net/wiki/SC2086, quoting is generally preferable when expanding a variable. However, when building a command line it is better to create an array and then expand the array. When using a regular variable, quoting can actually lead to incorrect behavior: for example, given `x="file1 file2"`, `clang-format $x` will correctly call `clang-format` on `file1` and `file2`, however `clang-format "$x"` will call `clang-format` on a non-existent file called `file1 file2`.
The lint itself was …
=> Fix shellcheck issues

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/tests/TestUtils.cpp, stablehlo/transforms/StablehloCanonicalizeDynamism.cpp, stablehlo/transforms/StablehloLegalizeToVhlo.cpp, stablehlo/transforms/StablehloRefineShapes.cpp, stablehlo/transforms/VhloLegalizeToStablehlo.cpp, stablehlo/transforms/VhloToVersion.cpp
This is unlikely to give us performance gains since most of our passes run on modules anyway (so the initialization probably already occurs only once), but it is cleaner to separate the initialization of a pass from the actual running of the pass.
The code in `initialize` will run when the pass runs regardless of whether there is at least one instance of the target operation. However, modules are pretty much always present so this is unlikely to change anything.
=> Perform initialization in pass initialize method

BUILD.bazel, stablehlo/api/CMakeLists.txt, stablehlo/api/PortableApi.cpp
Less moving pieces. Will also get the QuantizationDialect registration that was added earlier.
We end up registering _some_ dialects that aren't needed in serialization, but the cost is likely not worth the duplication.
=> Refactor portable api to use main registration method

rfcs/20230704-dynamism-101.md
The current design of dynamism in MHLO and StableHLO has been practically useful. There are success stories of it connecting JAX, PyTorch and TensorFlow to a number of compilers, in a mix of research and production environments. This RFC aims to leverage existing support for dynamism in the StableHLO dialect, discuss improvements to the existing design and then formalize the improved design in the StableHLO opset.
The main challenge with writing this RFC was that it affects the entire opset. The current design involves a lot of corner cases, so it took about a year of practical evaluation by the author - primarily within JAX native serialization, but also correlating with other ongoing and prior projects - to distill the design into just a few general design principles. I think I'm happy …
=> Dynamism RFC

rfcs/20230622-quantized-reduction.md, rfcs/20230704-dynamism-101.md, rfcs/20231017-collective-broadcast.md
Usually we try to modify the "Status" line to show approved right before merging. Looks like we forgot to do that for a few RFCs. Updating accordingly.
=> Update status of approved and merged RFCs

docs/spec.md
The text refers to "the example program above", but said example is actually near the top of the file (thousands of lines above). The example is also longer than necessary for the purposes of illustrating execution order.
=> Add a simple example for execution order

stablehlo/dialect/ChloOps.td, stablehlo/dialect/StablehloOps.td
I noticed some duplication and wondered if it was possible to remove it. Then I stumbled upon this thread which provided a solution: https://discourse.llvm.org/t/how-to-add-new-content-to-extraclassdeclaration-in-subclasses/71537
The idea is to declare the common class declaration in the base class and concatenate it with the child-specific declarations.
In some cases, the field was being overriden only to be set to the same value as the parent. In such cases, I simply removed the override.
=> Avoid duplicating extra class declarations

docs/status.md, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/ProcessGrid.cpp, stablehlo/tests/interpret/collective_broadcast.mlir
=> Add interpreter for CollectiveBroadcastOp

stablehlo/tests/interpret/all_gather.mlir, stablehlo/tests/interpret/all_reduce.mlir, stablehlo/tests/interpret/all_to_all.mlir, stablehlo/tests/interpret/collective_permute.mlir, stablehlo/tests/interpret/infeed.mlir, stablehlo/tests/interpret/outfeed.mlir, stablehlo/tests/interpret/partition_id.mlir, stablehlo/tests/interpret/reduce_scatter.mlir, stablehlo/tests/interpret/replica_id.mlir, stablehlo/tests/interpret/send_recv.mlir
As pointed out by @mlevesquedion in https://github.com/openxla/stablehlo/pull/1983#discussion_r1480049496, the symbol visibility is public by default, and making it implicit follows the precedent of other tests in this directory.
=> Use default visibility for symbols

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp
As an example, looking at the spec of `collective_broadcast`, we come across the statement:
`broadcast_in_dim(constant(0, element_type(result)), [], type(result))` otherwise.
This PR renames `makeScalar()` to `constant()` with arguments matching the spec above for parity.
=> Rename function to closely match spec

stablehlo/reference/Ops.cpp
This seems to be from https://github.com/openxla/stablehlo/pull/1987 (see https://github.com/openxla/stablehlo/actions/runs/7808382192/job/21298492956).
Not sure how presubmit failed to catch this. I think what happened is the following:
1. https://github.com/openxla/stablehlo/pull/1987 was uploaded and passed presubmit.
2. https://github.com/openxla/stablehlo/pull/1983 was submitted, adding a new use of `makeScalar`.
3. https://github.com/openxla/stablehlo/pull/1987 was submitted, deleting `makeScalar` and causing tests to fail at HEAD.
What I don't understand is why this sequence of operations is possible in the first place. I feel like when https://github.com/openxla/stablehlo/pull/1983 was submitted, the earlier passing presubmit on https://github.com/openxla/stablehlo/pull/1987 …
=> Use new constant function instead of deleted makeScalar function

stablehlo/dialect/TypeInference.cpp
The `hasDuplicates` function was originally factored out because it is used frequently. However it was still defined as lambda, so I've updated it to be a function.
There was also an unnecessary conversion to a vector (the underlying data does not change), so I've removed the conversion too.
=> Convert lambda call to a function call

stablehlo/dialect/TypeInference.cpp
With the recent change to rename a function to match spec in #1987, I noticed that several ops also rely on this meta function that can also benefit from name change.
=> Rename function to match spec

README.md
Users building the project by following the README may not need the Python bindings, so we shouldn't recommend building them by default.
#2001
=> Set Python bindings to OFF by default

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
Verification of `dynamic_broadcast_in_dim` does not address the event when the operand is of unranked type and crashes instead on nullptr dereference.  
The PR fixes the issue and adds a relevant test to highlight the problem.
=> Fix verification of DynamicBroadcastInDimOp to handle unranked operand

docs/spec.md
closes https://github.com/openxla/stablehlo/issues/1574
The PR implement the spec changes to support per-axis quantization scheme for `add` and `dot_general` ops. Here is the rationale for the support:
- For `add` op:  Used for bias addition following convolution. Bias and [convolution op](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#semantics-25) outputs can  both be per-axis quantized and have the same shape, and same quantization parameters, but current `stablehlo.add` only support per-tensor quantized scheme. [Relevant dicussion](https://github.com/openxla/stablehlo/issues/1574#issuecomment-1659466321)
- For `dot_general`:  Some uses cases of quantized models requires  support for a mixed quantization scheme where it accepts per-tensor quantized `lhs` and per-axis …
=> Per-axis specification for `dot-general` and `add`

stablehlo/tests/vhlo/vhlo_to_version_downgrade_invalid.0_16_0.mlir
This is covered by the invalid 0.17.0 test, don't need it in both. We tend to only have the illegal downgrade test at the boundary where it would occur
=> Remove redundant downgrade test

stablehlo/dialect/VhloOps.cpp
As pointed by @abhigunj , having this mismatch is confusing.
=> Align the definition of `checkIfOperandAndResultElementTypesMatch` with its name

.github/workflows/lint.yml, build_tools/github_actions/ci_build_bazel.sh, build_tools/github_actions/ci_build_cmake.sh, build_tools/github_actions/ci_build_cmake_code_coverage.sh, build_tools/github_actions/ci_build_cmake_llvm.sh, build_tools/github_actions/ci_build_python_wheel.sh, build_tools/github_actions/lint_clang_format.sh, build_tools/github_actions/lint_llvm_commit.sh, build_tools/github_actions/lint_markdown.sh, build_tools/github_actions/lint_version.sh, build_tools/github_actions/lint_whitespace_checks.sh, build_tools/github_actions/llvm_gcov.sh
"Bash strict mode" is a colloquial expression for a set of settings that
makes Bash stricter (safer). See e.g. https://gist.github.com/robin-a-meade/58d60124b88b60816e8349d1e3938615
TLDR: to avoid errors from being silently ignored, we should set errexit
(exit script on error), nounset (exit script when an undefined variable
is encountered) and pipefail (propagate error codes in pipelines) in all
our scripts.
Unfortunately, `errexit` is in fact not enough to exit when any error
occurs, some errors are swallowed: https://dev.to/banks/stop-ignoring-errors-in-bash-3co5
Because of this, I changed the whitespace script to gather the files in
a different way (I copied the approach from the clang-format script), such
that the script will exit when an error occurs, instead of continuing to run. …
=> Use bash strict mode in all CI scripts

.github/workflows/lint.yml, build_tools/github_actions/lint_check_license.sh
addlicense is not maintained and is not extensible. find and grep are sufficient for our use case. Note that what the new script is doing is basically equivalent to addlicense:
- Find files that may need licenses: https://github.com/google/addlicense/blob/4caba19b7ed7818bb86bc4cd20411a246aa4a524/main.go#L197
- Look for a license: https://github.com/google/addlicense/blob/4caba19b7ed7818bb86bc4cd20411a246aa4a524/main.go#L372
Unfortunately, addlicense only handles files with extensions it knows about, and there is no way to specify additional extensions: https://github.com/google/addlicense/blob/4caba19b7ed7818bb86bc4cd20411a246aa4a524/main.go#L163
I believe the reason for this is that addlicense can also add licenses to files automatically, which requires knowing e.g. what is the comment …
=> Replace addlicense with find and grep

docs/spec.md
The way the spec is currently written, a function input would be written e.g. `%%arg0` instead of `%arg0`.
=> Remove extra % prefix for function inputs

stablehlo/dialect/StablehloOps.td
This only concerns a few ops, but it avoids having to specify an empty list when an op has no traits.
=> Default stablehlop op traits to empty list

build_tools/github_actions/lint_check_license.sh
Unblocks #2029
I ran the license checker with `find` as input instead of `git diff` to find all the relevant files and exempted the files that don't already have licenses.
=> Ignore all files that shouldn't have licenses

build_tools/github_actions/lint_clang_format.sh
The version of clang-format available in CI seems to be different from the one on my machine, but I can't easily see what the version of clang-format running in CI is, so I can't really debug. Print the version so that moving forward if someone runs afoul of the check they can repro and fix.
=> Print clang-format version in CI

build_tools/github_actions/lint_check_license.sh
When I added the script in https://github.com/openxla/stablehlo/pull/2018, I bootstrapped it from a script that didn't use strict mode. Around the same time, I sent https://github.com/openxla/stablehlo/pull/2012 for review, but forgot to apply the change to this new script as well.
Also, change the condition on whether UNLICENSED_FILES contains any
elements to avoid triggering nounset.
=> Use bash strict mode in license check script

stablehlo/dialect/Base.cpp, stablehlo/dialect/TypeInference.cpp
Let's use `TensorType::clone` which is customized to create TensorType variants (`RankedTensorType` and `UnRankedTensorType`).
=> Simplify creation of `TensorType`  variants using `TensorType::clone`

.github/workflows/buildAndTestBazel.yml
Improve caching key based on [documentation](https://github.com/actions/cache/blob/a2ed59d39b352305bdd2f628719a53b2cc4f9613/examples.md?plain=1#L673)
* key hashes the relevant files that can cause variance
* removed LLVM version in the key since it's already in the WORKSPACE file
* added `restore-keys` which hydrates another cache for potential re-use
=> Improve caching keys for Bazel

.github/workflows/buildAndTestBazel.yml
Fix incorrect prefix in the restore-keys for the GitHub action for bazel builds.
=> Fix incorrect restore-key in cache action

stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_quantized.mlir
StableHLO OPs supporting Quantization can be categorized into following three types
a. Only PerTensor Quantized Tensors
b. Only PerAxis Quantized Tensors (no OP in this category for now)
c. Both PerTensor and PerAxis Quantized Tensors
PerAxis constraint from the PR allow only PerTensorQuantized Tensor inputs to type (a) OPs  and don't allow  PerAxis Quantized Tensors. 
Also,
Added negative test cases to validate this behavior
Added positive test cases for PerTensor , PerAxis Quantized Tensor support
Excluded OPs 
* Deprecated :`BroadCast` and `Call`
* Not Specced :  
 `dynamic_iota`, `create_token`, `dynamic_broadcast_in_dim`, `cross-replica-sum`, `einsum`, `unary_einsum`, `dynamic_reshape`, `set_dimension_size`, `trace`, `return`, `torch_index_select`, `real_dynamic_slice`, …
=> Introduce PerAxis Quantized constraint for StableHLO Quantized OPs

stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo.mlir
Custom call op permits just about everything: Tuple, Tensor, Token, Unranked, all quantization, etc. This change restores its ability to operate on unranked tensors.
This was squashed in a merge conflict between #2045 and #2007. Adding a testpoint to avoid this issue going forward.
=> Allow CustomCallOp to have unranked tensor operands and results

stablehlo/dialect/Base.td, stablehlo/tests/ops_stablehlo_quantized.mlir
Current StablehLO quantized signed int [cs](https://github.com/openxla/stablehlo/blob/4a26ddee5fdbe178a84f219513bfc48f565919b7/stablehlo/dialect/Base.td#L60) uses `mlir::quant::QuantizedType::isSIgned` to decide on the signed-ness of the storage type.
StableHLO, as bootstrapped from MHLO, inherits `signless` integers (added in MHLO for some legacy reasons) to be treated as signed integer. This is not captured by the check `mlir::quant::QuantizedType::isSigned` because of the following reason.
Based on [this](https://github.com/llvm/llvm-project/blob/16e74fd48988ac95551d0f64e1b36f78a82a89a2/mlir/include/mlir/Dialect/Quant/QuantTypes.h#L102), `mlir::quant::QuantizedType::isSIgned()` is true if the associated bit in [flag](https://github.com/llvm/llvm-project/blob/16e74fd48988ac95551d0f64e1b3 …
=> Check quantized-storage-type to be a signless integer

docs/spec.md, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo_quantized.mlir
~~DynamicBroadcastInDimOp:  is yet to be a part of spec.~~ (see comments)
GetDimensionSizeOp: will be changed to quantized types in spec. 
Back porting from the integration as file check tests were failing for both.
=> GetDimensionSizeOp : make arguments quantized type

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
`DotOp` currently doesn't have shape refinement, so if downstream exports stablehlo with dot, and it contains unbounded dynamic shapes with `stablehlo.dot`, it fails to refine shape.
This change enables refinement, and prevents users from having to transform `dot` back to `dot_general` whenever canonicalization pass (for `dot_general` to `dot`) is run implicitly.
=> Add shape refinement pass for DotOp

stablehlo/tests/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/StablehloAggressiveSimplification.cpp
I wanted to read this pass to familiarize myself with the code. In passing, I made a few readability improvements here and there and while making these I realized that we did not import the tests for this code. Import the tests so we can have some confidence when making changes.
The tests are from https://github.com/openxla/iree/blob/7782a414ea473c59f6d7a882cb510690ed666c79/compiler/plugins/input/StableHLO/stablehlo-iree/Conversion/Preprocessing/test/canonicalization.mlir, with minor tweaks (formatting, reordering tests to match the implementation, and adding missing test separators).
=> Clean up aggressive simplification and add tests

stablehlo/tests/shape_legalize_to_stablehlo.mlir, stablehlo/transforms/ShapeLegalizeToStablehlo.cpp
Add patterns in ShapeLegalizeToStablehlo for tensor::ExtractOp
1. Add support for tensor.Extract, which is lowered to mhlo.slice
2. Support a special case from TF graph:
tensor.extract tensor<?xi32> -> i32
arith.index_cast i32 -> index
This is lower to:
mhlo.slice tensor<?xi32> -> tensor<1xi32>
mhlo.reshape tensor<ixi32> -> tensor<i32>
unrealized_conversion_cast tensor<i32> -> i32
unrealized_conversion_cast i32 -> tensor<i32>
unrealized_conversion_cast tensor<i32> -> index
=> Add patterns in ShapeLegalizeToStablehlo for tensor::ExtractOp

stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo_quantized.mlir
ref: https://github.com/openxla/stablehlo/pull/2059 for background.
For now we are aligning with BroadcastInDimOp spec. It will be further reviewed during speccing the DynamicBroadcastInDimOp.
=> DynamicBroadcastInDimOp make arguments per-axis quantized

CMakeLists.txt, examples/CMakeLists.txt, examples/c++/BUILD.bazel, examples/c++/CMakeLists.txt, examples/c++/README.md, examples/c++/stablehlo_add.cpp
Add the beginnings of an `examples` directory structure that will help demonstrate how to use the StableHLO library.
At the moment I've only added a c++ example, and a simple one at that but the directory structure should indicate that we can support Python in the future.
* Added a meta library 'stablehlo_lib' that you can link against which should eventually include everything
* Added the add stablehlo example
* Added a simple README
```console
❯ ./build/examples/c++/stablehlo-add
module @test_module {
func.func @main(%arg0: tensor<3x4xf32>, %arg1: tensor<3x4xf32>) -> tensor<3x4xf32> {
%0 = stablehlo.add %arg0, %arg1 : tensor<3x4xf32>
%1 = stablehlo.add %arg0, %arg1 : tensor<3x4xf32>
return %1 : tensor<3x4xf32>
}
}
```
=> Add examples directory

stablehlo/tests/ops_stablehlo.mlir
This mirrors the checks we have for VHLO in
`stablehlo_legalize_to_vhlo.mlir`.
Emitting StableHLO bytecode should not emit such warnings either.
=> Ensure emitting bytecode does not yield warnings

BUILD.bazel, stablehlo/integrations/python/CMakeLists.txt, stablehlo/integrations/python/StablehloModule.cpp, stablehlo/integrations/python/tests/stablehlo.py, stablehlo/reference/Api.cpp, stablehlo/reference/Api.h, stablehlo/reference/CMakeLists.txt, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/tools/StablehloTranslateMain.cpp
```py
ASM = """
func.func @test(%arg0: tensor<2x2xf16>) -> tensor<2x2xf16> {
%0 = stablehlo.add %arg0, %arg0 : (tensor<2x2xf16>, tensor<2x2xf16>) -> tensor<2x2xf16>
func.return %0 : tensor<2x2xf16>
}
"""
m = ir.Module.parse(ASM)
arg = np.asarray([1, 2, 3, 4], np.float16).reshape(2,2)
args = [ir.DenseIntElementsAttr.get(arg)]
res = stablehlo.eval_module(m, args)
```
- Added python API for reference interpreter, and test cases for int/float datatypes
- Added reference API which takes DenseElementsAttrs to be used by python API
- Added method to convert between `stablehlo::Tensor` and `mlir::DenseElementsAttr` more easily (only supports int/float types)
- Added more error checking at interpreter entry point to improve UX
- Changed error reporting at API boundary from `llvm::Error` to …
=> Add a python API for reference interpreter

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo_quantized.mlir
Previous check was restrictive and causing test failures during integration.
=> ConvolutionOP verifier : allow rhs per_axis quantized and result per_tensor quantized

.github/workflows/buildAndTestCMake.yml
Seems the image itself has a bug: https://github.com/actions/runner-images/issues/9491.
Apply this patch from https://github.com/actions/runner-images/issues/9491\#issuecomment-1989718917 to fix the issue while we wait for a new version of the image to roll out.
Fixes https://github.com/openxla/stablehlo/issues/2106
=> Fix asan build issue

stablehlo/integrations/python/StablehloModule.cpp
because that the lambda's signature is `[](MlirContext context, std::string artifact)`.
=> fix typo of py args

stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/infer_stablehlo.mlir
The `ReverseOp` did not implement a `reifyReturnTypeShapes`.  This resulted in a failed assertion in the `getEmptyTensorFor` helper function that gets used during the `stablehlo-legalize-to-linalg` pass when the op has dynamic input/output.  This patch implements this function as well as adds a test for the newly supported case (input can have dynamic dims as long as they don't correspond to the `dims` attribute of the op)
Various other quality of life changes, such as having match failure notifications have been added.
=> Fix failed reify for ReverseOp

BUILD.bazel, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/StablehloRefineShapes.cpp
Edit: Sure, sorry for missing description.
Currently our small research team experimenting with BERT model represented in number of *-hlo dialects and wants to simplify it in terms of variety of operators. This PR fixes an issue we stumbled upon:
```
%42 = stablehlo.constant dense<"..."> : tensor<1x512xi64>
...
%66 = stablehlo.slice %42 [0:1, 0:128] : (tensor<1x512xi64>) -> tensor<1x128xi64> 
```
Previous implementation of EvalSlice can't handle such case -- tensor type prefixed with unit dimension(s) i.e. 1x128.
This PR adds support of the above case and can slice from any position, e.g.
```
%0 = stablehlo.constant dense<[[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]]> : tensor<1x3x2x2xi64>
%1 = "stablehlo.slice"(%0) {
start_indices = array<i64: 0, 1, 1, 0>,
limit_indices = …
```
=> Add support of tensor types with unit dimension prefix in EvalSlice

docs/spec.md, stablehlo/dialect/StablehloOps.td
As pointed out in https://github.com/openxla/stablehlo/pull/2097#discussion_r1534620186, MLIR doesn't insert spaces between the brackets and the content. I've also made minor formatting improvements.
=> Fix formatting on spec examples

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/StablehloOps.td, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
This enables specialization of stablehlo.compute_reshape_shape operator that operates on constant data:
```
func.func @test() -> (tensor<4xi32>, tensor<1xi32>) {
%0 = arith.constant dense<[2, -1, 2, 64]> : tensor<4xi32>
%1 = arith.constant dense<[-1]> : tensor<1xi32>
%2 = arith.constant 32768 : index
%3 = stablehlo.compute_reshape_shape %2, %0 : (index, tensor<4xi32>) -> tensor<4xi32>
%4 = stablehlo.compute_reshape_shape %2, %1 : (index, tensor<1xi32>) -> tensor<1xi32>
func.return %3, %4 : tensor<4xi32>, tensor<1xi32>
}
```
is transformed into:
```
func.func @test() -> (tensor<4xi32>, tensor<1xi32>) {
%0 = stablehlo.constant dense<[2, 128, 2, 64]> : tensor<4xi32>
%1 = stablehlo.constant dense<32768> : tensor<1xi32>
return %0, %1 : tensor<4xi32>, tensor<1xi32>
}
```
=> Add specialization of ComputeReshapeShapeOp

stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo_quantized.mlir
Reverts openxla/stablehlo#2094. Adding verification for this change will be done as a part of hybrid quantization PRs.
=> Revert "ConvolutionOP verifier : allow rhs per_axis quantized and result per_tensor quantized"

examples/c++/BUILD.bazel, examples/c++/CMakeLists.txt, examples/c++/ExampleAdd.cpp, examples/c++/README.md, stablehlo/reference/CMakeLists.txt
Augmented the example test with interpreter usage demo.
nit: Fixed the dependency of `MLIRParser` on `StablehloReferenceApi` as API.cc uses `parseSourceFile`.
=> Augment example test with interpreter usage

stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgPointwise.cpp, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll, stablehlo/dialect/Base.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_reduce.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
These checks are no longer necessary in most cases (they are still necessary in some cases, e.g. when dealing with custom call args/results or CHLO op args/results).
I plan to make further cleanups in future PRs, e.g. in ShapeRefinement.cpp (in this PR I did only the obvious ones). Also I plan to clean up casts, especially casting to `ShapedType` instead of `RankedTensorType`.
#1991
=> Clean up hasRank checks

build_tools/github_actions/lint_whitespace_checks.sh
The root cause of #2129 is that Python files (ending in `.py`) were excluded from the whitespace check. I originally proposed expanding the list of included files to include Python files, but @ghpvnist pointed out that there are more files that need this check than files that don't and suggested using an exclude list, so I did that instead.
Also, use `-E` and rewrite the pattern to allow the exclude list to be expanded more easily in the future.
Fixes #2129
=> Check whitespace in all files except bytecode and image/vector files

examples/c++/BUILD.bazel
All of our build target names are snake case. The only exceptions are `stablehlo-opt`, `stablehlo-lsp-server`, and `stablehlo-translate` which were named such to follow MLIR style for passes.
=> Update `BUILD.bazel` target name

stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td, stablehlo/tests/ops_chlo.mlir, stablehlo/tests/ops_chlo_roundtrip.mlir
(P1) of the Dynamism RFC.
These ops are no longer used by KernelGen and can safely be deleted.
=> Delete rank_specialization_cluster ops

build_tools/github_actions/lint_markdown.sh
I haven't used docker in a while, so I forgot what -v meant. In general, it is a good idea to use long form flag names in shell scripts for readability.
=> Use long form volume flag for docker run

stablehlo/dialect/TypeInference.cpp
The check is already enforced by the [tablegen declaration](https://github.com/openxla/stablehlo/blob/f392f5fcae12ef445e18eef921720b3313336c38/stablehlo/dialect/StablehloOps.td#L2514)
=> Remove redundant static result shape check on reshape

docs/spec.md
This implements part 1 of (P2) from the Dynamism 101 RFC: https://github.com/openxla/stablehlo/blob/main/rfcs/20230704-dynamism-101.md#-p2-ratify-the-existing-convention-for-shape-mismatches-constituting-undefined-behavior
In a future change, I will implement `ConditionallySpeculatable` where relevant. Many ops have the `Pure` trait but they are not actually `Pure` in all cases because shape mismatches are undefined behavior.
#1991
=> Add spec warning about shape mismatches

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/print_types_invalid.mlir, stablehlo/tests/stablehlo_refine_shapes.mlir
AddOP allows mix of `per-tensor` and `per-axis` inputs. Existing StableHLO AddOp def uses `HLO_CompatibleOperandsAndResultType` Trait which does not allow mix of `per-tensor` and `per-axis` inputs. 
This PR:
removed HLO_CompatibleOperandsAndResultType Trait for AddOP
Added custom Verifier to implement OP constraints
Thank you @sdasgup3  for the help with debugging builder issues after removal of `HLO_CompatibleOperandsAndResultType` suggestion for  `inferReturnTypes` placement.
=> AddOp: Remove HLO_CompatibleOperandsAndResultType Trait, add custom verifier

stablehlo/dialect/StablehloOps.td
~~New trait for StableHLO ops. Trait tries to match `scale` and `zero_point` of per-tensor quantized `operands` and `result`.~~
~~Initially I added checks at custom verifiers for few ops but there are ops without verifier. Adding a Trait is less code/custom verifier changes.~~
This PR adds SameOperandsAndResultElementType  Trait for applicable ops with `type(operand...) = type(result..) ` constraint. 
Total Three OPs  : `collective_broadcast` , `collective_permute`, `reverse`
Testing: positive tests already exist for these ops. Negative tests: since this is a  native mlir Trait and not custom verifier, skipped negative testing. 
There is a overlap of verifications  done by SameOperandsAndResultElementType and HLO_comp.. For now we will keep both the Traits. I will create a follow up …
=> Add SameOperandsAndResultElementType Trait for type(operand) = type (result) ops 

rfcs/20231005-hybrid-quantization.md
This RFC proposes to add hybrid quantized convolution and dot_general for weight-only quantization.
Please let me know your feedback on this.
The RFC partially address the issue https://github.com/openxla/stablehlo/issues/1575 w.r.t supporting weight only quantization support in StableHLO. The remaining tasks for the above the are highlighted [here](https://github.com/openxla/stablehlo/issues/1575#issuecomment-1819957802).
=> [RFC] Add hybrid quantized convolution and dot_general for weight-only quantization

stablehlo/conversions/linalg/tests/sparse.mlir, stablehlo/conversions/linalg/transforms/Passes.td, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
After StableHLO => Linalg lowering was implemented in the [linalg RFC](https://github.com/openxla/stablehlo/pull/1610), most of the ops stated by @aartbik in the [sparsity RFC](https://github.com/openxla/stablehlo/pull/1143) can generate correct linalg code with sparse encodings. And it can then be lowered through mlir-opt with --sparsifier pipeline and run with mlir-runner. 
The `sparse.mlir` file in this PR checks the generated linalg code with sparse encodings. These are the same tests for the dense ops but with sparse input/output.
The only op that couldn't be lowered to correct linalg with sparsity is `stablehlo.concatenate`. Therefore, after discussing with @GleasonK, I added a flag `enable-sparse-ops` to the linalg pass and rewrite `stablehlo.concatenate` to …
=> Support sparsity through StableHLO => Linalg lowering

BUILD.bazel, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Note: this PR builds on top of https://github.com/openxla/stablehlo/pull/2146. Please see the 2nd commit for changes that are unique to this PR.
A somewhat unfortunate thing is that we allow programs like:
```
func.func @foo(%arg: tensor<?xi64>) {
%0 = stablehlo.abs %arg : (tensor<?xi64>) -> tensor<2xi64>
return
}
```
Such a program is legal, but doesn't make much sense: in what scenario would we know the output shape, but not the input shape? If it weren't for such programs, the ops would all be `Pure`, but because at runtime dynamic dimensions in the input type could differ from static dimensions in the output type, these ops have to be `ConditionallySpeculatable`. Whether or not we should allow such programs could be a future discussion.
Also note that the spec asserts that floating …
=> Implement ConditionallySpeculatable for all UnaryElementwise ops

BUILD.bazel, stablehlo/dialect/CMakeLists.txt, stablehlo/dialect/StablehloBytecode.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h
This enables (at least) invalidating previously generated StableHLO bytecode serialization (not using VHLO) by bumping the version. The version is optionally set and if not set, not serialized - this would result in no changes to what is serialized by default today unless explicitly set.
This would enable a better error message than the existing where a loaded bytecode would fail and knowledge required as to why:
Before 
```
<unknown>:0: error: 'stablehlo.broadcast_in_dim' op attribute 'broadcast_dimensions' failed to satisfy constraint: either a DenseI64ArrayAttr or a 1-dimensional I64ElementsAttr.
<unknown>:0: note: see current operation: %4 = "stablehlo.broadcast_in_dim"(%1) {broadcast_dimensions = array<i64>} : (tensor<f32>) -> tensor<500xf32>
<unknown>:0: note: in bytecode version 6 …
```
=> Add StableHLO dialect version for bytecode

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Note that e.g. in C/C++ a few ops similar to our ops have undefined behavior
under some circumstances:
- Integer division/remainder by 0
- Integer division of INT_MIN by -1
- Signed integer overflow (as can occur through e.g. addition)
Our spec does not specify any undefined behavior in such cases, so I did not take them
into account while making this change. IMO, such issues may be worth
some discussion, and they can be handled later, since the current change
focuses on shape mismatches. Also, this change does not introduce any
unsoundness that wasn't there before, since these ops were marked
"Pure" until now.
https://github.com/openxla/stablehlo/issues/1991
=> Implement ConditionallySpeculatable for all Binary*Elementwise ops

BUILD.bazel
I don't understand why this isn't failing in CI, but I can't build this target since 2a0595bd3, and a few others have reported the same for their local builds.
In any case, the code `#include`s SideEffectInterfaces.h, so its target should depend on the corresponding BUILD target.
Filed https://github.com/openxla/stablehlo/issues/2155 for follow-up.
=> Add missing dependency to chlo_ops target

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_quantized.mlir
This PR add/update verifiers for ops to verify quantization specific constraints
OPs:  `bitcast_convert` `broadcast_in_dim` `transpose` `reshape`  `sort` `select` `abs`
~`dot_general`~  dropping dot_general verifier changes due to expected internal test failures similar to https://github.com/openxla/stablehlo/pull/2122
=> Quantization Verifiers : Add/update custom verifiers for quantized constraints

docs/spec.md, docs/status.md, stablehlo/reference/Index.cpp, stablehlo/reference/Index.h, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/tests/interpret/convolution.mlir, stablehlo/tests/interpret_convolution.mlir
Since the interpreter implementation is already a mouthful, I've split #1314 to separate the implementation from the remaining checklist items. Once this is merged, I'll work on the remaining to update the rest of the docs.
closes #970
=> Add interpreter for ConvolutionOp

docs/spec.md
The op is slated for removal, but unlike other ops in a similar position it currently isn't mentioned in the spec.
=> Mention trace in spec

stablehlo/dialect/StablehloOps.td
The spec says: https://github.com/openxla/stablehlo/blob/a053baba039d6d9f9cf11abd8c9555cc055144de/docs/spec.md?plain=1#L1584-L1585.
We could try to see if the inputs are constant and then try to determine if they are Hermitian positive-definite, and only then report that the op is speculatable, but that seems like a heavy check for a situation that isn't likely to occur frequently, so IMO it is more reasonable to say that this op is not speculatable.
Pure is "NoMemoryEffect + AlwaysSpeculatable". If an op doesn't implement ConditionallySpeculatable, then it is never Speculatable, so we replace Pure with NoMemoryEffect, because this op doesn't have memory effects.
=> Remove Pure trait from Cholesky

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Also, rework "UnaryElementwiseSpeculatable" to be more descriptive and more generic: the relevant condition is "every static dimension in the output is static in the input".
=> Implement ConditionallySpeculatable for a few unary ops

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Also, rework "BinaryElementwiseSpeculatable" trait to be more descriptive and more generic: the relevant condition is "are all the inputs statically shaped".
=> Implement ConditionallySpeculatable for BatchNorm* ops

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
If `a` is constant, we could check the diagonal to confirm that it
is unit, but this may be costly and should go in the op's verifier.
=> Implement ConditionallySpeculatable for TriangularSolve

stablehlo/dialect/StablehloOps.td
In https://github.com/openxla/stablehlo/pull/2162 I added an extraDeclaration for this op but forgot to concatenate the common decl.
=> Add missing ReshapeOp common decl

stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp
Due to a problem with the compilation options, the `shapeSource.reifyReturnTypeShapes` was not called, fix it.
=> Avoid calling functions in asserts

docs/reference.md
This was missed in https://github.com/openxla/stablehlo/pull/2180
=> Fix deprecated uses of cast/dyn_cast in docs

stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/chlo/chlo_legalize_to_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
Part of #1584. Last step is to migrate CHLO.
Regarding use of adapters in `reify` functions, see the following code comment which talks about why operands (and only operands) must be passed as arguments:
```
::mlir::LogicalResult inferReturnTypeComponents(::mlir::MLIRContext* context, ::std::optional<::mlir::Location> location, ::mlir::ValueShapeRange operands, ::mlir::DictionaryAttr attributes, ::mlir::RegionRange regions, ::llvm::SmallVectorImpl<::mlir::ShapedTypeComponents>& inferredReturnShapes);
/// Reify the shape computation for the operation.
/// 
///       Insert operations using the given OpBuilder that computes the
///       result shape. This interface is supposed to be workable during dialect
///       conversion (e.g. convert from tensor world to buffer world),
/// …
```
=> Migrate StableHLO to use properties

stablehlo/dialect/ChloOps.cpp, stablehlo/dialect/ChloOps.td
Migrate CHLO to use properties.
1. Use adaptors when possible to avoid needing to think about attrs vs properties.
2. Avoid using `get("string")` as in `attributes.get("broadcast_dimensions")` to get property values.
Closes #1584
=> Migrate CHLO to use properties

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/infer_stablehlo.mlir
for `collective_broadcast` and `collective_permute` ops,  `HLO_CompatibleOperandsAndResultType` trait is no longer required. `SameOperandsAndResultElementType` is covering  `(C3) type(result) = type(operand)` constraints. Previously  `HLO_CompatibleOperandsAndResultType` trait was defining type and shape inference functions. This PR removes `HLO_CompatibleOperandsAndResultType` for the OP and copied-out required inference functions.
Tested:
1. return type inference is ok. Added test to infer_stablehlo.mlir  to validate. 
2. no builder errors
ref: https://github.com/openxla/stablehlo/issues/2145
=> collective_broadcast, collective_permute : remove HLO_CompatibleOperandsAndResultType trait 

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h
for `reverse`, `HLO_CompatibleOperandsAndResultType` trait is no longer required. `SameOperandsAndResultElementType` is covering (C3) type(result) = type(operand) constraints. Previously `HLO_CompatibleOperandsAndResultType` trait was defining type and shape inference functions. This PR removes `HLO_CompatibleOperandsAndResultType` for the OP and copied-out required type inference function.
`reverse` op is a `StableHLO_ShapedInterfaceOp` so shape inference already handled.
Tested:
existing shape and type inference tests passed
fixes https://github.com/openxla/stablehlo/issues/2145
=> ReverseOp : remove HLO_CompatibleOperandsAndResultType trait

stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/TestUtils.cpp, stablehlo/tests/ops_speculatability.mlir
All of these ops have `same(shape(inputs...))` as a constraint,
but they also have regions, so if all their inputs are static, the
op is recursively speculatable.
(Note that `scatter` also has this constraint, but it can have UB
in other circumstances so it will be handled in a follow-up change.)
=> Implement ConditionallySpeculatable for Map, Reduce and ReduceWindow

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/shape_legalize_to_stablehlo.mlir, stablehlo/tests/stablehlo_canonicalize_dynamism.mlir
To make it easier to debug differences is non-constant operations, even if constants are different
=> Add prettier printing for constant operations

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgReduce.cpp, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/TypeInference.cpp
For type inference, if the infer/verify logic were a method on the op itself, we could remove the cast altogether, but with the current setup we can at least change dyn_cast into cast to remove any ambiguity and clean up redundant checks.
In some cases it's not possible to remove the dyn_casts, for various reasons:
- CHLO ops still allow RankedTensorType
- Some dyn_casts are used on things that may not be tensors
https://github.com/openxla/stablehlo/issues/2065
=> Use cast instead of dyn_cast where possible

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgConvolution.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp, stablehlo/dialect/StablehloOps.cpp
I revisited all the casts to ShapedType and RankedTensorType in light of the fact that most op input/output types are ranked and removed unnecessary casts.
This PR is sort of an extension of https://github.com/openxla/stablehlo/pull/2183
Also simplified a few `op.getResult().getType()` to `op.getType()` because I was modifying that code anyway.
Fixes https://github.com/openxla/stablehlo/issues/2065
=> Remove unnecessary {RankedTensor,Shaped}Type casts

stablehlo/dialect/VhloOps.td
We haven't needed to use this yet, but without this change it would create invalid code like `return mlir::vhlo::Version("0, 10, 0");`.
=> Remove extra quotes in getMaxVersion template

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
The logic is the same as for unary ops, except that if the type of FFT is RFFT or IRFFT then the last `fft_length.size()` dimensions in the operand need to be static (for speculatability), because there are extra constraints on them that could turn out to be false at runtime if they are dynamic.
Indeed, there is a general constraint that `shape(result) = shape(operand)`. For RFFT, the operand type element type is float, so the last `fft_length.size()` dims in the operand have to be static, because `fft_length` is static (it is an attribute). For IRFFT, the result element type is float, so the last `fft_length.size()` dims in the result are inferred from the `fft_length`, and they need to match the operand, so those dims have to be static in the operand. There are also constraints on the …
=> Implement ConditionallySpeculatable for Fft

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Relevant constraints from the spec:
```
(C10) dim(lhs, input_batch_dimension) % batch_group_count = 0.
(C11) dim(lhs, input_feature_dimension) % feature_group_count = 0.
(C14) dim(rhs, kernel_input_feature_dimension) = dim(lhs, input_feature_dimension) / feature_group_count.
(C15) dim(rhs, kernel_output_feature_dimension) % batch_group_count = 0.
(C16) dim(rhs, kernel_output_feature_dimension) % feature_group_count = 0.
(C25) dim(result, result_dim) is defined as:
* dim(lhs, input_batch_dimension) / batch_group_count if result_dim = output_batch_dimension.
* dim(rhs, kernel_output_feature_dimension) if result_dim = output_feature_dimension.
* num_windows otherwise, where:
* output_spatial_dimensions[spatial_dim] = result_dim.
* lhs_dim = input_spatial_dimensions[spatial_dim].
* rhs_dim = …
```
=> Implement ConditionallySpeculatable for ConvolutionOp

docs/spec.md
fixes https://github.com/openxla/stablehlo/issues/2205
Requesting the following for review:  
@loganchien
@paulinesho
@doyeonkim0
=> Relax constraint `num_bits(storage_type) < num_bits(expressed_type)`

stablehlo/dialect/StablehloOps.td
We changed these attributes to use DenseArray instead of DenseElements some time ago.
=> Use arrays for DynamicConv example

build_tools/github_actions/lint_check_license.sh, build_tools/github_actions/lint_whitespace_checks.sh, docs/_toc.yaml, docs/tutorials/jax-export.ipynb
See tutorial rendering using "View File" ([example](https://github.com/openxla/stablehlo/blob/f85d9fffc3d4e0fe4f09bfadd4739d09baaf60c1/docs/tutorials/jax-export.ipynb)).
Once merged the "Open in Colab" button should work. Also once integrated this should appear on the openxla.org documentation as well.
=> Tutorial: JAX Export to StableHLO

docs/_toc.yaml, docs/tutorials/jax-export.ipynb, docs/tutorials/pytorch-export.ipynb
View rich text GH rendering here: [pytorch-export.ipynb](https://github.com/openxla/stablehlo/blob/60adde95c9337ce031c91f3f3fb7e5b405f4cef0/docs/tutorials/pytorch-export.ipynb).
Includes "Open in Colab" URL fix for JAX tutorial.
=> Tutorial: PyTorch Export to StableHLO

README.md
We don't provide documentation on how to generate compile_commands.json and this could be a useful start. I left this flag out of CI since the CI doesn't need to generate this.
=> Add compile_commands flag to README

stablehlo/tests/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/StablehloAggressiveSimplification.cpp
This patch rewrites a comparison and selection combination that utilizes the same operands into a min/max operation:
```
func.func @test(%arg0: tensor<2xi32>, %arg1: tensor<2xi32>) -> (tensor<2xi32>, tensor<2xi32>) {
%0 = stablehlo.compare GE, %arg0, %arg1, SIGNED : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
%1 = stablehlo.compare LE, %arg0, %arg1, SIGNED : (tensor<2xi32>, tensor<2xi32>) -> tensor<2xi1>
%s0 = stablehlo.select %0, %arg0, %arg1 : (tensor<2xi1>, tensor<2xi32>, tensor<2xi32>) -> tensor<2xi32>
%s1 = stablehlo.select %1, %arg0, %arg1 : (tensor<2xi1>, tensor<2xi32>, tensor<2xi32>) -> tensor<2xi32>
return %s0, %s1 : tensor<2xi32>, tensor<2xi32>
}
```
transformed into:
```
func.func @test(%arg0: tensor<2xi32>, %arg1: tensor<2xi32>) -> (tensor<2xi32>, tensor<2xi32>) {
%0 = …
```
=> Add rewrite pattern into AggresiveSimplification that turns compare+select into min/max

stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h
This is part 2 of tackling #1049, making the function names shorter.
=> Remove "eval" prefix from ops

stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/infer_stablehlo.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/verify_conv.mlir
This is part 3 of #1964 to implement the remaining parts of #1314.
One notable change in TypeInference.cpp is (C27), whose verification differs whether element type is quantized.
We have the following constraints in the spec (excluding quantization-related constraints C28-C33):
```
(I1) `lhs` tensor.
(I2) `rhs` tensor.
(I3) `window_strides` 1-dimensional tensor constant of type `si64`.
(I4) `padding` 2-dimensional tensor constant of type `si64`.
(I5) `lhs_dilation` 1-dimensional tensor constant of type `si64`.
(I6) `rhs_dilation` 1-dimensional tensor constant of type `si64`.
(I7) `window_reversal` 1-dimensional tensor constant of type `i1`.
(I8) `input_batch_dimension` constant of type `si64`.
(I9) `input_feature_dimension` constant of type `si64`.
(I10) `input_spatial_dimensions` …
```
=> Update conv docs and tests per interpreter guideline

.github/workflows/publishWheelRelease.yml
We want to run all python tests before publishing a wheel. Running all tests has a TF dependency to run savedmodel tests.
See:
https://github.com/openxla/stablehlo/actions/runs/8807435054/job/24174472438
=> Add TF dependency to wheel build action

stablehlo/transforms/ChloLegalizeToStablehlo.cpp
Once we have c++20 support we should flip this to use `std::numbers::pi` from the `<numbers>` header.
=> Add header for M_PI to fix windows build failure on some systems

docs/tutorials/pytorch-export.ipynb
Colab by default ships with outdated versions of `torch` and `torchvision` (given that they just released a new version on 4/24/24). Adding this explicit upgrade to pip will keep these tutorials more stable.
Also it turns out that dynamic shape export wasn't backported into the 2.3 release cut, so while this does work at nightly, it still won't be tested in the 2.3 colab, updated wording to specify 2.4.
=> Update PyTorch example to support 2.3.0

stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
As discussed in
https://github.com/openxla/stablehlo/pull/2231#discussion_r1571148784, this will likely help with debugging shape mismatches.
=> Include output shape in shape mismatch error message

stablehlo/tests/ops_speculatability.mlir
Mostly, simplify redundant variable names, remove unnecessary ops in nested regions, and move ops around/add whitespace for readability.
=> Clean up op speculatability tests

stablehlo/tests/ops_speculatability.mlir
These ops are UnaryElementwise but they were missed in https://github.com/openxla/stablehlo/pull/2150
=> Add tests for uniform_{de,}quantize speculatability

README.md
The doc originally stated that the script preceding the instruction may have already built MLIR with python bindings, but that isn't true. I've included the actual command that builds with python bindings.
=> Include command to build StableHLO with python bindings

docs/spec.md
fixes #1627
Requesting the following for review:  
@loganchien
@paulinesho
@doyeonkim0
=> Fix the bitness of addition/subtraction in quantize op

docs/spec.md, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo_quantized.mlir
This PR adds spec for hybrid quantized op discussed in the [RFC](https://github.com/openxla/stablehlo/pull/1792) and implements verifier accordingly.
Please feel free to take a look. Thank you!
cc @sdasgup3 @loganchien @abhigunj
=> Add spec and verifier for quantized dot_general op

docs/spec.md
iota op spec doesn't define `result` but uses `result_index`.
=> iota op spec :  replace "result_index" with "output_index"

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_speculatability.mlir
Included ops:
- DynamicPad
- RealDynamicSlice
- DynamicConv
- DynamicGather
I refactored the logic to check speculatability for shaped ops to enable
reuse and allow ops with more than one shape-related operand to be
checked.
This should be the last change adding new speculatability
implementations. All the other ops are either done, pure, or
deprecated. I will confirm this shortly by reviewing the entire opset
and making sure everything is covered (I have been tracking progress in
a personal document).
=> Implement ConditionallySpeculatable for remaining dynamic ops

BUILD.bazel, stablehlo/integrations/python/tests/stablehlo.py, stablehlo/reference/Api.cpp, stablehlo/reference/CMakeLists.txt, stablehlo/transforms/PassPipelines.cpp, stablehlo/transforms/Passes.h
This PR adds a pass-pipeline to refine arguments and shapes of a program followed by [StablehloCanonicalizeDynamism](https://github.com/openxla/stablehlo/blob/main/stablehlo/transforms/StablehloCanonicalizeDynamism.cpp) to replace dynamic StableHLO ops with the corresponding static counterparts if applicable* (see note below).
The goal is to interpret dynamic programs after applying the above pipeline.
partially-fixes https://github.com/openxla/stablehlo/issues/2202
Note:
For a programs like
```
func.func @main(%arg0: tensor<?xf32>, %arg1: tensor<2xi64>) -> tensor<?x?xf32> {
%0 = stablehlo.dynamic_reshape %arg0, %arg1 : (tensor<?xf32>, tensor<2xi64>) -> tensor<?x?xf32>
return %0 : tensor<?x?xf32>
}
```
when applied through the above pass-pipeline with  static input shapes like …
=> Interpreter support for dynamic programs

stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloRefineShapes.cpp
Added test case which crashes before this change due to pattern application order.
There's probably some overly safe checks here (like checking that ops which cannot have dynamic output shapes - broadcast_in_dim / get_dimension_size) but there's no harm, and its safer if we ever add any additional constraints on result types that can be folded in the future.
=> Ensure result shape is static before folding

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
The method variant is deprecated.
=> Use free function instead of method for dyn_cast_or_null

stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/transforms/StablehloAggressiveSimplification.cpp
I think these were added after/during the first round of changes.
Context: https://github.com/openxla/stablehlo/pull/2180
=> Remove a few more deprecated method uses

BUILD.bazel, docs/spec.md, stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/Base.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/CMakeLists.txt, stablehlo/reference/InterpreterOps.cpp, stablehlo/tests/BUILD.bazel, stablehlo/tests/CMakeLists.txt, stablehlo/tests/CheckOps.cpp, stablehlo/tests/interpret/dynamic_iota.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/ops_stablehlo_quantized.mlir, stablehlo/tests/verify_reduce.mlir, stablehlo/tests/verify_reduce_window.mlir, stablehlo/tests/verify_scatter.mlir, stablehlo/tests/verify_select_and_scatter.mlir
fixes https://github.com/openxla/stablehlo/issues/2074
It seems there are some use-cases, like quantized reduce wanting to perform the body computation in a higher bitwidth, which avoids constraining and hence is not part of the verification checks.
```
(C1) num_bits(storage_type) < num_bits(expressed_type).
```
Added a ticket to address it separately https://github.com/openxla/stablehlo/issues/2205
=> Verify StableHLO Quantized Types

stablehlo/transforms/StablehloLegalizeCompositeToCall.cpp
This was added with the wrong license a while ago. I think I copied the license from StablehloAggressiveSimplication.cpp and changed the authorship and year, but didn't realize that the actual license designation was wrong.
=> Use correct license for LegalizeCompositeToCall

stablehlo/dialect/Base.cpp
Back porting from the integrate
=> Change uses of deprecated method a.cast to cast<>(a)

docs/spec.md
These ops were specced in https://github.com/openxla/stablehlo/pull/2270 and https://github.com/openxla/stablehlo/pull/2284.
=> Remove dynamic_{iota,reshape} from list of ops to spec

BUILD.bazel, stablehlo/tests/stablehlo_legalize_deprecated_ops.mlir, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/Passes.h, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloLegalizeDeprecatedOps.cpp, stablehlo/transforms/StablehloLegalizeDeprecatedOpsPatterns.td
This pass is intended to be used to test the blast radius of the proposed deprecation changes in #2283 and help with migration of passes and other tooling.
Still todo - patterns for the following:
- Einsum pattern
- TorchIndexSelect pattern
- RNG pattern (if possible)
- RealDynamicSliceOp (requires dynamic_slice update first)
=> Add initial deprecation upgrade patterns for testing impact radius

docs/spec.md, docs/status.md, stablehlo/dialect/Base.td, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/reference/Index.cpp, stablehlo/reference/Ops.cpp, stablehlo/reference/Ops.h, stablehlo/reference/Tensor.cpp, stablehlo/reference/Tensor.h, stablehlo/tests/interpret/dynamic_pad.mlir, stablehlo/tests/ops_stablehlo.mlir
This includes:
- Adding partial support to the interpreter (only when the result is static)
- Cleaning up and completing the verifier
- Updating the ODS
- Adding relevant tests
I made a few drive-by fixes to related logic/ops as well.
Constraint coverage:
```
I1. operand is tensor or per-tensor quantized tensor: ODS
I2. padding_value is 0-dimensional tensor or per-tensor quantized tensor: ODS
I3. edge_padding_low is integer tensor: ODS
I4. edge_padding_high is integer tensor: ODS
I5. interior_padding is integer tensor: ODS
C1. element_type(operand) = element_type(padding_value) = element_type(result): ODS
C2. size(edge_padding_low) = size(edge_padding_high) = size(interior_padding) = rank(operand): ODS + verifier
C3. 0 <= interior_padding: verifier
C4. shape(result) = shape(operand) + …
```
=> Spec dynamic_pad

stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.cpp, stablehlo/conversions/linalg/transforms/LegalizeToLinalgUtils.h, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp
Operands and results are enforced to be ranked by ODS.
=> Remove redundant rank checks in linalg lowerings

stablehlo/conversions/linalg/tests/dot-product.mlir, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/transforms/StablehloLegalizeDeprecatedOps.cpp
We are in the process of deprecating DotOp (#2296).
To ease the deprecation, we want DotGeneral ops that are equivalent to simple DotOp ops to be lowered in the same way.
In this PR:
- Add a "isSimpleDot" method to DotGeneralOp which determines if a DotGeneralOp can be expressed as a DotOp.
- Reuse the DotOp linalg lowerings for DotGeneralOp when isSimpleDot.
- Remove "DotOperationType" as it is redundant with the linalg op types.
https://github.com/openxla/stablehlo/issues/2311
=> Use DotOp linalg lowerings for simple DotGeneral ops

BUILD.bazel, build_tools/github_actions/lint_clang_format.sh, stablehlo/conversions/tosa/tests/binary.mlir, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.cpp
This first phase adds support for DotGeneralOp's that are simple dots (i.e. same semantics as DotOp).
=> Migrate TOSA support from Dot to DotGeneral

stablehlo/conversions/linalg/transforms/MapStablehloToScalarOp.h
Many of these map to scalar patterns are used in linalg, but using a code search, this DotOp pattern is never initialized. There is another dot pattern which is used instead.
=> Remove unused dotop lowering from linalg

stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/transforms/StablehloLegalizeDeprecatedOps.cpp, stablehlo/transforms/StablehloLegalizeDeprecatedOpsPatterns.td
In a similar vein as #2314, this PR eases the process of deprecating BroadcastOp by reusing the BroadcastOp lowerings for BroadcastInDimOp ops derived from BroadcastOp ops.
Unfortunately, BroadcastInDimOp requires a static result type, so not all Broadcast ops can be converted through the deprecated op legalization.
#2311
=> Use BroadcastOp linalg lowerings for simple BroadcastInDimOps

.github/workflows/buildAndTestCMake.yml
This reverts commit 538b1e11ca83fd5f14390e73a54c41af8f7ee87d.
The underlying issue was fixed in upstream in https://github.com/actions/runner-images/pull/9513 (https://github.com/actions/runner-images/issues/9491)
=> Revert "Fix asan build issue (#2108)"

docs/spec.md, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/ops_stablehlo.mlir
Separate constraints are not required, C8 is taking care of C9, C10. Same verifier check is applicable.
=> dynamic_broadcast_in_dim  followup cleanup

CONTRIBUTING.md, docs/vhlo.md, docs/vhlo_checklist.md
This may help with making sure we don't miss any items when making changes to VHLO. The main vhlo.md file should focus on what VHLO is.
=> Split out VHLO contribution guidelines into their own file

docs/vhlo_checklist.md
The line the log is at is not super likely to change, but the file is small and the log is easy to locate anyway.
=> Avoiding linking to specific line in VhloDialect.td

docs/spec.md, rfcs/20240503-opset-deprecations.md
Was flagged to me that there were a few things explicitly denoted as "to be removed" in the spec. I've closed a few of these issues, and added the ones that are likely beneficial to the community to the list of deprecations.
=> Add featured declated as 'to remove' in spec

README.md, docs/compatibility.md
Update compatibility.md to include the latest compatibility window for StableHLO v1.0. Also include link on readme to StableHLO's on-device use which utilizes these longer compatibility guarantees.
=> Add StableHLO v1.0 Compatibility Updates

stablehlo/integrations/c/StablehloAttributes.h
This is for C builds which doesn't have `optional` defined. And include `<stdint.h>` as that is what defines `int64_t`.
=> Delete `<optional>` and add `<stdint.h>` from `StablehloAttributes.h`

stablehlo/reference/Ops.cpp
Use `startIndicesIndex` in Ops.cpp for computing gather/scatter batching index instead of `batchIndex`
=> Small nit fix in gather/scatter batching index computation in evaluator

docs/generated/stablehlo_passes.md
documentation is outdated after https://github.com/openxla/stablehlo/pull/2253
Validated that  the change actually fixes the failure
Follow up: why https://github.com/openxla/stablehlo/pull/2253 CI check did not complain?
=> Regenerated pass documentation to fix bazel build failure at head

stablehlo/tests/stablehlo_aggressive_folder.mlir, stablehlo/transforms/StablehloAggressiveFolder.cpp
This PR adds support of IotaOp specialization:
```
func.func @eval_iota() -> tensor<3x4x5xi32> {
%1 = stablehlo.iota dim = 1 : tensor<3x4x5xi32>
func.return %1 : tensor<3x4x5xi32>
}
```
is transformed into:
```
func.func @eval_iota() -> tensor<3x4x5xi32> {
%0 = stablehlo.constant dense<
[[[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3]],
[[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3]],
[[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3]]]> : tensor<3x4x5xi32>
func.return %0 : tensor<3x4x5xi32>
}
```
=> Add EvalIotaOp pattern to StablehloAggressiveFolder

.github/workflows/publishWheelRelease.yml
Some folks are asking for 3.12 support: https://discord.com/channels/999073994483433573/999074539138990131/1246155487758520423
=> Add Python 3.12 to supported version matrix

docs/generated/stablehlo_passes.md, stablehlo/tests/stablehlo_aggressive_folder.mlir, stablehlo/tests/stablehlo_refine_shapes.mlir, stablehlo/transforms/Passes.h, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloAggressiveFolder.cpp
This adds support of following specializations in ConvertOp:
Integer -> Integer (old)
Integer -> FloatType (new)
FloatType -> FloatType (new)
FloatType -> Integer (new)
I have considered approach used in `convertElementsAttr` from `mlir-hlo/utils/convert_op_folder.cc`, but `DenseIntOrFPElementsAttr::mapValues` doesn't give an option to stop conversion in case of failure.
This implementation works for my case:
```
%cst = arith.constant dense<1.000000e+00> : tensor<1xf64>
%cst_0 = arith.constant dense<128> : tensor<1xi64>
%cst_1 = arith.constant dense<9.9999999999999998E-13> : tensor<1xf64>
%61 = stablehlo.constant dense<8.000000e+00> : tensor<f64>
%73 = stablehlo.constant dense<-3.4028234663852886E+38> : tensor<f64>
%76 = stablehlo.constant dense<1> : tensor<2x128xi32> 
...
%86 = …
```
=> Add support of float type in specialization of ConvertOp

stablehlo/conversions/linalg/tests/dot-product.mlir, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp, stablehlo/dialect/StablehloOps.cpp
When the rank of either `lhs` or `rhs` is greater than 2, `isSimpleDot` may produce an incorrect result because of how `getDefaultDotDimensionNumbers` is implemented.
=> Take rank into account when checking if a DotGeneralOp is simple

stablehlo/dialect/StablehloBytecode.cpp, stablehlo/tests/ops_stablehlo_roundtrip.mlir
The bytecode changes are causing issues due to some StableHLO consumers using StableHLO directly rather than VHLO.
Temporarily remove the relevant roundtrip tests as well since this breaks round-tripping.
=> Revert bytecode changes from #2259

stablehlo/integrations/python/stablehlo/savedmodel/stablehlo_to_tf_saved_model.py
The return type of 'List[tensorflow.TensorSpec]' for generator function `StableHLOToTFSavedModel._make_input_signatures` is error-ed out during internal testing.
The fix is to annotating the return type as Iterator as all generators are basically iterators.
=> Fix the return type of python generator function

build_tools/github_actions/ci_build_docs.sh
Will help with fixing doc CI issues without need for locally running the CI script:
Note the issue from https://github.com/openxla/stablehlo/pull/2125 where this CI script had trouble running on certain linux distros.
=> Add diff patch to doc ci error message

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/tests/ops_stablehlo_quantized.mlir
Here is the constraint this PR is adding verifier for
```
(C2) expressed_type(result) = is_float(operand) ? element_type(operand) : expressed_type(operand).
```
[link](https://github.com/openxla/stablehlo/blob/main/docs/spec.md#constraints-96)
Note: Per the guidelines [(P3) Maintain verification code in verifiers and shape functions
](https://github.com/openxla/stablehlo/blob/main/docs/type_inference.md#p3-maintain-verification-code-in-verifiers-and-shape-functions), we are adding the logic in the verifier (not in the type inference) as the element type for this op cannot be inferred.
=> Add verifier for missing constraint for UniformQuantize Op

stablehlo/transforms/CMakeLists.txt
`StablehloPasses` needs to link `StablehloLinalgTransforms` since `StablehloConvertToSignless` needs `RemoveSignTypeConverter` from `linalg/transforms/TypeConversion`
=> fix StablehloConvertToSignless linkage

stablehlo/conversions/linalg/transforms/CMakeLists.txt
As a follow-up on my previous [PR](https://github.com/openxla/stablehlo/pull/2387), The linalg_passes also needs to link `ChloOps` and `StablehloOps`. They are already included in [`BUILD.bazel`](https://github.com/openxla/stablehlo/blob/main/BUILD.bazel#L477,L479) so only the `CMake` file needs modification.
=> fix linalg_passes link

stablehlo/api/PortableApi.cpp, stablehlo/api/PortableApi.h, stablehlo/integrations/python/PortableApi.cpp, stablehlo/integrations/python/tests/stablehlo.py
Support `get_smaller_version(version1, version2)` in stablehlo's python binding.
Example usage:
```python
version = get_smaller_version(frontend_compiler.get_current_version(), backend_compiler.get_current_version())
serialize_portable_artifact(module, version)
```
=> support get_smaller_version in python binding

stablehlo/tests/stablehlo_legalize_quant_to_int.mlir, stablehlo/transforms/StablehloLegalizeQuantToInt.cpp
Consider the following quantized stablehlo max operation
```
func.func @max_per_tensor_diff_quant_parameters(%arg0: tensor<!quant.uniform<i8:f32,1.0:0>>, %arg1: tensor<!quant.uniform<i8:f32,2.0:1>>) ->  tensor<!quant.uniform<i8:f32,3.0:2>> {
%0 = "stablehlo.maximum"(%arg0, %arg1) : (tensor<!quant.uniform<i8:f32,1.0:0>>, tensor<!quant.uniform<i8:f32,2.0:1>>) -> tensor<!quant.uniform<i8:f32,3.0:2>>
func.return %0 : tensor<!quant.uniform<i8:f32,3.0:2>>
}
```
Note that the quantization parameters (scales and zps) for operands and results are different.  
Currently [--stablehlo-legalize-quant-to-int](https://github.com/openxla/stablehlo/blob/main/stablehlo/transforms/StablehloLegalizeQuantToInt.cpp) legalizes this as follows:
```
func.func @max_per_tensor_diff_quant_parameters(%arg0: …
```
=> Fix legalization of quantized Min/Max op to Int ops 

docs/spec.md, rfcs/20240312-standardize-customcallop.md
This RFC proposes standardizing CustomCallOp to extend backend_config to take a DictionaryAttr.
Please review and provide you feedback.
=> [RFC] Standardize CustomCallOp to extend backend_config to take a DictionaryAttr

stablehlo/tests/chlo/chlo_legalize_to_stablehlo_broadcast.mlir, stablehlo/tests/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/StablehloAggressiveSimplification.cpp
This patch is a two-stage:
1) change `isIotaRange` constraint to `llvm::sorted` in order to enable the rewrite from `broadcast_in_dim` -> `reshape`:
```
%0 = stablehlo.broadcast_in_dim %arg0, dims = [1, 2] : (tensor<3x6xi32>) -> tensor<1x3x6xi32>
```
is transformed into:
```
%0 = stablehlo.reshape %arg0 : (tensor<3x6xi32>) -> tensor<1x3x6xi32>
```
(hlo_ops.cpp: BroadcastInDimSimplifier uses same approach)
2) `broadcast_in_dim` operator can be quite complex in its semantics, sometimes functioning as a combination of `transpose` and `broadcast`. In order to simplify analysis and optimization, it can be beneficial to fully expand operand dimensions by ensuring that the size of broadcast_dimensions matches the rank of the result. This can be achieved by reshaping the input operand while …
=> Align canonicalization of stablehlo.broadcast_in_dim with XLA

stablehlo/tests/ops_stablehlo.mlir
Our repo uses `expected-error@+1` rather than `@expected-error@+1` for majority of the tests, so let's consolidate it to one style.
=> Remove spurious symbol on lit error checks

stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp, stablehlo/dialect/AssemblyFormat.cpp, stablehlo/dialect/AssemblyFormat.h, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloBytecode.cpp, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.h, stablehlo/dialect/StablehloOps.td, stablehlo/tests/ops_stablehlo_roundtrip.mlir, stablehlo/transforms/StablehloAggressiveSimplification.cpp
Several hacks/patches were put in place to preserve StableHLO compatibility for PJRT plugins.
Recently PJRT was switched to send VHLO, meaning we can clean up all these patch fixes.
Closes #2216
=> Cleanup StableHLO bytecode patches used for temporary pjrt compatibility

stablehlo/conversions/linalg/transforms/Passes.td
Anchoring `stablehlo-legalize-to-linalg` on ModuleOp doesn't serve any specific purpose at this point. However, this makes it difficult to use this pass in any way for downstream stablehlo users. This change removes ModuleOp anchor from `stablehlo-legalize-to-linalg` pass.
=> Don't apply `stablehlo-legalize-to-linalg` pass on ModuelOp.

CMakeLists.txt
This setup is based on: [How_to_Build_your_own_MLIR_Dialect.pdf](https://www.google.com/url?sa=D&q=https%3A%2F%2Farchive.fosdem.org%2F2023%2Fschedule%2Fevent%2Fmlirdialect%2Fattachments%2Fslides%2F5740%2Fexport%2Fevents%2Fattachments%2Fmlirdialect%2Fslides%2F5740%2FHow_to_Build_your_own_MLIR_Dialect.pdf)
```
#
```
Tested using `mlir-hlo` repo. No changes to the `EMBEDDED` build so should not impact torch-mlir.
=> Refactor CMakeList to work for all build types

stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td
This logic is used many times in openxla/xla, so decided to turn it into a method
=> Add convenience method to CustomCallOp for checking empty backend config

stablehlo/tests/math/acos_limits.mlir, stablehlo/transforms/ChloDecompositionPatterns.td, stablehlo/transforms/ChloDecompositionPatternsMath.td
It looks like something may be broken in the `chlo.acos` lowering from functional algorithms. The complex lowering works just fine (has `SelectOp`).
Also I'm wondering how we didn't catch this / could have caught this. Perhaps we should have special cases for ops with limits..somehow? Open to iterating on this, either by dev policy on these CLs (ensure total code coverage) or if there's a way to auto generate cases would be good too.
Current behavior prior to revert: `chlo.acos(-1) --> 0`, expected behavior is `pi`.
=> Revert acos changes for non complex numbers

stablehlo/integrations/c/CMakeLists.txt, stablehlo/integrations/c/CheckDialect.cpp, stablehlo/integrations/c/CheckDialect.h, stablehlo/integrations/python/CMakeLists.txt, stablehlo/integrations/python/CheckModule.cpp, stablehlo/integrations/python/mlir/dialects/CheckOps.td, stablehlo/integrations/python/mlir/dialects/check.py, stablehlo/integrations/python/tests/CMakeLists.txt, stablehlo/integrations/python/tests/check.py
Check dialect is an auxiliary dialect used in StableHLO repository for validation of StableHLO program evaluation. Currently there is no cleaner way to parse a module containing check dialect operations or to create them. One way to go around this is to textually modify the check dialect ops to normalize them to generic MLIR text  and allow unregistered dialect to pars that text. However, this PR provodes a cleaner way to process check dialect. 
This PR prepares for open sourcing some of the utilities, leveraged in https://github.com/openxla/stablehlo/pull/2404,  for auto-generating testdata formatted test files.
=> Python bindings for registering check dialect

stablehlo/reference/Ops.cpp, stablehlo/tests/interpret/all_to_all.mlir
fixes: https://github.com/openxla/stablehlo/issues/2433
```
scattered_parts...@receiver = [split_parts...@sender[receiver_index] for sender in process_group] where receiver_index = process_group.index(receiver).
```
each `sender/process` from `process_group` contributes a `split_part` to the `scattered_parts`. This PR ensures the order of `split_part` in `scattered_parts` matches with the order of the `sender/processes` within the `process_group`.
=> Update all_to_all op interpreter to fix issue#2433

stablehlo/tests/CheckOps.td
After recent LLVM integrate, optional attributes that have a default value, will not be printed anymore. 
This exposed `ExpectCloseOp` custom assembly parser limitation. It can't handle a scenario of - if `max_ulp_difference` is not printed.
```
if (::mlir::succeeded(parser.parseOptionalComma())) { 
if (parser.parseKeyword("max_ulp_difference"))
return ::mlir::failure();
if (parser.parseEqual()) return ::mlir::failure();
...
}
```
existing parser expects `max_ulp_difference` to be present after `,` which is not the case anymore for test
`check.expect_close %3, %4, max_ulp_difference = 1, min_ulp_difference = 1 : tensor<9xf64>, tensor<9xf64>`
To address this, we will need nested `optional-group`s which results in an error `attribute 'min_ulp_difference' is already bound`
fix- keep only one …
=> ExpectCloseOp  : Keep only one `optional-group` in custom assembly

stablehlo/reference/Ops.cpp, stablehlo/tests/interpret/sort.mlir
fixes https://github.com/openxla/stablehlo/issues/2440. The source and destination indices were not in correct order.
=> Fix SortOp interpreter

docs/spec.md, stablehlo/conversions/linalg/tests/dot-product.mlir, stablehlo/conversions/linalg/transforms/StablehloToLinalgDotProduct.cpp, stablehlo/dialect/StablehloAttrs.td, stablehlo/dialect/StablehloBytecode.cpp, stablehlo/dialect/StablehloEnums.td, stablehlo/dialect/StablehloOps.cpp, stablehlo/dialect/StablehloOps.td, stablehlo/dialect/TypeInference.cpp, stablehlo/dialect/TypeInference.h, stablehlo/reference/Ops.cpp, stablehlo/tests/interpret/dot_general.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/transforms/StablehloLegalizeDeprecatedOpsPatterns.td
Implementation of https://github.com/openxla/stablehlo/pull/2422.
Done:
- Attribute impl
- Spec updates
- Test cases
To-do:
- Create an XLA doc on supported algorithm pairs to link to from spec.
- Compatibility impl, will do this in a child CL to keep review simplified. 
To consider:
- Should we verify algorithms more strictly, so that only algs supported on _some_ hardware are allowed in StableHLO. Expanding support will be trivial, no RFC required, but StableHLO should try to statically enforce as much as possible, why allow nonsense pairs.
- Should dot_general on integers support floating point precision types?
Other cleanup:
- PrecisionConfig is no longer implicitly optional, but all uses are wrapped in `OptionalAttr` now.
=> Implement Dot Algorithms RFC

stablehlo/reference/Element.cpp, stablehlo/reference/Element.h, stablehlo/reference/Ops.cpp
1. earlier code assumed result element type is float : added `convertUsingZeroValue` to handle supported types.
2. `result` element type and `lhs` and `rhs` element types can be different. Convert the `lhs``rhs` to `result` element type  before computation to avoid errors like `LLVM ERROR: Element types don't match: i32 vs i8`
Tests: 
- existing stablehlo tests 
- Validated against new `dot_general` tests being added at https://github.com/openxla/stablehlo/pull/2500
=> DotGeneralOp interpreter updates

BUILD.bazel, stablehlo/integrations/c/StablehloApi.h
It is problematic to include StableHLO source files from non-StableHLO projects. It makes renaming files and dependencies much more difficult.
Hiding file names behind a target that lives in StableHLO should help with the file renames case. There isn't a good way to keep a dependency list in StableHLO, but the only dependency of python bindings should be CAPI so that shouldn't be too problematic.
=> Move exported files behind filegroups

stablehlo/dialect/Base.cpp, stablehlo/dialect/Base.h, stablehlo/dialect/TypeInference.cpp, stablehlo/tests/interpret/dot_general.mlir, stablehlo/tests/ops_dot_general_algorithms.mlir, stablehlo/tests/ops_stablehlo.mlir, stablehlo/tests/print_stablehlo.mlir
This is somewhat of ecosystem implementation details leaking into StableHLO, but that seems to be safer than allowing any arbitrary combination and enforcing that the user get some lucky combination correct.
=> Add best effort validation for known dot algorithms

build_tools/math/generate_ChloDecompositionPatternsMath.py, stablehlo/conversions/tosa/tests/lit.cfg.py, stablehlo/integrations/python/StablehloApi.cpp, stablehlo/integrations/python/tests/stablehlo.py
Add `stablehlo.get_version_from_compatibility_requirement` API.
=> Move python bindings to portable apis that use C-API datatypes.

BUILD.bazel, docs/generated/stablehlo_passes.md, stablehlo/tests/transforms/stablehlo_create_compatibility_expander.mlir, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/Passes.h, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloCreateCompatibilityExpander.cpp, stablehlo/transforms/StablehloCreateCompatibilityExpanderPatterns.td
Backporting from g3..
This pass expands backward compatibility with older StableHLO versions by decomposing newer StableHLO operations into equivalent operations supported by those older versions.
=> Add StableHLOCreateCompatibilityExpanderPass

stablehlo/conversions/linalg/transforms/CMakeLists.txt, stablehlo/conversions/tosa/transforms/CMakeLists.txt
This change removes two spurious 'LINK_COMPONENTS Core' declarations in
the CMake build. Depending on the 'Core' component indicates that the
libraries depend on the code under 'llvm-project/llvm/lib/IR' (e.g. 'LLVMCore'
library), which is not true for the StablehloLinalgTransforms and
StablehloTOSATransforms libraries.
=> [cmake] Remove dependence on LLVM 'Core' component in the CMake build

stablehlo/dialect/Version.cpp, stablehlo/transforms/StablehloAggressiveFolder.cpp
This PR fixes the following warnings:
```
stablehlo/stablehlo/dialect/Version.cpp:89:1: 
warning: control reaches end of non-void function [-Wreturn-type]
```
```
stablehlo/stablehlo/transforms/StablehloAggressiveFolder.cpp:315:59: 
warning: 'result' may be used uninitialized in this function [-Wmaybe-uninitialized]
315 |       return getAPSInt(resultType.getElementType(), result);
```
=> Fix some warnings

BUILD.bazel
Depending on :CAPIIR from a capi_objects target causes duplicate symbol problems in JAX on Windows.
=> Fix stablehlo_capi_objects to depend on :CAPIIRObjects, not :CAPIIR.

stablehlo/integrations/c/StablehloApi.cpp, stablehlo/integrations/c/StablehloApi.h, stablehlo/integrations/python/StablehloApi.cpp
Issue: JAX windows build is failing because of missing stablehlo C API symbols
https://github.com/google/jax/actions/runs/10739809804/job/29786443538
root cause: `StablehloApi.h` defs has function overloads. Compiler does name mangling (decorating function names with additional information).  These symbols are missing in JAX APIs,  JAX only allowlist symbol exports for symbols starting with `stablehlo`, but the mangled c++ names don't have that property.  
fix:
1. add `extern "C" `  around stablehloapi.h declarations. extern "C" instructs the compiler to suppress the mangling.
2. rename functions to avoid function overloading
thank you @hawkinsp  for help with root causing and validating the fix.
=> Fix JAX windows ci build error : missing stablehlo C API symbols

stablehlo/conversions/tosa/tests/legalize_quant_ops_to_tosa_rescale.mlir, stablehlo/conversions/tosa/transforms/StablehloQuantLegalizeToTosaRescale.cpp
by adding support for following quantized operators:
-  abs
-  multiply and divide
-  maximum and minimum
-  compare
=> Enhance stablehlo-quant-legalize-to-tosa-rescale

docs/spec.md, stablehlo/dialect/StablehloOps.td, stablehlo/tests/interpret/dynamic_broadcast_in_dim.mlir
fixes https://github.com/openxla/stablehlo/issues/2535
=> Fix typo:  known_non_expanding_dimensions -> known_nonexpanding_dimensions

docs/spec.md
fixes https://github.com/openxla/stablehlo/issues/2539
=> Fix Quant grammar

stablehlo/dialect/Version.cpp
For 4w compat, enables use of TanOp. For 12w, enables use of gather/scatter batch dims.
=> Bump 4w and 12w version numbers

stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
When `enable-primitive-ops` is true, emit `tensor.concat`.
=> Enable `stablehlo.concatenate` to `tensor.concat` conversion

stablehlo/tests/transforms/stablehlo_create_compatibility_expander.mlir, stablehlo/transforms/StablehloCreateCompatibilityExpander.cpp
porting to gh https://github.com/openxla/xla/commit/10f3a172a9973846e45d193ac9098d40b0ca156f
=> Add an expander pattern for GatherOp/ScatterOp with batching dims

stablehlo/tests/transforms/stablehlo_refine_shapes.mlir, stablehlo/transforms/StablehloAggressiveFolder.cpp
This patch enhances the EvalSlice constant folder to support all operator configurations on static tensor shapes, including 0-rank scalars.
=> Support all static tensor shapes in EvalSlice folder

docs/_toc.yaml
The page exists at: https://openxla.org/stablehlo/ide
But it isn't mentioned in `_toc.yaml` so it is missing the side bar on the page, and it doesn't show up in the typical nav bar.
=> Add ide.md to TOC

CMakeLists.txt
These LLVM CMake modules used to be unconditionally included, but #2430 changed that to only conditionally including them in the standalone and embedded builds, leaving out the external-project build.
That broke integration in https://github.com/iree-org/iree where Stablehlo is an external project. [Error log here](https://gist.github.com/bjacob/17f86fb5f07007e06b94f3a9347747a1). These are linking errors when building with Clang or GCC, with unresolved symbols for `typeinfo` for various types, referenced from Stablehlo symbols. `typeinfo` is a RTTI feature, and all LLVM-derived projects normally disable RTTI, which is why these symbols are not defined, and why that is normally not a problem. What changed with #2430 was that suddenly, the disabling of RTTI was itself disabled in our …
=> Always include LLVM CMake modules.

stablehlo/integrations/c/CMakeLists.txt, stablehlo/reference/CMakeLists.txt
This is a new take on https://github.com/openxla/stablehlo/pull/2573.
There, I was trying to fix CMake errors in the external build, with the error message saying that `LINK_COMPONENTS` should be used instead of `LINK_LIBS` for  LLVM libraries.  That change fixed my external build, but broke the standalone build on CI.
Reading the `AddMLIR.cmake` code generating the error, I came across this line:
https://github.com/llvm/llvm-project/blob/ee4dd147baff8f971f3ec5aad5a216ca9837a732/mlir/cmake/modules/AddMLIR.cmake#L287-L288
```cmake
list(APPEND ARG_LINK_COMPONENTS Support)
```
This looks like hardcoding always depending on `LLVMSupport`  (though I wasn't quite sure about the nuance between `Support` and `LLVMSupport`). If that's correct, then we never needed specifying `LLVMSupport` in the …
=> CMake: Do not specify `LLVMSupport` in `LINK_LIBS`.

stablehlo/conversions/linalg/tests/miscellaneous.mlir, stablehlo/dialect/StablehloOps.cpp
For the case of simple broadcast check that we don't have to extend dimentions, so skip convertion to BroadcastOp when only one of them is 1.
Error before:
test.mlir:5:8: error: 'linalg.broadcast' op input dim 1 should match init dim 2. input: 1, init: 5
%0 = stablehlo.broadcast_in_dim %arg, dims = [1, 2, 3] : (tensor<3x1x1xf32>) -> tensor<1x3x5x7xf32>
^
test.mlir:5:8: note: see current operation:
%1 = "linalg.broadcast"(%arg0, %0) <{dimensions = array<i64: 0>}> ({
^bb0(%arg1: f32, %arg2: f32):
"linalg.yield"(%arg1) : (f32) -> ()
}) : (tensor<3x1x1xf32>, tensor<1x3x5x7xf32>) -> tensor<1x3x5x7xf32>
=> Fix BroadcastInDimOps linalg lowering with compatible dim=1

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/transforms/StablehloAggressiveFolder.cpp
This patch folds `stablehlo.transpose` operation with constant operand into `stablehlo.constant`.
I have considered doing this by iterating over source index space, i.e.
```
auto initialValue = *std::begin(data);
SmallVector<ElementType> result(resultType.getNumElements(), initialValue);
for (int64_t i = 0; i < operandType.getNumElements(); ++i) {
auto srcDimIndex = delinearize(i, operandStrides);
auto dstDimIndex = applyPermutation(srcDimIndex, permutation);
auto dstLinearIndex = linearize(dstDimIndex, resultStrides);
result[dstLinearIndex] = data[i];
}
```
but that requires preinitialization of result vector with some value, which is twice as slow on simple case:
```
func.func @eval_transpose() -> (tensor<5000x80x30xi32>) {
%0 = stablehlo.iota dim = 0 : tensor<30x80x5000xi32>
%1 = …
```
=> Add EvalTranspose pattern to StablehloAggressiveFolder

stablehlo/dialect/Version.cpp
Bump 12W compat to v1.3.0 released on July 16, 2024
Tags: https://github.com/openxla/stablehlo/tags
12W is used in `xla::GetDefaultStablehloVersion()` which is used by `PjRtCApiCompiler::Compile()` xla/pjrt/pjrt_c_api_client.cc:2317
=> Bump WEEK_12 compat to v1.3.0

CMakeLists.txt
This fixes downstream build errors tracked at https://github.com/iree-org/iree/issues/18785.
Sample error message when building on Windows with MSVC:
```
FAILED: llvm-external-projects/stablehlo/stablehlo/dialect/CMakeFiles/obj.VhloOps.dir/VhloOps.cpp.obj
C:\ProgramData\Chocolatey\bin\ccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x64\cl.exe  /nologo /TP -DGTEST_HAS_RTTI=0 -D_HAS_EXCEPTIONS=0 -D_USE_MATH_DEFINES -ID:\a\iree\iree\third_party\llvm-project\llvm\include -ID:\a\iree\iree\build-windows\llvm-project\include -ID:\a\iree\iree\third_party\llvm-project\mlir\include -ID:\a\iree\iree\third_party\stablehlo -ID:\a\iree\iree\build-windows\llvm-external-projects\stablehlo -ID:\a\iree\iree\third_party\llvm-project\lld\include …
```
=> Set `/bigobj` option on MSVC to fix object limit error.

stablehlo/dialect/Version.cpp
Bump version in `Version::fromCompatibilityRequirement`
- WEEK_12 => v1.4.1 (84 days ago)
- WEEK_4 => 1.7.1 (35 days ago)
=> Bump WEEK_12=>v1.4.1, WEEK_4=>1.7.1

BUILD.bazel, stablehlo/testdata/igamma_float64_20_20_float64_20_20_chlo.mlir, stablehlo/testdata/igammac_float64_20_20_float64_20_20_chlo.mlir, stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/PassUtils.cpp, stablehlo/transforms/PassUtils.h, stablehlo/transforms/Passes.h, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloAggressiveFolder.cpp, stablehlo/transforms/StablehloAggressiveSimplification.cpp, stablehlo/transforms/StablehloAggressiveSimplificationPatterns.td
Starting to look into porting new simplification patterns from MHLO to StableHLO and wanted to clean things up in the process to make StableHLO simplification/folders an overall better place to innovate:
- Leverage DRR when possible. This is usually possible when the pattern isn't super complicated or the op being built doesn't have a region.
- Order simplification patterns by op alphabetically, order tests alphabetically, ensure a test per simplification pattern.
- Add code comments for each pattern of the format `// Pattern: ...` which can be used in the future for generating documentation.
- Move patterns which fold constants to folder pass.
=> Revamp StableHLO simplification paterns.

rfcs/20241001-microscaling-formats.md
This is a proposal to add MX (microscaling) floating point types to StableHLO.
Related links:
- StableHLO [PR#2582](https://github.com/openxla/stablehlo/pull/2582) Add MX floating point types (f4E2M1FN, f6E2M3FN, f6E3M2FN, f8E8M0FNU)
- LLVM [PR#95392](https://github.com/llvm/llvm-project/pull/95392) [APFloat] Add APFloat support for FP4 data type
- LLVM [PR#94735](https://github.com/llvm/llvm-project/pull/94735) [APFloat] Add APFloat support for FP6 data types
- LLVM [PR#107127](https://github.com/llvm/llvm-project/pull/107127) [APFloat] Add APFloat support for E8M0 type
- LLVM [PR#108877](https://github.com/llvm/llvm-project/pull/108877) [MLIR] Add f4E2M1FN type
- LLVM [PR#107999](https://github.com/llvm/llvm-project/pull/107999) [MLIR] Add f6E2M3FN type
- LLVM …
=> [RFC] Microscaling data types (f4E2M1FN, f6E2M3FN, f6E3M2FN, f8E8M0FNU)

stablehlo/tests/vhlo/vhlo_to_version_downgrade_patch.mlir, stablehlo/transforms/VhloToVersion.cpp
We want to allow targeting patch version because we allow `-target=current` so it makes sense that current can resolve to a patch version.
That said we write our compat passes against patch v0 since all opset changes require a minor version bump and therefore have patch v0.
This PR implements "version flooring" inside the vhlo-to-version pass.
=> Fix issue when targeting a patch version for serialization

stablehlo/dialect/Version.cpp
WEEK_4: v1.7.3 2024-09-23 28 days ago
WEEK_12: v1.4.2 2024-07-25 88 days ago
[get_compatibility_versions.py](https://gist.github.com/apivovarov/e5f949983feff1fc378d93f3008a9900)
BTW, WEEK_12 will be v1.5.0 in 3 days on Oct 24
=> Bump WEEK_12 to v1.4.2, WEEK_4 to 1.7.3

stablehlo/dialect/Version.cpp
WEEK_4: v1.7.5 2024-09-26 28 days ago
WEEK_12: v1.5.0 2024-08-01 84 days ago
[get_compatibility_versions.py](https://gist.github.com/apivovarov/e5f949983feff1fc378d93f3008a9900)
=> Bump WEEK_12 to v1.5.0, WEEK_4 to 1.7.5

BUILD.bazel, stablehlo/reference/Tensor.cpp, stablehlo/tests/interpret/api_input_arguments.mlir, stablehlo/tools/StablehloTranslateMain.cpp
Two main changes:
1. Support complex types in Reference APIs
2. Add support for passing arguments when using `stablehlo-translate`
To avoid inventing anything fancy, I've leveraged existing MLIR assembly printing/parsing:
```
stablehlo-translate myfile.mlir --interpret --args="[dense<1> : tensor<2xi32>, dense<2> : tensor<2xi32>]"
```
=> Add stablehlo-translate interpreter arg passing, complex types in reference APIs

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloAggressiveSimplification.cpp, stablehlo/transforms/StablehloAggressiveSimplificationPatterns.td
Porting over / re-organizing useful simplifications from MHLO to StableHLO for broader community use.
This includes all tests from [xla/mlir_hlo/tests/Dialect/mhlo/canonicalize/canonicalize.mlir](https://github.com/openxla/xla/blob/2c4b82cab1679273044188da5de780ec8f0eefad/xla/mlir_hlo/tests/Dialect/mhlo/canonicalize/canonicalize.mlir#L4)
Closes https://github.com/openxla/stablehlo/issues/2607
Overview of simplifications now in StableHLO:
```
add(X, 0) -> X
add(cst, X) -> add(X, cst)
add(cst,cst) -> cst
and(X, 0) -> 0
and(X, 1) -> X
and(cst, X) -> and(X, cst)
broadcast_in_dim(X, [dims...]) -> transpose(X, [dims...]) [if same numel & rank]
broadcast_in_dim(X, [iota...]) -> X
broadcast_in_dim(X, [sorted...]) -> reshape(X, [sorted...]) [if same numel]
broadcast_in_dim(broadcast_in_dim(X, …
```
=> Add MHLO simplifications to StableHLO

build_tools/update_version_h_cpp.sh, stablehlo/dialect/Version.cpp
This PR adds `update_version_h_cpp.sh` script
The script will:
- Automatically calculate `WEEK_4` and `WEEK_12` versions based on Version tag date and current date.
- Bump CurrentVersion by increasing patch version by 1 
This script should be executed at the beginning of the next development cycle, after performing the git tagging.
This script:
1. Updates current version in `stablehlo/dialect/Version.h`
```cpp 
static Version getCurrentVersion() { return Version(x, y, z); }
```
New version will be (x, y, z + 1)
2. Replaces WEEK_4 and WEEK12 versions in stablehlo/dialect/Version.cpp
```
return Version(a, b, c);  // WEEK_4 ANCHOR: DO NOT MODIFY
return Version(m, n, p);  // WEEK_12 ANCHOR: DO NOT MODIFY
```
- WEEK_4 version - The most recent git tag that was created at least 28 days ago.
- …
=> Automatically update WEEK_4 WEEK_12 versions

docs/tutorials/pytorch-export.ipynb
This PR updates the "Exporting StableHLO from PyTorch" tutorial. Specifically:
- Update dependencies, combine the tensorflow dependency in the first section to avoid warnings (about using tensorflow-cpu) on Kaggle
- Minor updates to narration and links, along with an introduction statement
- Removed dynamic batch size code, addedd notes instead
(Supersedes #2616, same updates but we get a rich diff here)
=> Update PyTorch export tutorial

docs/generated/stablehlo_passes.md, stablehlo/tests/transforms/stablehlo_refine_shapes.mlir, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloRefineArguments.cpp, stablehlo/transforms/StablehloRefineShapes.cpp, stablehlo/transforms/StablehloRefineShapes.h
Currently we require MLIR function inlining before refining shapes. Refining shapes in order and following call operations (enforcing no recursive calls) should allow for `refine(dynamic_export, static_args) == static_export` to be true
=> Don't require inlining for shape refinement

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/StablehloAggressiveSimplificationPatterns.td
Fixes an issue in `stablehlo-aggressive-simplification` where `%1` in
the below would get replaced by `%arg0`:
```
%0 = stablehlo.constant dense<1> : tensor<2xi32>
%1 = stablehlo.and %0, %arg0 : tensor<2xi32>
```
The pattern was checking whether `%0` is equal to `0b1` and was
only tested on bools. A similar bug existed for `stablehlo.and`. Fixed
by just making sure the constant is integer with all bits set to 1.
=> [transforms] Fix simplification patterns for `stablehlo.(and|or)`

.github/workflows/execute_tutorials.yml, docs/tutorials/savedmodel-embed.ipynb
This PR creates a workflow to execute the Jupyter notebooks in `docs/tutorials`. Couple of notes:
- It installs dependencies as defined in the notebook with `!pip install ...`, making it a little slow. We can instead create a `requirements.txt` and [cache dependencies](https://github.com/actions/setup-python#caching-packages-dependencies) for efficient runs, but then we won't be testing the actual user workflows running the tutorials on kaggle/colab
- The workflow only _executes_ the notebooks to make sure there are no errors. The notebooks are not altered. We can also update the notebooks in-place with the freshly executed versions for consistent output. The only concern here is the workflow might fail to push commits to the PR if it were opened from forks due to permission issues.
The …
=> Workflow to run tutorials in CI

BUILD.bazel, stablehlo/transforms/ChloDecompositionUtils.h, stablehlo/transforms/ChloLegalizeToStablehlo.cpp
We want to perform constant propogation through `chlo.lgamma` in Enzyme-JaX
[Kevin](https://github.com/EnzymeAD/Enzyme-JAX/pull/182#discussion_r1876814931) mentioned he was open to exposing some materialize functions (which are currently static, and not callable from [our pass](https://github.com/EnzymeAD/Enzyme-JAX/blob/main/src/enzyme_ad/jax/Passes/EnzymeHLOOpt.cpp) atm)
@wsmoses @GleasonK
=> Expose materialize functions in Chlo to Stablehlo lowering

.bazelrc, build_tools/github_actions/ci_build_bazel.sh
A prior failure in the google3 internal codebase showed that we were not executing the sanitizers like we thought we were.
This change augments bazelrc to do asan and ubsan via config. It leverages the default feature set offered by bazelrc.
I tested the commit priot to 474caa8370dccc753e4693a2ff4221864b227597 to validate that the bug was exhibited.
I've added the sanitizers to the default Bazel build which also builds debug builds.
This may come at an increase cost. If undesirable we can split the job out.
=> Augment bazelrc to support asan & ubsan

stablehlo/reference/Api.cpp, stablehlo/reference/InterpreterOps.cpp, stablehlo/reference/InterpreterOps.h, stablehlo/reference/InterpreterOps.td
While writing an MLIR pass, I realized there's no easy way to inspect the intermediate states of tensors while debugging them. ProbeOp does something similar, but this does not provide a human readable way of inspecting them given arbitrary SSA value.
=> Add PrintOp to the Interpreter dialect

stablehlo/conversions/linalg/transforms/Rewriters.h, stablehlo/conversions/linalg/transforms/StablehloLegalizeToLinalg.cpp
This function declaration has existed since the code was forked from IREE in https://github.com/openxla/stablehlo/pull/1817, but the implementation was kept private (static function within an anonymous namespace).
I'm now trying to switch IREE from having its own implementation to using the upstream implementation from this project in https://github.com/iree-org/iree/pull/19792, and I would like to access these patterns directly, instead of through the `StablehloLegalizeToLinalgPass`. With the patterns I can run conversion including my own sets of additional patterns, while a pass runs in isolation.
I'm also deleting the `populateLegalizeChloPatterns`, `populateLegalizeControlFlowPatterns`, and `populateLegalizeShapeComputationPatterns` declarations, which were not migrated from IREE and …
=> Expose populateStablehloToLinalgConversionPatterns function

docs/awesome.md
I couldn't find an easy link back to this source file from https://openxla.org/stablehlo/awesome.
I _think_ this style of URL should be fine, but I might be missing some website detail (for example, the hosted website has support for translations).
A site-wide solution may be available for some source files. For example:
* The mkdocs-material site generator has "edit this page" and "view source of this page" actions: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions.
* Some tensorflow examples include "View source on GitHub" buttons for notebooks: https://www.tensorflow.org/guide/keras/functional_api
=> Add source link to awesome.md.

BUILD.bazel
Should fix failure in https://github.com/openxla/xla/pull/22438
I need just a bit more time to validate this entirely on Linux
=> Fix duplicate symbols for downstream CAPIObjects users

stablehlo/tests/transforms/stablehlo_compatibility_expander_locations.mlir, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloCompatibilityExpander.cpp, stablehlo/transforms/VhloToVersion.cpp
Fixes https://github.com/openxla/stablehlo/issues/2724
Compatibility expander is an opt-in pass used in PJRT/ODML/etc to try to provide forward compatibility even when a new feature is used.
These can be costly or impact performance as they usually decompose a single op into many, etc.
Note - This is only run when requesting to downgrade to a version before 1.8.5, meaning it will not impact any PJRT users today, only for jax2tf or other export workflows.
=> Add source location downgrade to compatibility expander

.github/workflows/buildAndTestBazel.yml, build_tools/github_actions/ci_build_bazel.sh
- It's painful that doc-only changes compile the entire codebase and run all tests.
- We can't use `paths-ignore` from github actions because it marks jobs as pending and we have branch protections enabled which require all status checks to be green.
- This seems like a generally good change to build what you change, after merge to main we will still build and test all.
Calculates diff in GH actions using https://github.com/Tinder/bazel-diff
```sh
$ curl -Lo /tmp/bazel-diff.jar https://github.com/Tinder/bazel-diff/releases/latest/download/bazel-diff_deploy.jar
$ ./build_tools/github_actions/ci_build_bazel.sh /tmp/bazel-diff.jar $(git merge-base main HEAD) $(git rev-parse HEAD)
Generating Hashes for Revision 'd2708ad6cca730d4c17317388a7acbf8eac2c9f6'
Loading: 0 packages loaded
Generating …
```
=> Bazel build only build affected targets on pull_request

stablehlo/tests/transforms/stablehlo_compatibility_expander_locations.mlir, stablehlo/transforms/StablehloCompatibilityExpander.cpp, stablehlo/transforms/VhloToVersion.cpp
Two bugs:
- Serialization floors version to `X.Y.0` so we can't use `1.8.4` as a version. Makes sense, incompats should be confined to major version bumps
- Fix bug in the logic for valid location checking, was checking the parent location not the active location. Update test file to also test serialization behavior.
=> Fix location versioning

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp
The transformation sometimes generated an invalid `index_cast` op between two non-index int types.
Issue #2727
=> Fix a casting bug in `DynamicIotaOpToBroadcast`.

stablehlo/integrations/c/ChloAttributes.cpp, stablehlo/integrations/c/ChloAttributes.h, stablehlo/integrations/python/ChloModule.cpp, stablehlo/integrations/python/tests/chlo.py, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
Port of https://github.com/openxla/xla/commit/aa913a801a7e627645be4d0a0f6fdf36f4c1cfc5
=> Add CHLO CAPI and PythonAPI for ragged dot

BUILD.bazel, docs/generated/stablehlo_passes.md, stablehlo/tests/transforms/stablehlo_wrap_in_composite.mlir, stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/Passes.h, stablehlo/transforms/Passes.td, stablehlo/transforms/StablehloWrapInComposite.cpp
Wraps StableHLO operations in `stablehlo.composite` operations.
For instance, consider a simple StableHLO program:
```mlir
func.func @main(%arg0 : tensor<2xf32>, %arg1 : tensor<2xf32>) -> tensor<2xf32> {
%0 = stablehlo.add %arg0, %arg1 : tensor<2xf32>
return %0 : tensor<2xf32>
}
```
Applying this pass to wrap `stablehlo.add` operations will result in the
following program:
```mlir
func.func @main(%arg0: tensor<2xf32>, %arg1: tensor<2xf32>) -> tensor<2xf32> {
%0 = stablehlo.composite "stablehlo.add" %arg0, %arg1 {decomposition = @stablehlo.add.impl} : (tensor<2xf32>, tensor<2xf32>) -> tensor<2xf32>
return %0 : tensor<2xf32>
}
func.func private @stablehlo.add.impl(%arg0: tensor<2xf32>, %arg1: tensor<2xf32>) -> tensor<2xf32> {
%0 = stablehlo.add %arg0, %arg1 : tensor<2xf32>
return %0 : …
```
=> Pass to wrap StableHLO ops in composite

stablehlo/conversions/tosa/tests/binary.mlir, stablehlo/conversions/tosa/tests/legalize_quant_ops_to_tosa_rescale.mlir, stablehlo/conversions/tosa/tests/legalize_tosa_rescale_to_stablehlo.mlir, stablehlo/conversions/tosa/tests/nullary.mlir, stablehlo/conversions/tosa/tests/unary.mlir, stablehlo/conversions/tosa/transforms/StablehloLegalizeToTosa.pdll, stablehlo/conversions/tosa/transforms/StablehloQuantLegalizeToTosaRescale.cpp, stablehlo/conversions/tosa/transforms/TosaRescaleLegalizeToStablehlo.cpp
This fixes up legalization passes for converting to/from tosa for tosa dialect changes
- tosa rescale has multiplier, shift, input_zp, output_zp changed from attribute to operands with specific type requirements
- tosa rescale attribute "double_round" changed to "rounding_mode"
- tosa negate has additional input_zp and output_zp operands
- tosa const attribute name changed from "value" to "values"
=> [stablehlo][tosa] Fix for tosa dialect updates

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp, stablehlo/transforms/optimization/StablehloAggressiveSimplificationPatterns.td, stablehlo/transforms/optimization/StablehloTargetIndependentOptimization.cpp
Some of these may seem unsafe (simplifying float `X*1.0` or `X*0.0` may not account for NaNs properly), but both MHLO and XLA simplifications do this optim so probably generally safe.
=> Add more MHLO folders to StableHLO

.github/workflows/publishWheelRelease.yml
This is a LSC run by http://go/ghss to upgrade all depreacated ubuntu-20.04 runners to ubuntu-24.04.
On April 1, 2025, GitHub will stop supporting ubuntu-20.04 runners and workflows configured with this label will cease to run.  This PR is an attempt to save you work by doing the upgrade for you.
WARNING: We do not know if the updated label is compatiable with your workflow or not.
If you do not want to merge this PR, feel free to close it and deal with the problem yourselves.
More context and feedback: http://b/406537467
=> Update runners to ubuntu-24.04 from deprecated ubuntu-20.04 label

stablehlo/dialect/TypeInference.cpp
If this check isn't there, printing stablehlo of an op under construction (and thus without a terminator) will unnecessarily segfault/crash
=> Add terminator check during type validation

stablehlo/dialect/StablehloOps.td
Following up on PR #1872, this updates the ODS documentation comment to show the new input type of `array<i64: foo>` instead of the old `dense<foo> : tensor<Nxi64>`.
=> Update input type in ODS documentation comment

stablehlo/transforms/Passes.h, stablehlo/transforms/optimization/Passes.h
The declaration for a pass-creation function was located in the wrong header file, resulting in a linker error if someone tried to use it. This change moves the declaration to the correct header and updates its function signature per PR #2775.
=> Fix an outdated pass-creation function declaration

.bazelrc, MODULE.bazel.lock, stablehlo/tests/BUILD.bazel
Issue was discovered and fixed in https://github.com/openxla/stablehlo/pull/2743, but lets enforce this to avoid breaking downstream users going forward.
This bazel flag will be flipped to default in bazel8 so might as well get ahead of things too.
=> Disallow empty globs in bazel

BUILD.bazel, stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/tests/transforms/stablehlo_target_independent_optimization.mlir, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp, stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp
If a `stablehlo.while` op's condition is a constant with a value of `false`, replace the op with its input.
Make an exception for preserving dead ops with side effects, which can't currently be DCE'd safely despite being unreachable. This is because dependent code is currently allowed to depend on the existence of ops with hypothetical side effects that show up in the unoptimized IR but can't actually occur.
Issue: #2736
=> Add a pattern for folding `stablehlo.while` no-ops

stablehlo/transforms/CMakeLists.txt, stablehlo/transforms/optimization/CMakeLists.txt
When attempting to link against `StablehloOptimizationPasses`, it throws a linker error for functionality found in `PassUtils.cpp`. 
Error
```
/usr/bin/ld: lib/libStablehloOptimizationPasses.a(StablehloAggressiveSimplification.cpp.o): in function `mlir::Value mlir::stablehlo::getConstantLike<int>(mlir::OpBuilder&, mlir::Location, int, mlir::Value)':
StablehloAggressiveSimplification.cpp:(.text._ZN4mlir9stablehlo15getConstantLikeIiEENS_5ValueERNS_9OpBuilderENS_8LocationET_S2_[_ZN4mlir9stablehlo15getConstantLikeIiEENS_5ValueERNS_9OpBuilderENS_8LocationET_S2_]+0x5c): undefined reference to `mlir::stablehlo::getConstantLikeImpl(mlir::OpBuilder&, mlir::Location, mlir::Attribute, mlir::Value)'
clang++-17: error: linker command failed with exit code 1 (use -v to see invocation)
```
The bazel …
=> Separated stablehlo pass utils into separate dialect library to fix cmake build for stablehlo optimization passes library

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
Add four missing patterns targeting Reduce ops:
- FoldReduceOpReducingZeroDims
- FoldReduceOpToConstantInitializer
- FoldReduceOpWithRedundantResults
- LowerBoolSplatConstantsIntoReduceOpRegion
Issue: #2736
=> Add patterns for folding Reduce ops.

stablehlo/dialect/StablehloOps.h
`::mlir::stablehlo::side_effects::InfeedResource::getName()` previously returned "OutfeedResource" instead of "InfeedResource"; this fixes it.
=> Fix typo in `InfeedResource::getName()`.

stablehlo/dialect/StablehloOps.td
Mark all StableHLO ops with any side effects as having both MemRead and MemWrite side effects to ensure we don't accidentally DCE them.
A recent test showed that a `recv` op was getting removed while a `send` op wasn't. This change fixes it so that neither is removed.
=> Mark non-pure StableHLO ops with both R/W effects.

stablehlo/tests/transforms/stablehlo_aggressive_simplification.mlir, stablehlo/transforms/optimization/StablehloAggressiveSimplification.cpp
The `CustomCallUnregisteredBackendConfigToFfi` pattern previously skipped a certain null check since the value was never supposed to be null, but checking it anyway seems prudent on second thought.
=> Add a (theoretically redundant) null check.

stablehlo/dialect/TypeInference.cpp
verification of an invalid while op otherwise causes a segfault instead of throwing the proper error message
=> Don't segfault verifying while without valid terminator

stablehlo/dialect/StablehloOps.h, stablehlo/dialect/TypeInference.cpp
We want to be able to use the `create<ReduceOp>(values,inits,dim)` API that relies on type inference, but type inference relies on a body existing.
Today, most users expect the reduce body to have arguments similar to the input types, with the _option_ to use different precisions in the body. If using type inference APIs we should still allow this and you cannot use a body region with different types. If you use the API where you explicitly set output type (no reliance on type inference) then you can have body region with different input argument element types.
=> Allow reduce-like ops to type infer without body region

stablehlo/tests/transforms/stablehlo_aggressive_folder.mlir, stablehlo/transforms/optimization/StablehloAggressiveFolder.cpp
When a `case` op is given a constant branch-selection index, replace the `case` op with the contents of the always-active branch. If any branches are non-trivially dead (i.e. dead but not functionally pure), the `case` op will not be deleted but will always execute a now-empty branch (since the original contents of the active branch have been inlined).
=> Fold `case` ops with constant branch indices
